### ISSUE TITLE
Pressing 'Esc' after a search should close the search

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#10]
Pressing 'Esc' after a search should close the search like if the user hit the [x] button on the search box.
That should be the behaviour if the search box do have the focus.

**Comment by aaFn** [comment]
Correct ... I will see to that.

**Comment by aaFn** [comment]
Implemented in 2.0.5. I will close unless not at our taste, let me know.

**Comment by aaFn** [comment]
Closed
