### ISSUE TITLE
Add option to customize background and text colors

### ISSUE THREAD

**Issue by aaFn** [aaFn/Bookmark-search-plus-2#100]
As per demand of James Band and other previously at https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/reviews/

**Comment by MithranArkanere** [comment]
If it is not possible to use the colors from the current firefox theme, it should at least have settings for them.

It would also be better if the addon icon and the search button matched better the firefox interface instead always being that colorful.

**Comment by aaFn** [comment]
Functions to set text and background colors, as well as to synchronize text and background colors in sidebar with the active FF theme, are provided as of 2.0.68, out tonight.

Let me know if any problem, aaFn.
