### ISSUE TITLE
always on

### ISSUE THREAD

**Issue by ohillary** [aaFn/Bookmark-search-plus-2#105]
in previous versions, I clicked on BSP2 to engage it. Now it is on every FF window upon opening. How can I stop it from automatically turning on?

thnx
ohillary

**Comment by aaFn** [comment]
Hello @ohillary, it has always functioned like that, nothing changed in BSP2.
Basically, when FF opens a new window, it opens the same contents in the new window sidebar:
- If original window had the native FF bookmark sidebar open and showing, then the new window has it also
- If it was BSP2, then the new window also
- If there was nothing, then the new window has nothing

And when opening FF first window, it shows the sidebar which was opened when closing FF (or none if no sidebar was open).

Or let me know if I am missing your question.

**Comment by ohillary** [comment]
OK aaFn,
thanks for response. I guess I had too many windows open and one of them had the sidebar present. Upon reboot, all instances of FF had bsp2. I had never seen that so I thought it was a new "thing". thanks for reply and thanks again for this critical improvement to storing and retrieving bookmarks.
ohillary

________________________________

**Comment by aaFn** [comment]
Welcome. Closing the issue as answered question then.
Thanks, aaFn.
