### ISSUE TITLE
Where is the folder.png located? I want to change it to a yellow folder.

### ISSUE THREAD

**Issue by shoulders** [aaFn/Bookmark-search-plus-2#106]
I am running windows 10 and have searched my harddrive for the folder.png so I can swap it out but cannot find it.

Is it possible for me to swap the folder for a yellow folder so it looks more like Internet Explorer?

Thanks

**Comment by shoulders** [comment]
**Solution:**

1. Install Bookmark Search Plus 2 (if not already)
2. Find the file **bookmarksearchplus2@aafn.org.xpi** (should be in your profile folder)
3. Change its file extension to *.zip
4. Open up the zip file
5. Replace or edit the file /icons/folder.png with your new icon
6. Save the changes to the zip
7. Rename the zip back to *.xpi
8. Start FireFox and Bookmakrs Search Plus 2 to see your new folder icon.

**Notes**

- This will nbeed to be done for each profile using this extension
- Updates to the extension will wipe out the changed icon

**Comment by aaFn** [comment]
Indeed, that is the good way :-)

**Comment by shoulders** [comment]
Making these modifications can cause the extension to be disabled becasue xpi are now signed as a requirement to run in FireFox.

**Comment by aaFn** [comment]
Ah yes, that is right .. but I believe #112 should now answer your need :-)
It is out since 2.0.74
