### ISSUE TITLE
Prepare tree display takes hours

### ISSUE THREAD

**Issue by 532910** [aaFn/Bookmark-search-plus-2#107]
`Prepare tree display..` takes hours

**Comment by aaFn** [comment]
Hello @532910, can you enable the traces in the add-on options panel of BSP2, and copy here the text contents of the box that will reveal ?

**Comment by 532910** [comment]
Hmm, it works fine right now! I'll leave it enabled and will copy the output next time.

**Comment by aaFn** [comment]
Ok, I'll watch here, thanks

**Comment by aaFn** [comment]
Closing as no sign of it coming back.
Thank you, aaFn.
