### ISSUE TITLE
Does not find by tags

### ISSUE THREAD

**Issue by sparrowek** [aaFn/Bookmark-search-plus-2#108]
When I add some tags to the bookmark I can find by them in the location bar but the Bookmark search plugin does not respect them, ie. I cannot find the bookmark in the sidebar when typing the tag.

**Comment by aaFn** [comment]
Hello @sparrowek , correct, the Firefox WebExtension API does not give access to tags.
Add-ons cannot see them.

A bug is open on Firefox to get that https://bugzilla.mozilla.org/show_bug.cgi?id=1225916 (only 4 years old)

**Comment by aaFn** [comment]
Closing for now, will reopen when FF API allows add-ons to access or manipulate tags.
Thanks, aaFn.

**Comment by sparrowek** [comment]
I am not sure whether it is still impossible since Ctrl+B does use tags?
