### ISSUE TITLE
Keyboard shortcut not displayed int the sidebar menu on Linux

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#11]
> That said, on Linux:

> however, it is not displayed in gray in the switch-panel menu, like for others and on macOS

Quote from issue #4

**Comment by NicolasWeb** [comment]
Quote from issue #4
> Last, the shortcut is indeed not displayed in the sidebar switch-panel menu. Apparently this is the same for all sidebar add-ons I could test, and I didn't find a way to make it display .. FF simply doesn't appear to make that available.

Do you mean on Linux only ? I can see it on macOS

**Comment by aaFn** [comment]
On both Windows and on Linux, I can't see it .. I do not know about MacOS as I do not have any.
So I am not sure what to do about it :-(

**Comment by NicolasWeb** [comment]
There might be a Firefox core bug.
We could look into [Bugzilla](https://bugzilla.mozilla.org) if there's already a bug opened.

I've founded [these](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=WebExtension+shortcut). Seem like we should open a bug...

**Comment by aaFn** [comment]
Ok, I don't have an account there ... and last time I tried to create one, it said to me:

> User account creation has been restricted. Contact your administrator or the maintainer (bugzilla-admin@mozilla.org) for information about creating an account.

I just tried again to make sure .. not sure that if I write to bugzilla-admin@mozilla.org I will get any echo ??

**Comment by NicolasWeb** [comment]
@aaFn Really. It doesn't seems to be the case now : [https://bugzilla.mozilla.org/createaccount.cgi](https://bugzilla.mozilla.org/createaccount.cgi)

**Comment by aaFn** [comment]
Yes, I clicked on "Create account", and that gave me the message above ...

**Comment by NicolasWeb** [comment]
@aaFn I'm on IRC irc://irc.mozilla.org/bugzilla and admin are askink for your hostname (and TLD).
Can you join ?

[Getting Started with Mozilla IRC](https://wiki.mozilla.org/IRC)

**Comment by aaFn** [comment]
Ok, I'm there with Mibbit -> http://chat.mibbit.com/?channel=%23bugzilla&server=irc.mozilla.org
Can see the history with the logbot (very rarely used IRC before, I seemed to remember that history would show up on "connect" but apparently not, I get a blank page ..).
I posted there .. I think I see what is the problem ..

**Comment by aaFn** [comment]
@NicolasWeb , ok, I am in. Going again in business travel, will be slow in the coming 3 days ... so I guess I'll look at opening the bug around Friday. Thanks for the help.

**Comment by NicolasWeb** [comment]
Okay, found what happen... I'm using Nightly on macOS and and according [These weeks in Firefox 32](https://blog.nightly.mozilla.org/2018/02/15/these-weeks-in-firefox-issue-32/) that's a recent bug fix in Firefox : [The key combination to open a WebExtension sidebar is now shown](https://bugzilla.mozilla.org/show_bug.cgi?id=1344815) in the switcher dropdown and the sidebar menu.

This bug should be marked as fixed.

**Comment by aaFn** [comment]
Ok .. let's keep that one open until we get the next version distributed ... for now I have 58.0.2 and the bug is stille here

**Comment by aaFn** [comment]
I see that now (FF 60.0.1), this fix is distributed -> closing the issue.
Thank you @NicolasWeb .
