### ISSUE TITLE
Feature Request - remove icon in toolbar

### ISSUE THREAD

**Issue by stef204** [aaFn/Bookmark-search-plus-2#113]
Issue #36 quoting you:

> I found it is not possible to make the button appear on option .. As soon as it is specified in the add-on, it is here and cannot be removed by code.
> So it will be here for all, no option to show or to hide it .. :-(
> 
> For people finding the button annoying, they will have to manually remove it from the toolbar.
> Sorry.
> 

Even when one manually removes icon from toolbar (using "Customize" and dragging and dropping it off the toolbar), icon reappears on next restart.

This should be disabled altogether; or made optional if possible (but from your statement quoted above, you seem to imply not possible to disable/enable.)

**Comment by aaFn** [comment]
Hello @stef204, that works for me, simply right click on the button and click on "Remove from toolbar".
The button disappears, and when restarting FF, it is not coming back
This is working like that for all add-ons, this is controlled by FF only, not by the add-ons.

**Comment by stef204** [comment]
@aaFn  Thanks for your reply. Unfortunately, this does not happen here; when doing what you describe--as stated in my op--the icon reappears on next startup.  Anything in your code which might cause this problem? I do not have this issue with any other addons.

**Comment by aaFn** [comment]
Hello @stef204 , BSP2 just do standard code as per https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction

See the example add-on provided by mozilla -> https://github.com/mdn/webextensions-examples/blob/master/bookmark-it/background.js

Code in BSP2 is much identical:
```
	browser.browserAction.setTitle(
	  {title: title2
	  }
	);
	browser.browserAction.setIcon(
	  {path: "icons/star2.png"
	  }
	);
	browser.browserAction.onClicked.addListener(buttonClicked);
```

Nothing special .. It works well everywhere here (Windows 10, Linux, Windows 7) on my multiple machines, the button does not reappear once I right click on it and remove it from the toolbar.
I have Firefox 68, an dthe only way to make it reappear is to specifically go to customize and to right click it there to add it again.

Which OS, version of Firefox and BSP2 do you have ?

**Comment by stef204** [comment]
@aaFn 
my experience differs.
there is NO way currently that I am able to REMOVE the icon permanently.
Have tried all available options to do so but keeps coming back on restart.
I even edited user.js and prefs.js (with FF closed) to remove "bookmarksearchplus2_aafn_org-browser-action" from "user_pref("browser.uiCustomization.state" .....  but there is no impact.  Icon comes back.
running FF 68, Linux 64 bit, BSP2 2.0.65

**Comment by aaFn** [comment]
Not sure what is happening here. On my 3 Linux 64 bits (Void Linux with Mate, Void Linux with KDE5, and RHEL 7.6 with Xfce), all is fine, I just checked again.

Would you mind testing with a new profile, from scratch ?
Start firefox from command line::

`firefox --ProfileMaanger`

This will give you a popup where you can create and start a new blank profile, then load BSP2 in it, and verify.

**Comment by stef204** [comment]
there must be some type of corruption or some other extension impacting this issue as the problem is NOT present with a test profile in FF.
Can't quite really figure out what it could be so will have to troubleshoot, either delete user.js and/or prefs,js to start fresh and see; or disable the few extensions I have one by one and see if any impact this issue.
Will post my findings here.

**Comment by aaFn** [comment]
Ok, let me know ... thank you aaFn.

**Comment by stef204** [comment]
I wasn't looking forward to migrating to a new FF profile--but I did and all is fine, icon stays "removed" from toolbar when using "Remove from Toolbar".
Thanks.

**Comment by aaFn** [comment]
Hello @stef204 , ok, glad the problem is solved.
Starting with a new profile may have cured a few other things you will discover later by the way :-)
(and you can still keep the old one around for some time until you are sure all is ok)
