### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by grahamperrin** [aaFn/Bookmark-search-plus-2#116]
![image](https://user-images.githubusercontent.com/192271/64502505-526cec00-d2be-11e9-84b9-632ec71c8268.png)

I like to see release notes before updating extensions, Bookmark search plus 2 is amongst the extensions for which notes are not available:

- https://github.com/aaFn/Bookmark-search-plus-2/wiki#user-content-release-notes offers notes for 2.0.66 but not 2.0.67

**Comment by aaFn** [comment]
Hello @grahamperrin , I had forgotten to update the wiki.
Done now.

Thank you, aaFn.

**Comment by grahamperrin** [comment]
Thanks and ✰✰✰✰✰

**Comment by SteegHobland** [comment]
Still a bit annoying that the notes don't show directly in the place provided to view release notes. You get the extra step of following a link instead.

**Comment by aaFn** [comment]
Correct, but this content is on the AMO Web when doing the steps of creating the new release, and is not the best place or the most easy thing to do.
That is why the link .. which is always the same, and a carry forward. Plus, with the link, one has the complete list, not just the last one 😃

**Comment by SteegHobland** [comment]
you are right about that, of course
