### ISSUE TITLE
[Enhancement] Automatically give focus to "Search bookmarks" textfield when opening the side bar

### ISSUE THREAD

**Issue by liar666** [aaFn/Bookmark-search-plus-2#118]
Hi,

Thanks for the Add-ons, it saved my ass in multiple occasions. I find it quite strange that getting the "parent folder" of a bookmark is not considered mandatory by the firefox team and a feature of the default tool.

I have just one remark for an enhancement:
When I hit CTRL-SHIFT-b to open the sidebar, I then have to use the mouse to click inside the "Search bookmarks" textfield in order to be able to enter my query. 
It would be great if this textfield would automatically get the focus, so that I can use my keyboard only to search for bookmarks, instead of switching back-and-forth between mouse and kb.

**Comment by aaFn** [comment]
Closing, we will act on it and reopen if needed when FF has created the feature.
