### ISSUE TITLE
Can't find ⓘ in address bar

### ISSUE THREAD

**Issue by nkennington** [aaFn/Bookmark-search-plus-2#119]
The instrtuctions for Bookmark-search-plus-2 at Firefox: about additions say, "drag the ⓘ in the address bar or drag web page links into the sidebar, and insert them in the tree at the place you like".
I can't find the  ⓘ in the address bar, although I used to be able to.  What am I doing wrong?

**Comment by aaFn** [comment]
Hello @nkennington , indeed, they changed it, not sure with which version because I didn't pay attention to it, but probably around FF 68 ...

=> Now apparently this is the little padlock which is playing that role

I corrected the instructions accordingly. Let me know if you have any other question.
Best regards, aaFn.

**Comment by nkennington** [comment]
You invited me to let you know if I have any other questions.  I don't know how to that without adding a new comment like this for the public to see.  Is there any way that you would like me to respond privately to you?

You said " Now apparently this is the little padlock which is playing that role."  I can't get the little padlock to work as the ⓘ used to work.  Can you help me figure out how to do that?

You also said that "I corrected the instructions accordingly.".   I can't find the corrected instructions.  Can you help me find them?  (Maybe with a URL?)

Thank you for responsing,
nkennington@juno.com

**Comment by aaFn** [comment]
No need for private exchanges, My question is to make sure I addressed properly the point you initially raised.

Refreshed instructions are on the add-on page: https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/

About the way to work with the little padlock, simply click and drag it to the sidebar (like with the ⓘ in the past), and it will create a new bookmark for the current displayed page, at the place where you dropped it.
Note that another way to get the same effect is to click and drag the tab handle at top, and to drop it where you want in the bookmark tree, in the sidebar.

Hope this helps.
