### ISSUE TITLE
please add a feature to select multiple bookmark/bookmark folder

### ISSUE THREAD

**Issue by wtfiwinomgs** [aaFn/Bookmark-search-plus-2#120]
as title suggested, please add a feature to allow ctrl and shift for selecting multiple bookmark / bookmark folder in the sidebar. that way we can delete, mass select and move a bunch of bookmarks at the sametime.

right now it only allows 1 selection at a time, unlike the tabs allow multiple selection via ctrl for jump selection or shift for through selection. bookmarks need it too!

**Comment by aaFn** [comment]
Hello @wtfiwinomgs , correct, and this is duplicate with #29.
Can you please add your demand there ?

**Comment by aaFn** [comment]
Closing this one as duplicate of #29, will follow up there.
Thanks aaFn.

**Comment by wtfiwinomgs** [comment]
so it has been a year.. any update on this?
