### ISSUE TITLE
Make SBP2 listed in a replacement collection on AMO

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#13]
Legacy addons can propose a WebExtension equivalent through a click on the 'Find a Replacement' button on the Firefox Addons Manager.
I asked on IRC and on [discourse](https://discourse.mozilla.org/t/favorite-webextensions/17087/181) BSP2 to be listed in a replacement collection of Go-parent-Folder.

I will let you know how it is going forward.

#AMO: https://addons.mozilla.org/

**Comment by aaFn** [comment]
Thanks much for that.

By the way, the add-on is really meant to replace the old "Sidebar Bookmark Search Plus" XUL extension, which was a superset of "Go-parent-Folder".

**Comment by NicolasWeb** [comment]
[sdevaney](https://mozillians.org/fr/u/sdevaney/) answered on IRC that as the older extensions referenced as "removed by the author". If removed, Firefox replacement recommendation tool can't offer a replacement.
That's where we are now.
I'm trying to know if there a workaround to that, or a way to prompt users of this XUL add-on about the webExtension add-on, and if there is a technical reason for that implementation limiting on recommendations. Trying to go forward...

The recommendation tool as been first mentioned on this [discourse thread](https://discourse.mozilla.org/t/favorite-webextensions/17087) where you can find the [github repo](https://github.com/mozilla/addons-server/issues/5637)

**Comment by NicolasWeb** [comment]
Okay, done !
A workaround have been found : Now a user who click on the button `Find a Replacement` (Add-on manager/Legacy extensions) will be directed to SBP2
:)

**Comment by aaFn** [comment]
Hello @NicolasWeb , excelllent ! Thank you
