### ISSUE TITLE
Ctrl+Q focus

### ISSUE THREAD

**Issue by sparrowek** [aaFn/Bookmark-search-plus-2#132]
It would be nice if pressing Ctrl+Q gave focus to the input field like Ctrl+B does.

**Comment by aaFn** [comment]
Hello @sparrowek , indeed .. alas not yet possible -> https://bugzilla.mozilla.org/show_bug.cgi?id=1502713

**Comment by aaFn** [comment]
Closing the issue for now, while waiting for FF to fix the bug.
Thanks, aaFn.

**Comment by braham-snyder** [comment]
If you'd like to see this issue -- thus that firefox bug -- fixed, you might want to vote for that bug. You can login using your github account.
