### ISSUE TITLE
Newly added bookmark is not shown

### ISSUE THREAD

**Issue by chr7** [aaFn/Bookmark-search-plus-2#134]
I noticed the following recently (used to work before):

If I drag and drop a tab on an open folder in the bookmark tree, the bookmark doesn't show up in the folder. I have to switch off and on again 'Bookmark search plus 2' in the sidebar to have the bookmark shown as the last entry in the folder.

It works if I drag the tab to a position inside the bookmark folder.

I have version 2.0.75 installed and FIrefox 73.0.1

**Comment by aaFn** [comment]
Hello @chr7,it works fo me. So something wrong specific to your setup must be going on.

Can I ask you to:
- Open the browser console (Ctrl+Shift+J)
- Click on the "Console Settings" wheel (top right)
- Activate "Show Content Messages"
- Empty it (tray icon on top left)

Then do your drag & drop operation to a folder operation.
And then look back at the browser console, copy its content, and paste it here ?

Hopefully, we will catch an error which explains what is happening ...

**Comment by chr7** [comment]
It seems that this was a temporary problem, I can't reproduce it anymore.
