### ISSUE TITLE
Addon not fully working after bookmark desynchronization message

### ISSUE THREAD

**Issue by Speravir** [aaFn/Bookmark-search-plus-2#135]
When I search for a bookmark I sometimes run into the message (from memory) “Detected desynchronization of bookmarks. Wait for reloading”. The issue here is that after the message disappears the search does not work at all until I restart the browser so essentially I can not use the addon. (Well I can, but the other functions are available in the default bookmark sidebar, as well.)

I sometimes tried a second time only to see the message appearing for a very short time and afterwards on a third or fourth trial nothing at all of the expected action happened.

The last version without this issue is 2.0.70, but it can’t be soluton not updating the addon.

**Comment by aaFn** [comment]
Hello @Speravir , strange when this message appears, the add-on sort of gets reloaded.

1. What is exactly the visual symptom of "search does not work at all" ?
2. Could I ask that you start the browser console in background (Ctrl+Shift+J), activate content messages (Click on the "Console Settings" wheel at top right, then Activate "Show Content Messages" if not already activated), and then on next occurrence of the problem, you copy here the content of the browser console ? (say the last 100 lines, trying to catch BSP2 error messages) ?

Thank you, aaFn.

**Comment by aaFn** [comment]
While waiting for your return, I started to re-examine the code in such situations. Didn't find much, maybe a case where handling a detected de-synchro case could be more robust by immediately breaking from a loop where it was detected and signalled, but I am dubious this should be causing your problem.

So let me know when you are getting it again and are able to get something.
Or at least if you can describe the symptom more precisely, that will help me make conjectures :-).

Cheers, aaFn.

**Comment by Speravir** [comment]
It did not occur again, until now. Which reminds me of this I forgot above: As far as I remember for all search terms this did not appear twice: Apparently, once the bookmarks are synchronized for a certain group all is fine for it. Maybe there is some kind of corruption here?

Regarding your first question above: When I started entering letters into search input field I could for a short time (half a second or so) see the first results, but then all disappeared showing the message. Also, the input field is cleared. On a second try the message is shown shortly, the search is cleared, again. Beginning from a third attempt _nothing at all_ happens when entering letter into the search field.

**Comment by Speravir** [comment]
It still did not happen again on entering news search terms, but today I wanted to do another search and started deleting the entered term and this happened:
```
20:41:07.021 sendRemoveListener on closed conduit bookmarksearchplus2@aafn.org.412316871674 ConduitsChild.jsm:108
20:41:07.629 Error: CallResult for closed conduit bookmarksearchplus2@aafn.org.412316871851: ({childId:"bookmarksearchplus2@aafn.org.412316871851", callId:412316871863, path:"sidebarAction.setTitle", result:{}}) ConduitsChild.jsm:167:13
20:41:07.629 sendRemoveListener on closed conduit bookmarksearchplus2@aafn.org.412316871851 ConduitsChild.jsm:108
```
The desynch message appeared for a very short time.

`Conduitschild,jsm` is from Firefox (v.74 in the moment): `resource://gre/modules/ConduitsChild.jsm`.

Lines 106–112 are
```js
_send(method, query, arg = {}) {
  if (!this.actor) {
    throw new Error(`send${method} on closed conduit ${this.id}`);
  }
  let sender = this.id;
  return super._send(method, query, this.actor, { arg, query, sender });
}
```
and lines 166–168 are
```js
if (!conduit) {
  throw new Error(`${name} for closed conduit ${target}: ${uneval(arg)}`);
}
```
So, the lines are the ones with `throw new Error` (no surprise).

**Comment by aaFn** [comment]
Ok, so you fell again on a de-synchro case, detected by BSP2. This means:
- there was a bookmark known by FF and not by BSP2
- or from my experience, more exactly, a bookmark still known by FF while it was deleted and acknowledged as deleted by FF
- and so BSP2 decided to reload the full set, and then to restart the sidebars, to re-synchronize
- the error sequence above is typical of a sidebar reload, it says a message was being sent to the sidebar but it was not there because it closed its conduit when the background task sent something to it).

Well, let's assume then that the first time(s) you got on a more complex situation which is not happening anymore, and hopefully my robustness patch will address it.
And then let's monitor. It will be in 2.0.76.

I would be interested in how often you have auto-reloads, but next release should give a tool for that, by introducing a way to see the history of actions received by BSP2 (#75)

**Comment by Speravir** [comment]
Today I got v. 2.0.76 as addon update. I took a quick check with some query items where I knew I did not searched them before (I bookmarked them quite recently). I got no display mess, and also no error message at all with them, so I consider this case as solved. Thank you, aaFn.

**Comment by aaFn** [comment]
Thanks for the quick feedback @Speravir.
So I will consider the robustness patch does it for now, and we'll see if anyting comes back one day :grinning:
