### ISSUE TITLE
[Feature Request] When we are in a bookmarked page, then when opening "bookmarks sidebar" been scrolled to and been highlighted the bookmarked page auto

### ISSUE THREAD

**Issue by Saadish** [aaFn/Bookmark-search-plus-2#137]
Hi,
i want when i open one of the bookmarked pages via urlbar, or suddenly visit it, then by opening the bookmarks sidebar, automatically scrolls down and locates the bookmark and highlights it. Maybe I want to quickly rearrange it or move it up.

Thanks.

**Comment by Saadi1988** [comment]
sorry, i can't dict the title well! my language is not english.

**Comment by aaFn** [comment]
Hello @Saadi1988, not exactly sure I understand you.
1. Can you detail how you open a bookmarked page in your scenario ?
    - What do you mean by "via urlbar" ?
    - Is it by typing the URL by hand in tghe address bar, and then where do you get the URL from ?
    - Or by clicking on some link ?
2. How do you know it is an already bookmarked URL ?

Would it be sufficient that when the current tab is on an already bookmarked URL, you can right click on the BSP2 icon in the toolbar and have a context menu to "show current tab in bookmarks" ?

Please note that there is today an easy way to locate a bookmark for a page in current tab:
- Copy the URL in the address bar
- Paste it in the BSP2 searchbox
- Then the search pane will show you all bookmarks whose URL match the current page

**Comment by Saadi1988** [comment]
> 
> 
> Hello @Saadi1988, not exactly sure I understand you.
> 
>     1. Can you detail how you open a bookmarked page in your scenario ?
>        
>        * What do you mean by "via urlbar" ?
![Untitled1](https://user-images.githubusercontent.com/42292489/79282536-b990f580-7eca-11ea-8df3-8f586252ac85.png)


>        * Is it by typing the URL by hand in tghe address bar, and then where do you get the URL from ?

yes.

>        * Or by clicking on some link ?

yes too.

> 
>     2. How do you know it is an already bookmarked URL ?
![Untitled2](https://user-images.githubusercontent.com/42292489/79282695-1096ca80-7ecb-11ea-842e-1e4ea65df49c.png)


> 
> 
> Would it be sufficient that when the current tab is on an already bookmarked URL, you can right click on the BSP2 icon in the toolbar and have a context menu to "show current tab in bookmarks" ?

yes.

> 
> Please note that there is today an easy way to locate a bookmark for a page in current tab:
> 
>     * Copy the URL in the address bar, and paste it in the BSP2 searchbox
> 
>     * Or easier, click inside the address bar, and when the URL is highlighted, drag it and drop it on the BSP2 searchbox
> 
>     * Or even easier, drag the little icon in the address bar (often a lock when on an https page) into the BSP2 searchbox
> 
> 
> Then the search pane will show you all bookmarks whose URL match the current page

yea, but this requested feature is for faster doing our purpose. 

Thank you.

**Comment by aaFn** [comment]
Hello @Saadi1988 , well you taught me something, I never noticed that when the drop down was open on the URL address, there was a tiny blue star to say which addresses are already boookmarked :-)

Ok, I will see what I can do on the BSP2 icon context menu in the toolbar to make it contextual to the URL in the current tab.
Should be in 2.0.76 if I can find a way.

**Comment by Saadi1988** [comment]
Thank you, brother. You can add this feature to be enabled in options. So that every time we open a bookmarked url, and then click on BSP2 icon, auto-scroll and show the Bookmark.

**Comment by aaFn** [comment]
Hello @Saadish , this is in 2.0.76 which is out now.
Let me know if any  problem.

Thanks, aaFn.
