### ISSUE TITLE
add link to alternative folders repo

### ISSUE THREAD

**Issue by shoulders** [aaFn/Bookmark-search-plus-2#138]
In the options page it might be a good idea to point to the folder icons repo

https://github.com/aaFn/Bookmark-search-plus-2/tree/master/altFldrIcons

This allows people to go and find the alternative icons easily, not all end user knows about looking on github for these little easer eggs.

I would also ask users who push icons, to supply a link to the license for that icon

**Comment by aaFn** [comment]
Hello @shoulders , this is a good idea.
I just modified the repo to mention the request for license, and I will add a link to the repo besides the Alternate folder option in 2.0.76.

Thanks, aaFn.

**Comment by aaFn** [comment]
2.0.76 published now. Thanks, aaFn.
