### ISSUE TITLE
Bug: Tags are  removed after modifying a bookmark Address from BSP2

### ISSUE THREAD

**Issue by brain8891** [aaFn/Bookmark-search-plus-2#141]
1- create a bookmark 
name: test1 
Address test1.com
Tags: testing website

![image](https://user-images.githubusercontent.com/7104190/81054974-d5d7ef00-8ed8-11ea-80bb-5961a456c9d2.png)

2- Ctrl+Q> search "test1" > right click> properties > change URL to test2.com> Save
![image](https://user-images.githubusercontent.com/7104190/81055100-12a3e600-8ed9-11ea-9f9f-6edc4247b249.png)

3-  in FF bookmark manager go to test1 bookmark and right click > properties:
you will see it removed
![image](https://user-images.githubusercontent.com/7104190/81055198-43841b00-8ed9-11ea-95f0-cf083f32d22b.png)

interesting:
if you changed that particular bookmark Address back to test1.com within BSP2 it brings back the tags, so that might indicate how bookmarks addresses are associated with tags and not that particular bookmark entry. 

also notice that changing the [Address] entry from the default Firefox menu won't reproduce this bug

a question to aaFn:
1- Would you please explain how BSP2 modify/save data? does it modify Firefox Bookmark file, or does it create a new one? 

 2- When you fix this issue, would explain why, why did this happen, I am afraid to use BSP2 ? 

3-  https://bugzilla.mozilla.org/show_bug.cgi?id=1225916
FF webextension API, so still doesn't allow access to Tag/keywords? I would vote but my email would be publicly listed! I don't know why they won't change that? but since you are working on this, is there any new/rumors s on this?

4- suggestion for users to feel secure about their data, why not call the default Firefox properties panel? I know it doesn't show the bookmark location, but it is not much needed, I think, so I suggest adding it to the options for users who would want the default Firefox panel.

thank you for your hard work, and BSP2 is much, much faster than the last time I tested it, I was amazed. Sadly though it is not a bookmark manager. Personally, I am looking for a software to manage "online URL's"  where I can assign folder icons, retrieve search tags automatically from the webpage, and sync with all of my browsers, and specially add DESCRIPTION! Much needed.  

Keep up the good work,

**Comment by aaFn** [comment]
Hello @brain8891 , there is only one way for an add-on to modify a bookmark, which is to call this API -> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/update

- This API doesn't allow anything on tags, and it is a complete black box.
- It is only an update, and by the way, you can now see that by opening the history window (click on the magnifying glass, or right click on the BSP2 icon in the toolbar), and you will see on the test you made above that the bookmark id, which is the internal FF reference, is not changing.

So the effect of removing the tag on address change (and reshowing it when the address is back !!) is a complete unknown to the add-on.

And frankly, I do not know how to explain that. I saw strange things in the FF code, where I believe a tag is stored like a bookmark, and it looks like it is then a parent of bookmarks which have this tag (and this explains slowness of some API calls when there are many bookmarks and tags) .. but I can"t understand why the linkage would change on changing the address.

Worst, re-doing your tests above, I can see that changing from test1.com to test1.com/testpath/ doesn't remove the tag, but as you say, changing to test2.com does ... and of course going back to test1.com re-shows the tag .. so this seems only related to the hostname part of the URL !?!

=> I can only infer there is a bug in FF.

And probably, that would deserve its own bugzilla .. I will research if such a bug already exists, or create it.
Now, I am afraid that won't be fast to be resolved .. Tags are clearly the "poor parent" topic in FF.

**Comment by brain8891** [comment]
> => I can only infer there is a bug in 

Looks like you are right, so for now  to mitigate this problem, calling the internal Firefox bookmarks property dialog will solve this.  

BSP2 use it's own properties window, I assume it is to show the Path: info, that is useful and give the user a good reference, so why not have two context menu:
1- properties: which call Firefox bookmark property window
2- bookmark path: which shows  the path. 


An additional suggestion:
1- when pressing [CTRL+Q] BSP2  side  bar opens, but the "Search Boookmarks.." filed is not active and you have to use your mouse, which is an additional step. 

Thank you for your hard work,

**Comment by aaFn** [comment]
Well, unfortunately, an add-on cannot call Firefox native windows or objects. That was possible in the old time of XUL extensions, but not anymore with WebExtension. So BSP2 can only open its own property window.

You are correct on the focus after Ctrl-Q. Again not a choice ... waiting for Firefoc to do something abour it ... -> https://bugzilla.mozilla.org/show_bug.cgi?id=1502713

**Comment by aaFn** [comment]
Hello @brain8891, I opened the bug on bugzilla -> https://bugzilla.mozilla.org/show_bug.cgi?id=1636755

Btw, on FF76, it seems the behavior changed a bit, now when I change the path it makes the tag disappear also, so no just the hostname.

Let's see how FF dev team will handle the bug .. meanwhile, I will close the issue as Dependency on FF to correct it, as I can't do anything on it for now. We'll reopen if needed when anything changes.

Thanks, aaFn.
