### ISSUE TITLE
Keyboard shortcut can't be changed on the long term

### ISSUE THREAD

**Issue by Wronschien** [aaFn/Bookmark-search-plus-2#144]
Hello, the default shortcut "Ctrl+Q" appears in Firefox shortcut manager and can be changed temporarily there. But as soon as the extension's options panel is opened or simply after a restart of Firefox, it reverts back to its default.
Could you please fix that ?

I'm using latest Firefox (76.0.1) on Windows 10.

**Comment by aaFn** [comment]
Hello @Wronschien , that works here, strange.
Can you try Ctrl + Shift + V  for example ? (this key combination is free on FF in windows 10)

**Comment by Wronschien** [comment]
Setting Ctrl + Shift + V is the same, but as you hinted at it I tried on a new profile and everything works fine. Well I have to find the incompatibility here, I do have quite a bunch of extensions.
Thank you for your quick reply !

**Comment by aaFn** [comment]
Closing as no more issue, aaFn.
