### ISSUE TITLE
Can't drag bookmark folders into firefox interfaces

### ISSUE THREAD

**Issue by Waltonvcl** [aaFn/Bookmark-search-plus-2#147]
I can't drag bookmark folders into firefox interfaces, like Bookmark bar or Library.
I can't copy and paste bookmarks on firefox interfaces.

**Comment by aaFn** [comment]
Hello @Waltonvcl , indeed this is a limitation of Firefox .. see https://bugzilla.mozilla.org/show_bug.cgi?id=1531539 (please vote for it :-) )

**Comment by aaFn** [comment]
Closing the issue until Firefox corrects the bug.
Thanks, aaFn.
