### ISSUE TITLE
Local Link does not open by mouse click

### ISSUE THREAD

**Issue by printpagestopdf** [aaFn/Bookmark-search-plus-2#149]
Local links (e.g. file://.....) can't be openend by clicking on it. Context menu (e.g. open in new tab) is working as expected. 
Clicking on such bookmarks in FF bookmark sidebar opens link.

**Comment by aaFn** [comment]
Hello @printpagestopdf , that is correct, this is a security feature of Firefox, add-ons cannot open local links. I guess this is to avoid they interact with local content ..

I f you want to see that by yourself:
- Open the browser console (Ctrl+Shift+J)
- Click on the "Console Settings" wheel (top right)
- Activate "Show Content Messages"
- Empty the console (tray icon on top left)

Then try to access a file://... bookmark from BSP2, you will see a error messages and security warnings saying an add-on cannot access such URLs ...

**Comment by printpagestopdf** [comment]
Hello @aaFn 

my apologize, I forgot what stupid things FF Development made with switching to WebAddons and throwing away the good old stuff that enabled sophisticated AddOns.

Best regards and many thanks, I am using your AddOn frequently.

**Comment by aaFn** [comment]
Welcome, thank you :-)
