### ISSUE TITLE
Toolbar button has no effect in Waterfox Classic

### ISSUE THREAD

**Issue by c33s** [aaFn/Bookmark-search-plus-2#150]
the sidebar bookmark management works like charm but the button added to the toolbar is greyed out and clicking on it has no effect. sometimes it shows the default green puzzle addon icon and sometimes the correct bookmark search plus 2 icon. 

opening the browser console and clicking on to bookmark search plus 2 icon gives no output. it's just greyed out.

bookmark search plus version: 2.0.78 
waterfox version:  2020.06 classic

**Comment by aaFn** [comment]
Hello @c33s , I am not sure how Waterfox Classic is working. It probably reproduces Firefox before version 57 to keep old extensions working, a,nd in such a case, many feautres of newer web extensions would not work.

Do you get a "Button not working in FF56 !" message when you hover your mouse pointer on the toolbar icon, and remain there ?

**Comment by aaFn** [comment]
Closing the issue as I do not use Waterfox and can't check.
Please reopen if you have more details to bring.

Thanks, aaFn.
