### ISSUE TITLE
Feature Request:  Go To Folder / Show Folder in Library

### ISSUE THREAD

**Issue by VLM-TechEd** [aaFn/Bookmark-search-plus-2#152]
Would you consider making a version of this that works in the Library instead of the Sidebar? As someone with visual impairment, I really benefit from viewing bookmarks full-screen, in the Library. I imagine at least some others may experience the same.

Thank you for considering this request.

**Comment by aaFn** [comment]
Hello @VLM-TechEd , alas Firefox doesn't allow WebExtension add-ons to run inside the bookmark library (at least until now)

**Comment by VLM-TechEd** [comment]
Thanks for responding so quickly! Unfortunately, I use the various columns and data fields (e.g., keyword) in the Library version quite extensively. But this may help someone else. Too bad they won't open the Library to developers. They did gain speed with Fx 57+, but they gave up a lot, too.

Thanks again!
