### ISSUE TITLE
Search for whole words like LED. Versus pulled. + BSP2 ranking in AMO searches

### ISSUE THREAD

**Issue by Twistyness** [aaFn/Bookmark-search-plus-2#156]
Hello again! Is there a way to restrict searches to looking for whole words like LED. Versus pulled ("led" is at the end of the word). A lot of words have "led" in them. 

In the Firefox browser the "find in this page" search (edit menu) gives the option to click on "Whole Words". And "Match Case". Both would help in searching for "LED". 

I noticed you link to this French language page: 
https://addons.mozilla.org/fr/firefox/addon/bookmark-search-plus-2/reviews 

Out of curiosity what is your native language?

**Comment by aaFn** [comment]
Hello @Twistyness, BSP2 now supports searches with [regular expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) (see this [cheatsheet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet)) to address cases more complex than simple words:
- click on the magnifying glass button (= filter button) besides the search box
- select "Use regex" in the menu which just opened
- then type the appropriate regex string in the search box
- in your case, for finding bookmark items containing a word ending in "led", you can use the search string `led\b` (note that BSP2 converts to lowercase and normalizes strings by removing diacritic when searching, like the native FF bookmark sidebar, so "match case" is not a possibility right now)
- for matching "led" as a whole word, use `\bled\b`
- refer to the cheatsheet mentioned above for variations, regex are very powerful.
The price to pay is a bit more complexity, but this is manageable
- to make sure you are not getting more matches than necessary, select "Title only" in the filter button menu, as you are probably not interested in bookmarks with matching URLs

When you are tired of using special matching mode / scope, just click on the reset filter button, at front of the filter button, and all will return to default.

I guess the link you mention is an error when I copied it, I corrected it, thank you. Yes, that tells you what my native language is.

**Comment by Twistyness** [comment]
Thanks! I suggest putting **"Whole words"** as an option in the menu. Most people have no clue about regex. I only use it rarely, and just copy stuff others recommend in answer to my question. 

So you are a French native speaker. I can read and speak some French. I am a native English speaker. I mention all this because on the Wikimedia Commons I have file renaming rights. So I sometimes change the name of a file to make it show up better in searches. 

It's been around a year and a half since I last wrote anything here. I notice that this great addon only has around 2200 users. I believe (like with file names on the Commons) that the name of an addon or file is very important for finding them in searches. I know a lot of people want to be able to search for **FOLDERS** in bookmarks. 

I suggest changing the addon name to:
**Bookmark search plus 2, and bookmark folder search**

**Comment by aaFn** [comment]
Thank you. In fact the displayed number of users decreased for all add-ons because displayed numbers only count people who agree to have their data used by Mozilla .. as I get it. I think before that change, it was around 4000 or more.

Anyway, I'll see what I can do about the title, I believe you got a good point.
Thanks, aaFn.

**Comment by Twistyness** [comment]
I noticed that the regex method you mentioned for whole word searches also works for phrase searches. Thanks again.

**Comment by aaFn** [comment]
As a matter of fact, standard (word) search is doing things like the native Firefox bookmark sidebar, and it is based on firefox API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/search; I cannot modify its behavior nor its syntax.

This is why I introduced regex, using native capablities in the Javascript library provided by Firefox. It allows much more powerful and advanced searching, and is not too difficult to master for a user, for simple things.
Coding a custom search myself, with my own syntax, would be significant work however. And I do not see a lot of added value for that. Given that there is already regex, it would be quite redundant.

**Comment by Twistyness** [comment]
Regex is not easy. I can understand why a developer may think so. :) 
I have had these kind of discussions with developers on wikis. 
Could you encode the regex for phrase search into an option or checkbox for "phrase search"? That way the user does not have to learn regex. And you the developer can use regex as the method to do the phrase search.

**Comment by aaFn** [comment]
I guess I could, but then this is opening the door to many variations and as many options to add ... and to manage in the UI menu, because people will want more than "phrase search" or will prefer other things.
That would be a candidate for future when other things are done, to provide something easier to use than regex (but more complexity in code) => not now then ..

**Comment by aaFn** [comment]
> I suggest changing the addon name to:
> Bookmark search plus 2, and bookmark folder search

I just made a search on "bookmark folder search" on https://addons.mozilla.org/en-US/firefox/, and BSP2 show 4th, behind 3 Mozilla recommended add-ons : first one is "Default Bookmark Folder", second is TST and 3rd is Feedbro
=> none of them really answer the need nor the question, do they ? And then BSP2 alternatives are listed after it in the search result

So not sure then if changing something in the title could change anything to AMO search results. What do you think ?

**Comment by Twistyness** [comment]
The problem is that the ones above BSP2 are not useful for bookmark folder search. So after people try out some of the top 3 and find no bookmark folder search, they may not ever get around to trying BSP2. Whereas if "bookmark folder search" is in your title then people are much more likely to try it. Especially when they have no luck with the top 3. They may even try BSP2 first because "bookmark folder search" is in the name. And over time BSP2 may rise to the top of a search for "bookmark folder search".

One problem I noticed is that the short description of BSP2 on the search results page does not really indicate there is bookmark folder search. It mentions parent folders, but does not say whether folder names are part of the search: 

"Displays and filters bookmarks on search string, show parent folders. This is a Web Extension add-on version of the old 'Bookmark search plus' XUL extension published by Alice0775, not working anymore in Firefox 57+, which was very useful."

**Comment by aaFn** [comment]
Ok, what about:

> More complex search and filters on bookmarks, show location of a bookmark in its respective bookmark folder (show parent folder, go parent folder).
> Continuation of the old "Bookmark search plus" XUL extension by Alice0775, not working in Firefox 57+

**Comment by Twistyness** [comment]
How about this below. From the most important to the less important (to the average user). 

> Search bookmarks or folders or both. See exact location in bookmark tree. Advanced searches via regex.

**Comment by aaFn** [comment]
Looks better indeed, good suggestion :-)
I want to keep mentioning "show/go parent folder "as they are old functions known on the Internet = look for "bookmark show parent folder" in Google, and you will see what I mean ... I also feel the first sentence must be easy and quick to read, even if simplifying a bit, to get a hook.

So that would give:

> Search for both bookmarks and folders. Find exact location in bookmark tree (show parent folder, go parent folder). Advanced filters and searches, use regex.

**Comment by Twistyness** [comment]
Yes, that sounds better.

**Comment by aaFn** [comment]
Ok, done, The description is now shorter and hoepfully more impactful.
That doesn't change the AMO search ranking, still being #4, but that was expected 😄

**Comment by Twistyness** [comment]
Great. I noticed that it is number 3 in a search for "folder search". Instead of "bookmark folder search". I think the simplest thing to add to the end of the addon name is: "Folder search too". So the full name would be . "Bookmark search plus 2. Folder search too".

**Comment by aaFn** [comment]
Close of the issue for now:
- Can't do better on AMO searches, it appears that for some reason "AMO Recommanded" add-ons go first in the results list, even when they are less relevant (e.g. Default Bookmark Folder, TST or Feedbro are all shown before BSP2 on "search bookmark folder" results, even though they do not satisfy search of bookmark folders to my knowledge !)
- Adding a specific option for full word search could be significant coding with a custom own syntax, and not a lot of added value considering redundancy with regex, so putting that aside as possible future imporvement until I get other things behind me.

Thanks, aaFn.
