### ISSUE TITLE
Search from Context Menu Function

### ISSUE THREAD

**Issue by minshifu** [aaFn/Bookmark-search-plus-2#159]
Hi, could "Search From Context Menu" function be enabled? That is, to search selected text from context menu with this addon. This feature would make this addon more efficient. Thank you and best regards!

**Comment by aaFn** [comment]
Hello @minshifu , could you give a bit more details on your demand by illustrating a use case in details ?
I mean, describe the series of actions and clicks you expect, from select text (where ? in a web page ?) .. to the result you wish (in BSP2 sidebar I presume ?)

Right now, you can easily copy selected text (Ctrl-C or right-click + Copy) and paste it in BSP2 searchbox (Ctrl-V, or right click + paste), and you'll get the search result nearly as fast as having a special right click menu entry, so I am not sure what you exactly need or the benefit you expect.

Thank you, aaFn.

**Comment by aaFn** [comment]
This is more than 2 months old, closing for now.
Do not hesitate to come back to this with more precision when you want, and we'll reopen.

Thanks, aaFn.
