### ISSUE TITLE
Problem in preferences: Search results bookmarks behaviour 

### ISSUE THREAD

**Issue by patrcoil** [aaFn/Bookmark-search-plus-2#162]
Hi, 

first of all I would like to congratulate you for you very good extension BSP2! 

However, I have a problem concerning in Preferences the topic "Search results bookmarks behaviour". The second choice "Advanced click" has two possibilities "Show bookmark" or "Open bookmark in active tab" but these possibilities are not readable. Probably a combination of keys is required but which one? Please look the screenshot attached.

I use Firefox 81.0.2 on Mac OS 12.6

Thanks for your answer.

Pat

![Capture d’écran 2020-10-20 à 17 35 09](https://user-images.githubusercontent.com/73185044/96609563-f109b000-12fa-11eb-8384-2f2a74170a9e.jpg)

**Comment by aaFn** [comment]
Hello @patrcoil , this is not a choice between two possibilities, but an illustration of what Advanced click does depending on the area you click in, that is when you click on the blank part at left and right of the bookmark (which does a "Show"), and when you click on the bookmark itself (which is "Open"ing the bookmark).
Sorry for the confusion it may create, if you see a better to describe what Advanced mode does, less confusing, I'll welcome your suggestion.

Maybe an "and" instead of "or" in the middle would already clear a bit the confusion ?

**Comment by patrcoil** [comment]
> Hello @patrcoil , this is not a choice between two possibilities, but an illustration of what Advanced click does depending on the area you click in, that is when you click on the blank part at left and right of the bookmark (which does a "Show"), and when you click on the bookmark itself (which is "Open"ing the bookmark).

OK, now I understand what you mean and it works fine. I like it! Actually, both pictures confused me since they did not represent any bookmark. It was the reason why I thought it was unknown characters for FF. On the other hand, what is the blank shark fin ;) on the right picture?  

Here is what I propose: Advanced click: click on the blank part at left of the bookmark for "Show bookmark" or click on the bookmark itself for "Open bookmark in active tab". "or" is OK since it is an alternative.

You can replace your picture by a screenshot of real bookmark, where both parts are visible, but for me it is useless.

**Comment by aaFn** [comment]
Sorry for the delay, was busy preparing and fixing other pieces.
In fact, this is already a subject we triied to refine ling ago in #14, and I feel we never got an ideal clear and explicit but short and redable description (trying to keep to 1 line).

I am switching to that in 2.0.84:
![image](https://user-images.githubusercontent.com/36155054/102055863-c401e700-3deb-11eb-8efd-08cce40dc399.png)

Let me know if you have comments.

**Comment by aaFn** [comment]
Published in 2.0.84 today, so closing the issue. Thanks, aaFn.
