### ISSUE TITLE
Request: option for custom "unknown favicon" icon

### ISSUE THREAD

**Issue by RememberTheAir** [aaFn/Bookmark-search-plus-2#165]
Hello there,

First off, thanks for the great extension. It's a must.

I was wondering, would it be possible to add an additional request to load a custom icon for bookmarks that are missing a favicon (no favicon/unfetched favicon)? I'm thinking about something similar to the existing cutom folder icon setting. The current icon [looks weird](https://i.imgur.com/gO0AuVj.jpg) when using a custom dark background color

Thanks!

**Comment by aaFn** [comment]
Hello @RememberTheAir , indeed I see that its missing a transparency setting .. I'll see to correct that, sorry that I missed it.

Now, that will still look odd, but in a different way, on dark backgrounds. I can obesrve that on the FF native Bookmark sidebar, they seem to invert the colors. I will see if I can make such an effect possible on my default icons.

Now, your demand makes sense anyway. So I will add it in a later release (maybe not next one).

Thanks, aaFn.

**Comment by RememberTheAir** [comment]
> I see that its missing a transparency setting

Yes, that would be a solution too! Thank you

**Comment by aaFn** [comment]
Both done in 2.0.84 which is published today => closing the issue. Thanks, aaFn.
