### ISSUE TITLE
Small but very annoying problem: no initial focus on the search field

### ISSUE THREAD

**Issue by liar666** [aaFn/Bookmark-search-plus-2#166]
Hi,

Thanks for the extension, it is GREAT !!!

Unfortunately, there's a small hickup that really annoys me: when I run the plugin/open the sidebar (e.g. hitting Ctrl+Shift+B), the search field is not focused automatically, which is the case with the default "Bookmark Sidebar" (and, more generally, any tool that you run takes the focus).

This is annoying because when you're used to such (a very logical) behaviour, you run/open the sidebar and start typing directly your search. And in the current setting, all the keys I type are interpreted by FF (instead of going to the search field) and this leads to a lot of confusion (closing tabs, opening new windows/tab...) and sometimes loss of information (e.g. data filled in forms) :{ 

Would be great if you could find a solution to set the focus in the search field as soon as the sidebar is opened.

Thanks a lot !

**Comment by aaFn** [comment]
Hello @liar666 , yes this is also an annoyance to me, unfortunately nothing I could do about it so far = this a Firefox bug, see #132

(ref https://bugzilla.mozilla.org/show_bug.cgi?id=1502713 -> please vote for it 😀 )

**Comment by liar666** [comment]
Thanks a lot, I've added some info on mozilla's bug page !

**Comment by aaFn** [comment]
Yes, I saw, thank you. Let's hope that somethingcan come soon, I can't believe this is difficult !
