### ISSUE TITLE
Delete/clear or prune BSP2 history

### ISSUE THREAD

**Issue by Gitoffthelawn** [aaFn/Bookmark-search-plus-2#168]
Happy New Year! 🥳 

I might be missing it, but is there any way to delete/clear or prune BSP2 history?

If not, could this functionality be added?

Ideally, one option to delete/clear all of it, and other option to prune so it only contains the previous x days.

Thanks!

**Comment by aaFn** [comment]
Hello @Gitoffthelawn, happy new year to you too !
Yes, pruning is already in place = all history data older than 30 days is removed.
That happens each time BSP2 is restarted, which is at least on each FF restart.

**Comment by Gitoffthelawn** [comment]
Thank you!

Happy to hear pruning is in place.  Would it be fairly simply to add a "prune all now" button and an small input field to the Options UI so the user can change from 30 days to whatever they desire?

I'm guessing that handling the case when the user selects "0" days would be the only special case to handle.

The only other edge case I can think of is if someone sets it for 99999 days, or something like that, but the code already should be designed to handle a large quantity of history because there is no limit as to the amount of bookmark edits/changes a user can make per day (therefore, even with just 30 days of history, the limit approaches infinity).

**Comment by aaFn** [comment]
Yes, I can start by adding a "Clear history" button. It could be in the History window itself, or in the options panel.
Which way would be more logical from your standpoint ?

Then I'll see to make the duration configurable, that was indeed my intention from the origin, I just made a 30 days default to begin with.

**Comment by aaFn** [comment]
"Clear history" button and configurable pruning duration (defalut to 30 days) are now added to the BSP2 options page, with 2.0.87, published this morning.

Closing, thanks, aaFn.

**Comment by Gitoffthelawn** [comment]
Looks great!  Thank you!
