### ISSUE TITLE
add folder contents view pane like FF bookmarks in tab/full screen view

### ISSUE THREAD

**Issue by shoulders** [aaFn/Bookmark-search-plus-2#169]
The only thing missing in full screen view is now having a folder contents view on the right like the native FF bookmarks APP.

I would like this so I can use it to organise my 10,000+ URLs that need looking at.

Is it possible to add this?

![image](https://user-images.githubusercontent.com/319997/104041305-bfed9d00-51d0-11eb-8282-a6cff66ffd23.png)

**Comment by aaFn** [comment]
Duplicate with #170
