### ISSUE TITLE
Option for version number in side panel.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#17]
It might be handy, for you and us testers, to display the version number somewhere in the side panel, e.g. next to the text "Bookmark search plus 2". That could be an option/setting (off by default)???

**Comment by aaFn** [comment]
Ok. However I am concerned that the title is already long and not showing entirely, or may not fit in some of the menus. So I also am adding a feature that when hovering on the search magnifying glass, the version is displayed:

![withversion](https://user-images.githubusercontent.com/36155054/36659653-739fd132-1ad5-11e8-9711-85b6a46aa5e8.png)

(here you see the next version I am working on, hence the name "BSP2 evol", to not confuse things on the FF UI)

How does that sound ?

**Comment by aaFn** [comment]
In 2.0.7

**Comment by JohnLukeBentley** [comment]
Looks perfect from my end.
