### ISSUE TITLE
option to disable click operation on links in tab mode

### ISSUE THREAD

**Issue by shoulders** [aaFn/Bookmark-search-plus-2#171]
## what is this
when you are in tab mode and you click on a link, it will open that link in that window and is difficult to manage.

## What do i want
A setting with the following options
- disable the left click operation on the links in tab mode
- convert the left click into open in new window
- convert the left click into open in new tab

The right click options should be left in place so i can do things like cut and copy or open in new tab.

## why do i want this
I use the full screen (tab) mode to organise my links and I am forever left clicking on a link when i am just trying to move it to another folder.

If there is an option to change the default behaviour of the  clicklable link I can organise my links quicker and in a less stressful way 😄 .

This will be closer to the behaviour of the native bookmarks manager. In the FF bookmark manager when you click on a link it opens the link up in the last tab that was used. In the case of **Bookmark-search-plus-2** it is itself.

**Comment by aaFn** [comment]
As said in #170, I can look at that, yes. I'll keep you posted.
Thanks, aaFn.

**Comment by aaFn** [comment]
This is now in 2.0.87, published this morning, and I did not make it an option but a new constant behavior.
I also modified the wiki on mouse and clicks modifier table https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.87) accordingly.

Closing the issue as done, thanks, aaFn.
