### ISSUE TITLE
Bookmark-search-plus-2 feature request for larger font.

### ISSUE THREAD

**Issue by ChooChooAl** [aaFn/Bookmark-search-plus-2#175]
@aaFn Cute tool.   I would like to be able to push the font to 20pt.   High dpi monitor and poor eyesight.   I've got it at 16 and it's readable at least but it would be a lot easier @ 20.

**Comment by aaFn** [comment]
Hello @ChooChooAl , sure, easy enough, I had arbitrarily picked 16 as a max, having no idea of what kind of range would suit people.
I will then raise the max to 20 in next release, probably published on next week-end.
Cheers, aaFn.

**Comment by ChooChooAl** [comment]
Thanks much.

**Comment by aaFn** [comment]
@ChooChooAl, 2.0.89 is out this morning, you can now increase fonts to 20px.
Enoy, aaFn.
