### ISSUE TITLE
Options to exclude a search pattern and to search in URL?

### ISSUE THREAD

**Issue by tobwz** [aaFn/Bookmark-search-plus-2#177]
Is there a way to add (in search entry field) after a search pattern(s) another pattern for exclusion?

The often used syntax with prepended "-" minus sign 

searchpattern -excludepattern 

does not work.

Moreover I would like to see a way to not only search in the Bookmark description but in URL too.

"\*" could be used as an indicator for URL related search. So e.g. entering 

*foobar.com

should find all bookmarks which have an url like

https://www.foobar.com/aaa/bbb/intro.html

Is this possible?

Can these features be added in the next release?

**Comment by aaFn** [comment]
Hello @tobwz, click on the red magnifier glass button at front of the search box, and you will see that:

- By default this is searching on both Title and URL => what you want
- You can change to search on Title only or URL only
- You can use Regex as search method, which allows you to do the negative exclusion you want.
E.g., once you have selected the Regex search mode in that menu:
    - To search for bookmarks which contain "trick" but not followed by "treat", simply write trick(?!.*treat)
    - To search for bookmarks which contain "treat" but not preceded by "trick", simply write (?<!trick.*)treat
- And some other choices are also possible (e.g. show only folders, or only bookmarks, or search in subtree)
- All is combinable as you wish. E.g., you can search on URL only, using regex, in a subtree, and showing only folders.

See those about regular expressions:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet
http://www.regular-expressions.info/lookaround.html

Once you are finished with special modes of searching, simply click the Reset button at front of the magnifying glass.

**Comment by aaFn** [comment]
Closing as the question is answered.
Let me know if any problem, thanks aaFn.
