### ISSUE TITLE
Req: Option to limit search to _current_ folder; specifically not including any subfolders

### ISSUE THREAD

**Issue by rlaggren** [aaFn/Bookmark-search-plus-2#179]
Many times when moving quickly, I dump a pile of bookmarks into approximately the right tree. Then need to go back and select and distribute the bookmarks to their final location. Or I forget and just save a bunch at the highest level and ditto above.

This means that I want to Search the pile in the current folder to find particular topics and _not_ return any results from subfolders - I will then distribute Search results down into the correct subfolder. But won't work when Search hits everything in _and_ below the current subfolder.

This type of problem is what led me to BMS+2 - I needed to search the current folder only, in particular not above the current folder. So I'm halfway there. <g>

Perhaps the gui would include a small button at the right of the Search box which would limit the search to line items in the current folder and not search up or down into lower folders. Or perhaps the button could be settable: a) search only current folder; b) search current folder and all sub folders; c) search current folder and _up_ the tree (don't know what the demand might be...). Maybe add sub-flags to b) and c) above to _exclude_ current folder from the search. I can see that being potentially useful when collecting relevant bookmarks into the current folder.

And it sure would be nice to have multi-moves. But I guess there are problems there. Just adding my vote.

Thanks for your work. Darn good implementation. Excellent documentation.

Regards,
Rufus

**Comment by aaFn** [comment]
Hello @rlaggren, interesting idea, and easily doable, to be activated then in the menu you open when clicking on the magnifier glass button (the red looking glass).

So then scope section of that menu would look like:
- Search all (default)
- From current folder
- In current folder only

and the last one would be what you want .. how does that sound ? (the second one is currently named "Inside current folder").

**Comment by rlaggren** [comment]
Great. 

A nit with your option phrasing. For exactness, maybe less chance of confusion:

"From Current Folder" is short, neat and accurate, but...

"Search all EXCEPT Current Folder"

Maybe would be harder to misinterpret.

And I think an option to search subfolders _only_ is helpful. This potentially would limit the search significantly. The PC won't care, but the person picking through the results might be really glad.

Rufus

**Comment by aaFn** [comment]
"From Current Folder" is to mean current folder included, and below it.
I am just changing "Inside" by "From" in the existing option name, to avoid ambiguity with "In" for the new one to introduce ... the search algorithm won't change.
Now, if too misleading, I can keep "Inside", to then have
- Search all (default)
- Inside current folder
- In current folder only

Let me know ..

Notes:
- "Search all EXCEPT Current Folder" doesn't exist.
- "Search subfolders only", not sure I see a good need for it = this is not a use case we classically see in e.g. file explorers, which is a good illustration of what is needed for search scope options.

**Comment by rlaggren** [comment]
Agree, following classic convention is usually right way.

My pov, using search results often benefits from limiting scope in order to not grab a big irrelevant pile to sort through. "All", "Current Folder Links Only", and "Current + Subs" is probably a proper plan. If I have the options correct...

Your option list, #2 and #3 look unclear and easily confused between them - to me, anyway. See, the "CurrentFolder" contains the subfolders and thus #3 can imply searching the subfolders. Ditto, really, #2, so it's hard to distinguish. Although maybe not as sleek, including words like "Except" or "Excluding" and "Including" would seem to make #2 and #3 harder to misinterpret.

Here's where we need an English major or a poet or something... <g>  Eg. the words "Links", "Marks", "Items" (and probably others), as well as the words "SubFolders", "Including" and "Excluding" (and more) might help to distinguish  and nail down just what is being searched within the current folder. But one thing I learned from writing text books for TurboTax is that somebody will always find a way of interpreting that nobody thought of before. C'est la vie.

It would be interesting to see feedback on which options are popular and used most often.

Cheers,
Rufus

**Comment by aaFn** [comment]
Correct, but at least we can try to reduce ambiguity ...
What about:
- Search all (default)
- Inside current folder subtree
- Folder direct children only

**Comment by rlaggren** [comment]
Wow. The text in the notification email is _not_ the same as the text in your post above!

IAC your above labels seem pretty clear. The real test is how many confused questions come back about the options. 

But "Let Not the Perfect Stand in the Way of GoodEnough!" 

Thanks for making this happen!


Cheers,
Rufus

**Comment by aaFn** [comment]
Function is in 2.0.90, which is out today.
Closing the issue, let me know if any problem, thanks aaFn.
