### ISSUE TITLE
Feature Request: Add an icon to the toolbar to show Bookmark search plus 2 in the sidebar

### ISSUE THREAD

**Issue by syldub69** [aaFn/Bookmark-search-plus-2#18]
I rarely use the sidebar. Actually I only use it for Bookmark search plus 2, because it allows me to use the "Go Parent Folder" feature which is the only feature that really interests me.
To show the sidebar, each time I have to go to View > Sidebar > Bookmark search plus 2, which is a pretty long access path when used many time a day.
Could you please implement an icon we could add in the toolbar in order to show the addon in the sidebar ?

**Comment by aaFn** [comment]
Hello @syldub69 , I am not familiar with how the toolbar works, but I guss I can have a look at it.

Meanwhile, did you try using the keyboard shortcuts ? (see #4)

    Linux = Ctrl+Shift+B
    MAC = Alt+B
    All others, including Windows = Ctrl+Q

**Comment by syldub69** [comment]
CTRL + Q works like a charm!
Also, I could click on the Firefox button which open the Sidebar (but it does not always open on Bookmark search plus).
But I think a toolbar icon is still the best :o)

**Comment by syldub69** [comment]
The following extension provides exactly the feature I'm suggesting:
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
It does have a toolbar icon which open the extension in the Sidebar.

**Comment by aaFn** [comment]
Hello @syldub69 , ok I will have a look at it. Thank you.

**Comment by aaFn** [comment]
Working on it for 2.0.18.

**Comment by aaFn** [comment]
I found it is not possible to make the button appear on option .. As soon as it is specified in the add-on, it is here and cannot be removed by code.
So it will be here for all, no option to show or to hide it .. :-(

For people finding the button annoying, they will have to manually remove it from the toolbar.
Sorry.

**Comment by aaFn** [comment]
Function provided with 2.0.18.
