### ISSUE TITLE
I would like to use BMSP2 as a replacement for bookmarks sidebar, but some important features a missing.

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#181]
Hi!

It seems like most things are there except these two:

- multi-select items, which is a big one. It's very common that I would like to organize stuff and I drag multiple items. Or multi-select and cut/paste, if I mean to use a very different location.
- type to select folders/bookmarks. It's not as big as the first, but still can be very useful when one has folders opened that have many items.

**Comment by aaFn** [comment]
Hi @mzso , yes multi-selection is under way, see #29, progressing slowly as I have other things going in parallel.

On the second one, not sure how to make it friendly .... if you try that on the native FF Bookmark sidebar, it is working only if you type characters very quickly .. else the input is reset and the next key you type after others is taken as the first letter again, but without any indication to the user this is happening
-> quite frustrating

Suggestions to make that better than current FF way ?

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2021. márc. 25. 17:10 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/181#issuecomment-807019641 "2021-03-25T16:10:53Z - Replied by Github Reply Comments"):
> Hi [@mzso](https://github.com/mzso) , yes multi-selection is under way, see [#29](https://github.com/aaFn/Bookmark-search-plus-2/issues/29), progressing slowly as I have other things going in parallel.

Great!


[**@aaFn**](https://github.com/aaFn) commented on [2021. márc. 25. 17:10 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/181#issuecomment-807019641 "2021-03-25T16:10:53Z - Replied by Github Reply Comments"):
> Hi [@mzso](https://github.com/mzso) , yes multi-selection is under way, see [#29](https://github.com/aaFn/Bookmark-search-plus-2/issues/29), progressing slowly as I have other things going in parallel.
> 
> On the second one, not sure how to make it friendly .... if you try that on the native FF Bookmark sidebar, it is working only if you type characters very quickly .. else the input is reset and the next key you type after others is taken as the first letter again, but without any indication to the user this is happening  
> \-> quite frustrating
> 
> Suggestions to make that better than current FF way ?
(It also switches between items starting with the letter in question when you tap only one key.)

I rather gotten used to this. So it's fine by me.
I have no ideas. I can live with how FF does it.

**Comment by mzso** [comment]
One other thing I can't quite get used to is how the show bookmark, search pane options work.
It's a tad misleading that the options have "after "show bookmark"", but the same happens why I simply select an item via mouse or arrow keys.
This also means I can't recreate the original BSP behavior. Where selecting search results worked as a sort of preview. And if I chose the "show bookmark" menu item it jumped to the particular bookmark and closed search.
I think it was a bit more versatile. With BSP2 I have to choose between the search pane always closing automatically, or never doing so. Or all folders remaining open or neither.

**Comment by aaFn** [comment]
Correct, as per https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.87), when there is the "Show" action (whether by click or by menu action), the search pane is closed if the corresponding option is set.

I see by the way there is a slight discrepancy in how the code does it, as it closes also in some cases where the action is an open in tab, new tab, window ... I will correct that in 2.0.90.

Select item only, whether by arrows or click (again see the table above), does not provoke a "show", and then does not close the pane. Agree this is a bit different from original BSP, where selecting was also always doing a Show, if I remember well.
I guess what you want is that:
- when the option is set, you can do a show without close, some times .. correct ? (what you called preview ...)
- and the trigger you propose for that "show-no close" (= "preview") would be on select ..
- .. but then how do you propose to handle when doing multiple selection as you want, where we successfully select multiple items either with mouse or with keyboard ? I guess on those selects we do not want to "preview" ... so need to be more precise in the desired effect, than just saying select I think

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2021. márc. 27. 00:14 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/181#issuecomment-808581984 "2021-03-26T23:14:17Z - Replied by Github Reply Comments"):

> Select item only, whether by arrows or click (again see the table above), does not provoke a "show", and then does not close the pane.

What do you mean? If I select a search results via mouse the search pane is closed in an instant.

> * when the option is set, you can do a show without close, some times .. correct ? (what you called preview ...)
> 
> * and the trigger you propose for that "show-no close" (= "preview") would be on select ..

I'm not sure I can follow all of this. I thought it was more intuitive, when it only jumped to the bookmark in question when I chose it in the context menu.
Otherwise it only showed the location without anything being opened up when I closed the search pane. And I would get me back to where I was before searching. So selection and the context menu "show" worked differently.
With BSP2, I don't have this choice. The configuration decides whether the search pane is always closed or never. Similarly the tree either always remains open or never.



>     * .. but then how do you propose to handle when doing multiple selection as you want, where we successfully select multiple items either with mouse or with keyboard ? I guess on those selects we do not want to "preview" ... so need to be more precise in the desired effect, than just saying select I think

Multi select is mainly useful in normal navigation. I guess it can be useful with multi select. I think in the rare cases when I used such I only did it via ctrl+x, than closed the search pane and navigated to where I panted to put items

**Comment by aaFn** [comment]
Hello @mzso , you are now losing me. To try to understand what you were saying, I jsut restarted an old FF with original BSP (version 2.02, the latest), and:
- there was no "Show bookmark" action in the context menu
- there was no close of the search panel when clicking a search result, or moving the search result selection cursor by keyboard

The "close of search result after show bookmark" is a BSP2 specific option I added on demand by another user, see #20

So if you want the original BSP behavior, simply do not set the option to close the search pane after show bookmark.

The only difference in BSP2 so far with original BSP behavior is that when moving the selection cursor by keyboard, in BSP2, I am not showing the bookmark in its tree (instead, you have to additionally click on it to get it shown, or to click on the "Show bookmark" action in the context menu).
=> is that what you would like to have ?

---------------------------------------------

As for a close of search result pane, this was happening only when you had installed the "Go parent folder" extension, in addition to BSP, when you were clicking on the "Go parent folder" action in the context menu.
But this was coming from the fact that it was another extension, not integrated with BSP, causing probably involuntarily that close behavior.

On BSP2, since the "Go parent folder" action is part of the extension, it doesn't close the search result pane.
At this stage, I am not convinced that adding another option "After go parent, close search pane", which was an accidental collateral, is really worth it.
However, I will let you give our arguments if you really want that.

**Comment by mzso** [comment]
@aaFn 
I might have conflated the two extensions, forgot that it's two. I always used them in parallel.

> But this was coming from the fact that it was another extension, not integrated with BSP, causing probably involuntarily that close behavior.
> 

Or maybe it was intentional. :)

> On BSP2, since the "Go parent folder" action is part of the extension, it doesn't close the search result pane.
> At this stage, I am not convinced that adding another option "After go parent, close search pane", which was an accidental collateral, is really worth it.

Well, it's you choice. I just thought it was nice that I could choose what would happen, depending what suited me best at a given occasion.

**Comment by mzso** [comment]
Just noticed one other missing thing. There's no way to view or, edit bookmark keywords. Not sure if addons have access.

**Comment by mzso** [comment]
I realized that another important feature is missing: Undo, redo.
Since with one accidental "delete" keypress I could erase a good chunk of my bookmarks it's a very necessary feature.
Also, speaking of delete, if I use it to delete something the focus is lost, very annoying. I have to click back on the tree to delete another item, after every single deletion, especially annoying with the lack of multi-select.

I see there's a history, but how do I make use of it? I can only see an option to keep history, and to erase it but nothing to use it in any way.

**Comment by aaFn** [comment]
2.0.90 is out with:
- more multi-selection internal code preparation. Still to come later, but let's track that in #29
- introduced internal code in preparation of undo/redo. To come later, but we will track that in #75
- adjusted the slight discrepancy mentioned above in https://github.com/aaFn/Bookmark-search-plus-2/issues/181#issuecomment-808581984

I will leave this issue open for the "Type to select folders/bookmarks." function using keystrokes, like in native FF bookamrk sidebar.

**Comment by aaFn** [comment]
On delete losing focus, indeed I see in the FF native bookmark sidebar that the cursor then moves to the next record.
I will look at doing that in 2.0.91.

History is a read only pane for now, to see what happened to your bookmarks, whether this is done by BSP2 or by FF native bookmark sidebar, or by any other add-on.

**Comment by aaFn** [comment]
Sorry, I have been a bit delayed and busy. This will be in 2.0.93.
Thanks, aaFn.

**Comment by aaFn** [comment]
For the "**Type to select folders/bookmarks**" function using keystrokes, I am using a much simpler algorithm than the native FF Bookmark sidebar, which quite convoluted, hard to reverse engineer, and not very intuitive (sometimes it jumps backwards, or it has a different behavior whether typed character correspond to first typed character i nthe sequence or not .. etc ...):

- when keystrokes are typed fast enough (faster than every 1/2 second), concatenate them as a search string used to find the next bookmark item starting with them.
- when a keystroke is more than 1/2 second after last, restart string used for search with that character only.

Thus:
- typing m m m m ... by spacing them with more than 1/2 second = browse through all next bookmark items starting with "m"
- typing m-m-m-m-... by spacing them with less than 1/2 second = search for next bookmark item starting with "mmmm.."

Replace above by any key sequence you want, e.g.:
- m m a will go to the first boolmark item starting with "a" after the first next two starting with "m"
- m m-a will go to the first boolmark item starting with "ma" after the first next starting with "m"
- m-m-a will go to the first boolmark item starting with "mma" after current

No wrapping = when reaching end, it does not restart at beginning
Only alphanumeric characters [A-Za-z0-9_], with case insensitive matching.

**Comment by aaFn** [comment]
The above two are now in 2.0.93 which is published.
Closing the issue, the rest (multiselection, undo/redo ..) is tracked through individual issues on their onw.

Thanks, aaFn.

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2021. júl. 23. 23:57 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/181#issuecomment-885933771 "2021-07-23T21:57:25Z - Replied by Github Reply Comments"):
> For the "**Type to select folders/bookmarks**" function using keystrokes, I am using a much simpler algorithm than the native FF Bookmark sidebar, which quite convoluted, hard to reverse engineer, and not very intuitive (sometimes it jumps backwards, or it has a different behavior whether typed character correspond to first typed character i nthe sequence or not .. etc ...):

> 
> No wrapping = when reaching end, it does not restart at beginning.  
> Only alphanumeric characters \[A-Za-z0-9\_\], with case insensitive matching.  
> Works both in seach result pane and in main bookmark tree pane.

Hi!
Sorry for responding so late.
I think the lack of wrapping is a significant drawback. When there are many files/folder I often don't know if the item in question is after or before my current position. But even if I do know, it's a lotmore convenient to just start typing with the knowledge that I'll get navigated to what I want, instead of checking whether I'm after it and navigate to the parent folder's item.

**Comment by aaFn** [comment]
Hello @mzso , I guess I can easily add wrapping, if we are ok that this is an endless wrapping (i.e. not a stop at some specific number of loops like 1, 2, ..., nor at a specific point like the "start point of the loop", quite difficult to safely identify) => the use decides by him/her-self when to stop.

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2021. aug. 8. 23:10 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/181#issuecomment-894855940 "2021-08-08T21:10:07Z - Replied by Github Reply Comments"):
> Hello [@mzso](https://github.com/mzso) , I guess I can easily add wrapping, if we are ok that this is an endless wrapping (i.e. not a stop at some specific number of loops like 1, 2, ..., nor at a specific point like the "start point of the loop", quite difficult to safely identify) => the user decides by him/her-self when to stop.

I'm fine by it. Honestly I'm not aware such restrictions being used FF or any other program, in cases like this. I just imagined it searches while I type until it finds a result or goes through all items.

**Comment by aaFn** [comment]
Ok, that will be in 2.0.97.
Best regards, aaFn.

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2021. aug. 9. 11:14 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/181#issuecomment-895068443 "2021-08-09T09:14:32Z - Replied by Github Reply Comments"):
> Ok, that will be in 2.0.97.  
> Best regards, aaFn.

Great. Thanks!
