### ISSUE TITLE
Default shortcut is already taken by FF + Can't change the shortcut 

### ISSUE THREAD

**Issue by liar666** [aaFn/Bookmark-search-plus-2#182]
Hi,

BSP2 2.0.89 & FF 86.0 here.

Problem 1 - BSP2 uses Ctrl+Shift+B to open side panel by default. Unfortunately in my FF version, this shortcut is managed by FF itself to show/hide the Bookmark Toolbar.

Problem 2 - When I change BSP2 shortcut in the addon config tab, I can use only Ctrl/Alt + Shift/Nothing/Ctrl + Letter. I've tried to set Ctrl+Nothing+B and Alt+Shift/Nothing+B but they are already managed by FF also, so not working :{

**Comment by aaFn** [comment]
Hello @liar666, default shortcut so far is Ctrl-Q in Windows, Ctrl+Shift+B in Linux, and Alt+B in IOS.
So I guess you are in Linux ?

Ctrl+Shift+B was free in Linux in the past when I created the add-on.
And when a shortcut is taken by FF, we can't override it, whatever we try, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#shortcut_values
The pain being that from platform to platform, of course FF does not use the same shortcuts everywhere 😠 

I see that now Ctrl+Shift+B is taken by FF on Linux as you say. This is for the bookmark toolbar as I see it.
So I guess I now need to change the BSP2 Linux default for something else 😢 .

The only way to find a free combination is unfortunately by trial and error ... it looks like Ctrl+Alt+B is free ... so I am going to change the default to that combination in 2.0.90. Let me know how this is on your side.

Thank you for letting me know, aaFn.

**Comment by aaFn** [comment]
Changed the BSP2 Linux shortcut to Ctrl+Alt+B, since this shortcut which was free at beginning of BSP2 is now taken by FF for the Bookmark toolbar 😞

2.0.90 is out with that modification.
Let me know if any problem, aaFn.

**Comment by liar666** [comment]
Hi,

Thanks for your work.
Yes, I'm on Linux. Now using FF 90.0.2 & BSP 2.0.94.

Unfortunately, Ctrl+Alt+B does not work for me either. Probably the "problem" is on my side, because Ctrl+Alt is already taken by my WM :{ (and I need that to stay like that...).

I don't see any means to change the key bindings anymore in the extensions parameters. Did you remove it?

While trying to find a solution, I've found extensions that are supposed to help redefine FF keys, like:
https://github.com/lusakasa/saka-key and https://github.com/mikecrittenden/shortkeys
but I cannot manage to do anything useful with the former and the latter has an interesting option to run some custom JavaScript on some already defined FF key, but I cannot manage to find the way to open BSP2 from JS code :# If anyone reading this can help, this would be greatly appreciated :)

PS: when I open the native "Bookmarks" side panel + open top list/combo-box to, I see an entry "Bookmark Search Plus Ctrl+Shift+B". You probably forgot to change the keyding in the list item name.

**Comment by aaFn** [comment]
Hello @liar666 , yes it is still theren in the extension options, as the last item in the **User Interface** section (cf. `Sidebar shortcut ...`)
