### ISSUE TITLE
Favicon and radio stream

### ISSUE THREAD

**Issue by Phil67ago** [aaFn/Bookmark-search-plus-2#184]
It seems that it is stuck a long time trying to get fav icons from bookmarks for mp3 streams.
Like this one: http://radio10.pro-fhi.net/flux-qlvuthph/192stream.

Just of curiosity, is it trying to get the favicon from the sqlite3 db .../profile/favicons.sqlite before trying fetching.

**Comment by aaFn** [comment]
Hello @Phil67ago , indeed, these URLs do not seem to point at any HTML, and then the code to get HTML content and find possible path of favicon inside page doesn't return.
I implemented a timeout (30s) on that step, and all should be fine then.
That will be in 2.0.90.

Thanks, aaFn.

**Comment by aaFn** [comment]
2.0.90 is out with the correction.
Let me know if any problem, aaFn.
