### ISSUE TITLE
BSP can not open a link to a file.

### ISSUE THREAD

**Issue by nabla666** [aaFn/Bookmark-search-plus-2#189]
I can not open a link to a file.
For example, BSP2 can not open the bookmark : "file:///C:/Users/myself/Documents/bookmarks%20win4710%2088b.html"
whereas the regular firefox bookmark can....

**Comment by aaFn** [comment]
Correct, see #149 (search works very well in GitHub ...) and read also the BSP2 add-on description, in the Limitations section https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/

Then go and ask Firefox for asking that add-on can do that.

Thanks, aaFn.

**Comment by nabla666** [comment]
Sorry for not searching before asking ;)

**Comment by aaFn** [comment]
No problem, just a bit annoyed that Firefox is introducing those limitations on us without really making people aware of them nor giving them choice, and then we are the ones to deal with those and to regularly explain 😞 

Thanks anyway for the interest in BSP2, I hope it brings you what you need in spite of that imposed-on-us limitation 😁
