### ISSUE TITLE
Implement dark theme & automatic switch to it according to Firefox's current theme

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#190]
I use Firefox built-in dark theme.
Built-in Firefox Bookmarks pane adapt to Light or Dark built-in theme.

Using BSP2 with Firefox Dark theme show the same panel as with the light theme : there is then a wide white rectangle in the UI and it's confusing with the web content area.

Is there any possibility to make BSP2 compatible with Dark theme please ?

**Comment by aaFn** [comment]
Hello @NicolasWeb, yes in BSP2 options, under "User Interface",
check the "Match active FF theme colors .." option.

That should do what you want.

Note also that you can manually change the text and background colors in the "Override .." option below, which is btw showing current text and background color codes at all times (even when disabled), for help.

**Comment by NicolasWeb** [comment]
Hello @aaFn , yep, it works ! Thanks
Shouldn't it be the default ? I personally forgot to go to Add-ons preferences after installation because it's not straight forward and not really easily discoverable.
I think that by default the user expect "all Firefox" (so Add-ons too) to follow the Theme. So I would better go for that option checked by default.

**Comment by aaFn** [comment]
Hello @NicolasWeb , I guess yes I could set it on by default, that would probably make more sense as you say.

However, note that this would only act for new installs of BSP2. It would not modify anything for existing installs.
Indeed, the default value is used only when there is no previous value saved. And when BSP2 is run at least once, all options are saved ... so on next run all options have a value.

Therefore, currently, all existing BSP2 installs have that option set to false, and changing the default won't change that.

Let me know your thoughts.

**Comment by aaFn** [comment]
Hello @NicolasWeb, ok, for now I am making it default to true on new BSP2 installs.
This will be in 2.0.93

Thank you, aaFn.

**Comment by aaFn** [comment]
2.0.93 is published, with the change.
Thanks, aaFn.
