### ISSUE TITLE
[Keyboard shortcuts] Make ctrl/cmd+click open in a new tab

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#191]
Hello,

Using the built-in Firefox Bookmarks pane, if you ctrl/cmd+click on a bookmark, it opens on a new tab. BSP2 seems to ignore the ctrl/cmd+ option.
This shortcut is a very common in Firefox UI : as an example, it works on any link into the content area. So it's something the user is waiting when using ctrl/cmd+click anywhere.

Would it be possible to implement it please ?
(If I do remember well, it was the case in some previous WebExtension version, while the default context menu were even bold, and shortcuts shown next to each context menu item)

**Comment by aaFn** [comment]
Hello @NicolasWeb , indeed this is the case, see https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.87)

I just tested again on Windows and Linux, and that works well.
Are you saying that on MacOS this is not working, because maybe Cmd is not seen as Ctrl by FF ?
(sorry, I do not have a Mac, I can only emulate in a VM but with a Windows/linux type of keyboard).

**Comment by aaFn** [comment]
Note: it seems that on MacOS, Control is different from Cmd ...

First one is detected by https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey
and second one is detected by https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

I am using the first one in the code.
If you are on MacOS, let me know if what you call Ctrl/Cmd+click is the first one or the second one .. (there is an area to test in each of the two links)

**Comment by NicolasWeb** [comment]
Yes on macOS, ctrl+click open always (system wide) the context menus (like a right click on windows and Linux).
Cmd is the equivalent to Ctrl in Windows & Linux. So on mac, that's Cmd+click that should open in a new tab. At the moment, it do no work : it open in the current tab, overriding the content.

Yes, Cmd is the metaKey :) : the test works for me.

**Comment by aaFn** [comment]
Ok, I guess Apple always have to do it their own way 😁 ...
I will adjust in 2.0.93, thank you.

**Comment by aaFn** [comment]
2.0.93 is now out, with the fix.
Thanks, aaFn.
