### ISSUE TITLE
Could "Quick Move Bookmark to Folder" funcion be realized?

### ISSUE THREAD

**Issue by minshifu** [aaFn/Bookmark-search-plus-2#193]
Thank you for your excellent addon which is very useful to me. Could "Quick Move Bookmark to Folder" function be realized? Moving bookmarks between different folders can be very troublesome especially when many folders are concerned. So could you pls enable a context menu list of folders to appear when a bookmark is right clicked？And then the bookmark can be moved to a folder chosen from that list.  Besides, it'd be preferable that the most recently used folders automatically move to the top of the context menu list. Of course, this is just my method. There may well be other better ways to achieve this function. Would you be interested in realizing this function. That'd save a lot of trouble and be a big boon to many people.

Thank you and best regards!

**Comment by aaFn** [comment]
Hello @minshifu , that is a possibility, although this is a significant piece of code to maintain such a tracking list and then show it in menus. I will think about it.

Meanwhile, do you know that there is also a nice and smooth way to do bookmark moves ?
- Click on the magnifying glass at left of the search bar
- Open BSP2 in a tab
- You now have 2 BSP2 running side by side = 1 in the sidebar, one in the tab as a web page
- And now you can drag from one to the other => show the bookmarks you want to move in one of them, and search for the target folders in the other, and drag from the first to the second with slick, safe and short moves 😀

**Comment by minshifu** [comment]
> 
> 
> Hello @minshifu , that is a possibility, although this is a significant piece of code to maintain such a tracking list and then show it in menus. I will think about it.
> 
> Meanwhile, do you know that there is also a nice and smooth way to do bookmark moves ?
> 
>     * Click on the magnifying glass at left of the search bar
> 
>     * Open BSP2 in a tab
> 
>     * You now have 2 BSP2 running side by side = 1 in the sidebar, one in the tab as a web page
> 
>     * And now you can drag from one to the other => show the bookmarks you want to move in one of them, and search for the target folders in the other, and drag from the first to the second with slick, safe and short moves grinning

Thank you so much! It works well. Pls also consider the feasibility of my method, if possible. Best regards!
![图片](https://user-images.githubusercontent.com/5119952/129500470-3bd10ef3-4419-46e8-8f82-b2a5d51f7621.png)

**Comment by aaFn** [comment]
Hello @minshifu, ok I will look at it more closely and see if I can put it in my todo list.
Thanks, aaFn.

**Comment by aaFn** [comment]
Closing for now as we have a workaround, and I confirm this is a significant piece of work to maintain such a list across all instances in all open windows, and across restarts.
We can reopen if/when the need becomes more proeminent, and the workaround is not sufficient.

Thank you, aaFn.
