### ISSUE TITLE
BSP2 swallows hotkeys since the type to find feature

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#194]
Hi!
So BSP2 introduced typing to navigate to bookmark tree items, which is fine.
However it also started swallowing various (most?) hotkeys to which it has no business with. Stuff like ctrl+j, ctrl+h.

It also swallows F-buttons. And has a funny response. If I press F1, it navigates to the item starting with "F1", if there's one as if I typed F and 1.
F1 is supposed to be the hotkey for Tree Style Tab for me.

**Comment by aaFn** [comment]
Hello @mzso , Ctrl, Alt, Shift ... keys have always been "swallowed". No hot key / shortcut is working from inside BSP2, as they can mean something to BSP2. Same for Fx keys. For example, at some point, F2 was an experimental function for in-place editing of bookmarks - which did not work well, so was removed.

We could decide as an improvement to not "swallow" them, and then pass to FF the ones which mean nothing to BSP2 ... something to think about indeed.

-------------------------------------

Now, you are correct that there is a bug on Fx keys themselves, and a few other special keys, with the new key navigation system = they are provided as strings to BSP2, and I was not checking that the length was exactly 1, nor the exact state of alt, meta and shift keys.
Correction made, will be in 2.0.97, now pressing F1 will not result anymore in finding the next bookmark item starting with "F1".

Thanks, aaFn.

**Comment by mzso** [comment]
@aaFn 
Well, some work, like CTRL+T, Ctrl+W. So I see no reason for other unused combinations wouldn't work.
Maybe I'm misremembering, but I thought I could use F1 to change back to Tree Style Tab after I finished with bookmarks.

**Comment by aaFn** [comment]
This is because Ctrl-T and Ctrl-W are not passed to the add-on at all, so BSP2 never sees them ... Don't ask me why, FF choice it seems ...

**Comment by aaFn** [comment]
2.0.97 is published with the fix.
Cliosing as resolved. Than kyou, aaFn.

**Comment by mzso** [comment]
I think it could have been left open, until you decide whether BSP2 should pass on hotkeys or not.

**Comment by aaFn** [comment]
Don't worry, this will be in 2.0.98.
I closed the issue because the bug was fixed, and rest is an improvement (but not losing sight of it 😁 )
