### ISSUE TITLE
Solution for background page deprecation in Firefox

### ISSUE THREAD

**Issue by Permik** [aaFn/Bookmark-search-plus-2#195]
I bumped into your [comment on the Firefox bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1578286#c8) and wanted to contact you and tell you about the [OffscreenCanvas API](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) that you could use to replace the canvas elements from the Background pages.

Sorry in advance if you've already solved the issue that's mentioned in the Firefox bug tracker comment.

**Comment by aaFn** [comment]
@Permik , thanks.
Only problem is that it is experimental, it requires the `gfx.offscreencanvas.enabled` preference (not sure I can set it by code in the add-on).
=> overall, not to use in Prod code, and not really supported then by FF.

If FF makes it a full supported function, then yes that would alleviate the problem it seems 👍

**Comment by aaFn** [comment]
Closing, until this is officially supported by FF, hopefully before Background pages gert deprecated in favor of Service workers one day ..
Thank you, aaFn.
