### ISSUE TITLE
After "Show bookmark", close search pane. 

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#20]
I'd suggest that after the "Show Bookmark" command has been executed the search pane be closed.

... perhaps as an option if you, @aaFn, don't think it ought be the only behaviour now that I mention it.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , indeed, the search pane is made to remain open while you work on the bookmark tree, and I even improved a feature recently to make it update dynamically when you add / modify / delete a bookmark which fits with the search criteria ..

However, I can add an option to close the search pane when you click on "Show bookamrk" indeed. Let me know if this is what you want, and I'll do it :-)

**Comment by getreadyforme** [comment]
yes, that option would be great!

**Comment by JohnLukeBentley** [comment]
@aaFn I haven't been responding lately partly because notifications were being incorrectly routed to my spam folder. That should be fixed.

> I can add an option to close the search pane when you click on "Show bookamrk" indeed. 

Yes please :)

**Comment by aaFn** [comment]
Ok, will look at it for 2.0.10 ..

`[ ] Immediately close search pane on 'Show bookmark' `

Default unchecked.

**Comment by JohnLukeBentley** [comment]
Sounds good. 

I'd also suggest that, with that option unchecked, that ESC to close the search window be active anywhere inside the search pane, not just inside the search bar.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , the question is: what is "inside the search pane" for a keyboard press ? This is not an obvious notion for keyboard events, because there is no focus at search pane level.

I guess a behavior could be, sidebar wide, when Esc is pressed:
- if a menu is open, close it
- if no menu is open, but the search pane is open, close the search pane
- Else do nothing.

How would that sound ?

**Comment by JohnLukeBentley** [comment]
>  because there is no focus at search pane level.

You mean the search pane can't capture mouse location while the whole sidebar can?

If so, your proposed scheme sounds like it would give me want I want. That also takes care of the menu (as it does now), which I hand't thought about.

**Comment by aaFn** [comment]
I guess I could check where is the mouse pointer when I receive the keyboard event and amend the second bullet in the logic above to say "when mouse pointer is in search pane". However, that will remain a sidebar wide event, and relating a keyboard event with the mouse position is not a natural thing I am afraid, which incurs the risk of not looking consistent to users.
So I'd prefer indeed to remain with a sidebar wide logic.

**Comment by JohnLukeBentley** [comment]
> and relating a keyboard event with the mouse position is not a natural 

We might be talking passed each other ... but the keyboard event is necessarily related to mouse position (or focus more generally). In general the cursor position determines which application, or component within the application, will receive any keyboard event (OS wide keypresses aside). So, for example, it is only when the mouse is over notepad (in windows) that Alt+F4 closes notepad, otherwise Alt+F4 will close another application (if the mouse cursor is over that other application).

So too you if you are looking to capture keyboard presses at the Sidebar level then this will necessarily be related to the cursor being over the sidebar (or the sidebar achieving focus through other means).

If I'm thinking this through correctly (I may well not be) you can keep the behavioral logical identical but implement it in two different ways:
* By capturing keypresses at the sidebar level; or
* By capturing keypresses at the sub-sidebar level, on a component basis ...

... that is, so long as sub-sidebar component are able to capture keypressses. Either way should look identical to users. It's then a question of which produces the better code.

**Comment by aaFn** [comment]
As a matter of fact, focus and mouse position are 2 different things.
Meka the following test:
- Ctrl B, to get the normal Bookmark feature
- click inside the search box = it gets the focus
- type keys, and while doing so, move the mouse somewhere else, like over the address bar or in another window ...

=> the keystrokes will continue to "arrive" to the search input box, wherever is your mouse, until you click on an identifiable component somewhere else which can receive the focus (a button, a menu, text area, a window, a frame .. etc ..).

Unless you have a special flavour of the OS UI which is dynamically moving the focus to follow the mouse, which is not the case of standard UI in windows or in Linux, keystrokes go wherever is the focus. Not where is the mouse.

Btw, I tried on Alt-F4, it goes to the active (focused) window, and does not follow the mouse .. until you click the mouse on the new object. At least in standard Windows UI.

Or let me know if I am missing something ?

**Comment by aaFn** [comment]
Btw, quickly searching, it does look that the notion of focus is keyboard related only, therefore calling it "keyboard focus".
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms646267(v=vs.85).aspx for example

I can see people talking of capturing keystrokes without the focus, and they all seem to rely on hooks at keyboard driver level to redirect/copy to their application (which is something not doable from within FF of course :-) )

**Comment by JohnLukeBentley** [comment]
>  focus and mouse position are 2 different things.

Right. We have three different things at play: focus, keyboard events, and mouse events. Those three different things do relate, and can be made to relate, to each other is all sorts of ways.

Download and fire up ... [JohnLukeBentley/events-demo.xhtml](https://gist.github.com/JohnLukeBentley/3cf2f005de1d6c59e966478a304fb8a3)

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , correct, we can see that once you've done the focus() in the code on the green zone on mouseover event, the focus is not lost .. that is, even when the mouse goes over blue or somewhere else or outside the FF window after that, key events still continue to go to the green zone (as long as we do not click somewhere else and steal the focus from the green zone).

We can also see from the doc that a keyboard event has no notion of the mouse position:
https://developer.mozilla.org/en-US/docs/Web/Events/keypress

Even though KeyboardEvent inherits from UIEvent, there are no coordinates on screen.

On keypress, use the following code line:
result = "Key " + event.key + " layer coord: ("+event.layerX+","+event.layerY+") page coord: ("+event.pageX+","+event.pageY+")";
The coordinates always appear to be (0,0) wherever is the mouse pointer.

Also, make the following experiment:
- Ctrl B to get the native sidebar
- type some chars for search
- right click on a search result to get a menu -> this steals the focus off the search box
- press ESC once: the menu is closed
- press ESC a second time: nothing happens

I checked this is the same in BSP1.

Ok, so all that said, what do we want to do ?
-> On my side, I am reluctant to give focus to something which is not active (the search pane is a div which is not an active object).
Are you ok with the proposed behavior above which anyway amounts to nearly the same thing, this is just that it will be a little wider in scope as even when something has the focus in the bookmark pane, it will act on the search pane:

On ESC:
- if a menu is open, close it
- if no menu is open, but the search pane is open, close the search pane
- else do nothing.

?

**Comment by JohnLukeBentley** [comment]
Try [events-close-search-pane-with-escape.xhtml](https://gist.github.com/JohnLukeBentley/cc96073a2a31bbdb85e60b2ca47b5ee0) ...

Throw in all the right-click menu openings and escapes yo want in addition to three test scenarios there.

I'm not seeing any particular problem with this modeled behaviour.

Just for fun I'm using a select element for the searchPane. I believe it could just as well be a div.

The native bookmark bar behaviour you mention is undesirable, I'd suggest.

**Comment by aaFn** [comment]
Yes, this is what is currently happening in the add-on except:
- ESC must go to a menu close in priority, so only next ESC will go to close search box
- when closing the search box, the contents of the search box is also emptied at same time, like in the native bookmark and in BSP1.
Or am I missing something ?

**Comment by aaFn** [comment]
@getreadyforme , @JohnLukeBentley , both are in 2.0.10 and effective =
- option for closing search pane after show,
- and close of search pane when pressing ESC and there is no context menu open to close.

Note that closing the search pane is in all cases emptying the search box, and setting keyboard focus to it.

**Comment by JohnLukeBentley** [comment]
> Yes, this is what is currently happening in the add-on except:
>> * ESC must go to a menu close in priority, so only next ESC will go to close search box

In my events-close-search-pane-with-escape.xhtml that is the same behaviour. Anytime you open a right-click menu an escape just closes that menu. This behaviour comes for free in my demo.

> when closing the search box, the contents of the search box is also emptied at same time, like in the native bookmark and in BSP1.

Yes that's a simple design choice to make. As long as we are clear that keypresses are captureable at particular points, you can insert (with some exceptions) whatever code you like on the keypress e.g. you can choose to clear the search box, or not, at the point of hiding the searchpane.

> Or am I missing something ?

In a new gist I've made some code adjustments and further explanations to my demo to make matters clearer (as they've become clearer to me): [events-close-search-pane-with-escape02.xhtml](https://gist.github.com/JohnLukeBentley/7c1f8f8731cee020224ab42bebc4789a). That is, see Tests 4 and 5.

At the moment BSP2 v2.0.9 behaves according to my tests as follows (ignoring issues around when the searchbox is cleared):
* Test 1: Passes.
* Test 2. Passes.
* Test 3: Fails.
* Test 4: Fails.
* Test 5: Fails.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley ,2.0.10 should pass tests 1, 2, 3 and 5.
Not sure about what test 4 is, your test text is the same as test 3 ??

**Comment by JohnLukeBentley** [comment]
> Not sure about what test 4 is, your test text is the same as test 3 ??

Very sorry, it was. But your 2.0.10 passes all 5 tests as they were intended.

Just for completeness I've updated [events-close-search-pane-with-escape02.xhtml](https://gist.github.com/JohnLukeBentley/7c1f8f8731cee020224ab42bebc4789a) to fix the text of Test 4.

So escaping to close the search pane works as desired. Great work!

Your option `After "Show bookmark", close search pane` works very well with one problem: the chosen bookmark shown in the tree is no longer highlighted/focused when the search pane is closed (but it is highlighted/focused with  `After "Show bookmark", close search pane`  off).

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , as a matter of fact, after closing the search pane, the focus is going to the search box, and results are discarded, so the bookmark row is no more highlighted.
For example, try the following:
- no search / no result, select a bookmark in the bookmark tree pane by clicking on the blank part at front of it = it gets highlighted
- click inside the searchbox = the bookmark is not highlighted anymore
- similarly, any result highlight is cleared when the searchbox is closed, since there are no result anymore.

So I guess this is a little confusing and I should change that:
- instead of having a notion of a result highlight row and a notion of focused row, I will simply have a notion of "highlighted row"
- a click on a result highlights corresponding bookmark, moving previous highlight if needed
- a click on a bookmark highlights that bookmark, moving previous highlight if needed
- there can only be one row maximum highlighted at any time
- a focused highlighted row has a different color than a non focused highlighted one, just to show it has the focus (as in the native bookmark sidebar)

Also, there is a bug: when closing the search pane after showing bookmark which is in a hidden part of the tree, if the "leave tree open" is not on, then we cannot see the bookmark.

Hence, the option "close after show bookmark" will now imply "leave tree open", as of 2.0.11 out tonight.

I am closing this enhancement as it behaves as it should, and things should be clearer now.
Let's open another issue if I made an error in the highlight handling.

Thank you much, aaFn.
