### ISSUE TITLE
Add option to 'Bookmark Tab Here' on right clicking a folder.

### ISSUE THREAD

**Issue by dougwl** [aaFn/Bookmark-search-plus-2#200]
This functionality can be added using another extension:

https://addons.mozilla.org/en-US/firefox/addon/bookmark-tab-here/
(It creates an option in the right click context menu)

And would be nice having something like this integrated in the add-on.
It basically simplifies bookmarking to a specific folder without needing any extra interaction or 'drag & drop', currently the user options for bookmarking are:

* Address bar action button -> Find the correct folder in a very annoying small screen.
* Main Menu -> Bookmarks -> Bookmark current tab -> Find the correct folder in a very annoying small screen. 
* Open add-on sidebar -> Drag & drop the tab to the specific folder.
* Open add-on sidebar -> Right click folder -> New Bookmark -> Type manually the title and address.
* Open library sidebar -> Select Bookmarks -> Drag & Drop to desired folder.
* Use the bookmark manager if you feel fancy.

With this suggestion:

* Open add-on sidebar -> Right click folder -> 'Bookmark Tab Here'

Any tags or specific configurations can be added or edited later.

Anyway, the add-on is awesome and basically my go-to for using bookmarks. Thanks for all your work.

**Comment by dougwl** [comment]
Perfect, not only would bring the new feature but keep it on pair with others already in place.
It's nice to see that my suggestion was useful :)

**Comment by peter-kehl** [comment]
For anyone attempting to use "Bookmark tab here" extension ([addons.mozilla.org/en-US/firefox/addon/bookmark-tab-here](https://addons.mozilla.org/en-US/firefox/addon/bookmark-tab-here/)): It doesn't & can't work anymore (whether with Bookmark Search Plus 2 or without). See teddy-gustiaux/default-bookmark-folder/issues/399 for an explanation.

**Comment by aaFn** [comment]
Thank you @peter-kehl . Hopefully, the BSP2 function added here helps on smoothing the problem.

**Comment by Gitoffthelawn** [comment]
> For anyone attempting to use the separate "Bookmark tab here" extension (addons.mozilla.org/en-US/firefox/addon/bookmark-tab-here- not the same as the popup menu "Bookmark Tab Here" from Bookmark Search Plus 2): That other extension doesn't & can't work anymore (whether with BSP2or without), unfortunately. See teddy-gustiaux/default-bookmark-folder/issues/399 for an explanation.

Hmmm... That doesn't appear to be correct.  I just tried installing the "Bookmark tab here" extension in a profile (that does not have BSP2) and it works very well.
