### ISSUE TITLE
Option to display folders first in search results

### ISSUE THREAD

**Issue by dougwl** [aaFn/Bookmark-search-plus-2#204]
When you have folders and bookmarks with similar names, finding folders can be, well, a little messy (my bookmark list is a monster), since they are all mixed as the same thing in search results.
Having an option to display folders before bookmarks would help a lot.

**Comment by aaFn** [comment]
Hi @dougwl , click on the magnifier glass at left of the search box = you can select to see only folders, or only bookmarks. That will do what you need to distinguish one from the other, and locate only what you want.
