### ISSUE TITLE
Local file:/// bookmarks not opening. 

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#206]
A bug in that local file:/// bookmarks are not opening. 

To reproduce:

* Surf to a local file. E.g. file:///C:/Users/John/Documents/WebOut/index.html
* Open BSP2 and drag the url from address bar into BSP2 tree. Observe that it looks OK in the tree.
* From the BSP2 tree click on the bookmark.
* Observe that nothing happens (we'd expect it to open the local html file).

See that the same url works when using from the native bookmark tree:

* Ctrl + B (To open the native bookmark tree).
* From the native bookmark tree click on your bookmark.
* Observe that the local html file is opened, as we'd expect.

Edit: BSP2 Version: 2.0.99 (Last updated 27 October 2021).

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , yep, not a bug, but a security feature of FF, preventing add-ons to do so ... see #189 and #149

If you open the browser console (Ctrl+Shift+J), you will see a security error msg generated by FF when you click on the bookmark in BSP2, saying FF prevented the add-on to access the URL.

Until FF provides a permission for that to add-ons, there is no way to circumvent this that I know of (except if you go to about:config and forcibly disable by yourself the protection).

Thanks, aaFn.

**Comment by JohnLukeBentley** [comment]
Thanks @aaFn, and apologies for not finding the duplicate. 

Yes I see in the Browser Console  (Ctrl+Shift+J), with settings > "Show Content Messages"
> Error: Illegal URL: file:///C:/Users/John/.../WebOut/index.html

So I see it is not a bug.

For workaround I'll have to stick with the native bookmark tree (Ctrl + B) to open file:/// urls. 

Do you know what the relevant about:config setting is?

**Comment by aaFn** [comment]
I believe this is `privacy.file_unique_origin` in about:config.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1500453

**Comment by JohnLukeBentley** [comment]
That didn't work.

The options seem to remain:

* Use the native bookmark tree (Ctrl + B) to open `file:///` urls; or
* Serve it (e.g. `http://localhost:8080/WebOut/` )

**Comment by aaFn** [comment]
Looks like an extra step is needed .. see https://blog.scottlowe.org/2020/04/04/making-file-urls-work-again-in-firefox/ (I didn't test)
