### ISSUE TITLE
See folder path in search view for context

### ISSUE THREAD

**Issue by Morikko** [aaFn/Bookmark-search-plus-2#207]
For some "generic words", the search results are not very explicit whereas it would be if the parent folder or the full path could be visible.

![2021-11-09_15-04 bookmark search](https://user-images.githubusercontent.com/7831572/140938253-f3bbcfa5-4b60-40ab-b7ee-7f6844168057.png)

I already know that on a search result you can right click and then look at `Bookmark path` but this is rather long to do for a list of results like in the picture.

Would it be possible to add an option to make it visible from the search view ?

Example:
- Tools _- Draw_
- Tools _- Kitchen_
- Tools _- Programming > Python_

Maybe on top of italic the path font color could also be less black to still keep the folder title emphasized.

**Comment by aaFn** [comment]
Hello @Morikko , there is an option which makes the path visible when you hover the mouse on the result.
See 
![image](https://user-images.githubusercontent.com/36155054/140942534-13807b54-5126-4918-bf6a-1ddc5b391f69.png)
