### ISSUE TITLE
Visual Customizations -> wiki documentation of main ids and attributes

### ISSUE THREAD

**Issue by dougwl** [aaFn/Bookmark-search-plus-2#208]
The project has some direct goals that it already achieves with success and it is basically a very feature rich tool. 
Having said that, what I've been thinking the most during my daily usage was about how to adapt the design to my preferences, similar to something a user would find in a extension like 'Sidebery', 'Tab Center Reborn', 'Tree Style Tabs' where CSS can be utilized to offer personalized experiences.

Is something like that in your radar? Are there any intentions to offer something similar?
 
Even if that is something out of question, what do you think about offering the ability to change other icons in the UI beside folders and bookmarks? (Folder arrows, filter and reset filter icons, 'other bookmarks' folder).

**Comment by aaFn** [comment]
Hello @dougwl , this can already be done by using userChrome.css with `!important` rules. 

A number of people are doing that already, see #112, https://github.com/Aris-t2/CustomCSSforFx, https://github.com/Aris-t2/CustomCSSforFx/issues/109#issuecomment-402849175

Note: for people able to write and manage such CSS code, using userChrome.css or a text field in the options panel doesn't make much difference.

**Comment by dougwl** [comment]
@aaFn, yeah, userChrome/userContent does the job, off course, and I'm actually using it for some other things, but an internal panel could possibly be quicker (in my perspective), especially because there is no need to restart the browser for testing changes and no need for opening an editor to edit the code; the best alternative in this case probably is by changing the styles directly in the Browser Toolbox.
But my whole point was about having a way to change the styles, and there is one, so I guess it will be my free time project xD

Maybe some sort of small documentation listing relevant ids and attributes could offer a nice kick-start. What do you think?

**Comment by aaFn** [comment]
Problem with an internal panel with user input and then injection in the main document / CSS stylesheet is that this requires to verify the code the user enters, to make sure it is correct, and to avoid any security risk / exposure.
The requires to add a CSS parser. I am not inclined to add that complexity, at least not now.

Ok for a growing documentation on the wiki, makes sense.

**Comment by dougwl** [comment]
Completely fair point, anything related to these seems challenging and  a pain to maintain in a solo project.

**Comment by aaFn** [comment]
I started the documentation here https://github.com/aaFn/Bookmark-search-plus-2/wiki/Documentation-of-main-ids-and-attributes

More to come, or anybody can contribute / correct things through opening issues.
