### ISSUE TITLE
Exclude trash folder from search results

### ISSUE THREAD

**Issue by Morikko** [aaFn/Bookmark-search-plus-2#209]
If the `undo` option is enable, then BSP2 is creating a trash folder in the bookmarks.

Folders & Bookmarks part of the trash folder are returned in the search results.

I realized one day after that I saved a new bookmark in a folder in the trash :sweat_smile: 

I did not see an option to exclude this trash folder, is it an option that might be added ?

**Comment by aaFn** [comment]
Hello @Morikko , yes if you disable the `Show BSP2 trash folder and its content` option, then the BSP2 trash folder becomes hidden, and its content is not part of search results.
See at bottom of the options page, in the `Traces / debug` section

**Comment by aaFn** [comment]
Note: of course, there is no way to hide it from the Native FF Bookmark sidebar, as there are no such things as "hidden bookmarks" in FF

**Comment by Morikko** [comment]
Ok my bad, I don't remember to switch this on. But now it is off, I don't see the folder in the tree view and in the search results. Great :+1:
