### ISSUE TITLE
Bookmark History in a Tab + honour FF theme + remember size & position

### ISSUE THREAD

**Issue by peter-kehl** [aaFn/Bookmark-search-plus-2#210]
In addition to having "Bookmark History" menu item, could we,  please:
- have a menu item "Bookmark History in a Tab" (it does work: moz-extension://your-installation-specific-ID-here/sidebar/history.html)
- make it honour the Firefox theme (the same way that "Open BSP2 in a Tab" already does).

**Comment by aaFn** [comment]
Hello @peter-kehl 

On the first bullet, the History window is not designed to run multiple times (this is what could happen if it can be open in a tab, especially when several FF windows are open).
Also, as it is in its own FF window, it is easy to enlarge the window as wished with no soze limit, as large than a tab (or even bigger), contrary to the sidebar which has limits imposed by FF .. Hence the "in a Tab" mode for the sidebar content.

On the second bullet, yes, planned in a future version.
Note:  I will also make its size & position remembered at same time.

**Comment by aaFn** [comment]
Hello, version 2.0.100 is out, with the bookmark panel in History window honouring FF active theme, and remembering size & position (if the corresponding option is enabled).

Let me know if problems, aaFn.

**Comment by peter-kehl** [comment]
Thank you @aaFn. Confirming that v. 2.0.100's History uses FF active theme for the left part (the list of changes). However, the details part of a selected history change is still black-on-light:
![image](https://user-images.githubusercontent.com/4270240/147630360-32f46b89-ef1f-44ea-9870-46b7040ab76d.png)

**Comment by aaFn** [comment]
Correct, the right and top parts are not following any theme at all for now, they are designed to be black on light grey for now.
This will evolve as I refine that piece with actions (all actions are greyed out for now)

Thanks, aaFn.

**Comment by Alpengreis** [comment]
Just for info:

It seems Firefox (Dev version) was crashed here after that update at some point. Then I restarted it and later I had 2 Firefox windows open - one with Firefox Browser window and the other just with BMSP window ... never had that before.

I thought you shouls now it.

**Comment by aaFn** [comment]
Hello @Alpengreis , interesting .. I guess FF decided by itself what to reload in those windows upon restart, and I suppose the History window was reloaded with the base BSP2 add-on internal URL.
That is fine, no harm, BSP2 sidebar code is made to run and coexist in multiple instances (not the case of the History window code, but here that is not what happened, so all is ok).

Thank you, aaFn.

**Comment by Alpengreis** [comment]
Thank you for explaining, @aaFn
