### ISSUE TITLE
Bookmark addition ability in BSP2 needed if not present after Folder/File search

### ISSUE THREAD

**Issue by Ecofoot** [aaFn/Bookmark-search-plus-2#211]
Bookmark addition ability in BSP2 needed if not present after Folder/File search

After searching for instances of a topic folder/File the add-on should allow one to add that page as a bookmark there. If this feature is already present better publicize use. 

FF currently requires me to scroll thru my LONG list of bookmarks to find best folder to put URL in.
Thanks.

**Comment by aaFn** [comment]
Hello @Ecofoot , sorry I do not exactly understand what you mean.

In BSP2, yo bookmark a page / tab at same place than another bookmark:
- simply search for the bookmark you want
- then click on the result in the search result pane to bring it into view in the main pane
- and then either drag and drop current tab close to it, or right click on the bookmark and click on "Bookmark Tab Here"

Or if you mean something else, can you clarify / illustrate by a scenario ?

Thanks, aaFn.
