### ISSUE TITLE
Need ability to see only folders with present search time if feature not present

### ISSUE THREAD

**Issue by Ecofoot** [aaFn/Bookmark-search-plus-2#212]
The ability to do a search and just see folders containing term would be nice.

A toggle allowing an expansion to then see files also would be good.  Seeing duplicate files within these folders would also be a good checkmark item.

**Comment by aaFn** [comment]
Click on the red magnifier glass button, and select "Show folders only" = that will select only the folders matching the search string.
Then click on the folder you want in the result pane = it will show it in the main pne .. and you can expand it there to see what is inside the folder.

Duplicate bookmarks = you need a bookmark manager for that. This is not the purpose of BSP2.
BSP2 primary purpose is to allow you to search and to show where are your results in 1 click, a thing that one cannot do with the native FF bookmark sidebar.
