### ISSUE TITLE
Bookmark-search-plus-2 fails on SM

### ISSUE THREAD

**Issue by Romko-M** [aaFn/Bookmark-search-plus-2#213]
Bookmark-search-plus-2 2.0.99 installs selfishly happy on SeaMonkey 2.53.9.1 but I cannot find either a context menu in left panel or any other means in Bookmarks > Manage Bookmarks menu.

**Comment by aaFn** [comment]
Hello @Romko-M , sorry, I do not know how SeaMonkey works, but I suppose it provides or emulates some of the APIs maybe in a different way than Firefox, or maybe some are not working at all ...?

BSP2 only supports Firefox for now, so I cannot tell if it works with other browsers or not.
I guess the conclusion is "no" for SeaMonkey .. sorry.
