### ISSUE TITLE
Stay at the location of the selected item in the bookmarks tree, after closing the search menu.

### ISSUE THREAD

**Issue by CrazieIvan** [aaFn/Bookmark-search-plus-2#218]
Hi, 

I hope it's ok to post another request soon after my first one. 
So, after searching and selecting a search result, the extension sends me to the item's location in the bookmarks tree.  That's great, but after closing the search menu, the bookmarks pane resets back to the previous view from before opening the search menu, and it loses the location of the searched item.  Would it be possible to add an option to keep the view on the location of the found item, after closing the search menu? 

Thank you!

**Comment by aaFn** [comment]
Hello @CrazieIvan , that option already exists, see` After "Show Bookmark", leave bookmark tree open by default when closing search pane` in the Search results behavior section.
That should do what you want.

**Comment by CrazieIvan** [comment]
Oh shoot, that's exactly what I wanted.  I looked at the settings and somehow I missed that option.  My mistake.  Thank you!
