### ISSUE TITLE
Respect browser config setting

### ISSUE THREAD

**Issue by Speravir** [aaFn/Bookmark-search-plus-2#22]
The browser config setting `browser.tabs.loadBookmarksInTabs` should be respected. So, when I’ve set it to `true`, also in _Bookmark search plus 2_ all bookmarks should also with left click be opened in own new tabs. (This is different from #3).

**Comment by aaFn** [comment]
Hello @Speravir , that is a good suggestion.
Unfortunately, the two options

- openBookmarksInNewTabs
- openSearchResultsInNewTabs

are not yet available to WebExtensions. This will be in Firefox 59, see the Browser compatiblity tables in
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/openBookmarksInNewTabs
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/openSearchResultsInNewTabs

When 59 is out, I will test for their presence and implement the behavior if the options are available.
Setting it to improvement for now, and we will wait for FF 59 to be out to make that happen ..

**Comment by Speravir** [comment]
Oh, I didn’t know about these restrictions. So, I’m happily looking forward.

**Comment by aaFn** [comment]
In 2.0.10
