### ISSUE TITLE
Date added/ URL info should be added to property window

### ISSUE THREAD

**Issue by Ecofoot** [aaFn/Bookmark-search-plus-2#220]
Date added/ URL info should be added to property window
It would be nice to know when each bookmark was initially added to Firefox and when last accessed.

**Comment by aaFn** [comment]
Hello @Ecofoot , see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNode

Are you talking of **dateAdded** ?
If it is there (cannot guarantee that all bookmarks have it), yes I could add an option to show it in Property window indeed, for advanced users.

As you can see in the doc link above from Mozilla, there is no last access time on bookmarks, and last modified only applies to folders.

**Comment by Ecofoot** [comment]
YES!

On 1/31/2022 12:19 PM, aaFn  wrote:
> *dateAdded* would be the term for when each bookmark was added.  It is 
> in the basic FF bookmarks menu.

Still would be nice to be able to select multiple bookmarks from search 
upper pane and copy/move them to another folder.

Thanks. You're doing a great job. Good app.

**Comment by aaFn** [comment]
This is in 2.0.102 which is out now.
Let me know if any problem, aaFn.
