### ISSUE TITLE
Side pane does not show complete PATH of bookmarks

### ISSUE THREAD

**Issue by Ecofoot** [aaFn/Bookmark-search-plus-2#221]
Side pane does not show complete PATH of bookmarks
If the PATH to folder is too long one cannot see everything

**Comment by aaFn** [comment]
See #71 , maximum width of the sidebar is not controlled by the add-on, but by Firefox.

As a workaround, you can use userChrome.css as suggested in the wiki https://github.com/aaFn/Bookmark-search-plus-2/wiki/Documentation-of-main-ids-and-attributes#override-minimum-and-maximum-size-of-firedox-sidebar-to-give-more-or-less-room-to-bsp2
