### ISSUE TITLE
Cannot move or cut/copy-paste bookmarks from the BSP2 bookmarks pane to the FF bookmarks toolbar.

### ISSUE THREAD

**Issue by CrazieIvan** [aaFn/Bookmark-search-plus-2#223]
I can only move bookmarks and folders FROM the FF bookmarks toolbar TO the BSP2 left pane, but not the other way around.  If I want to send an item from the bookmarks menu to the toolbar, I need to close BSP2 and change to the default FF menu.  

This is a problem because I wanted to use the BSP2 menu as a permanent substitute to the FF menu, but now I cannot do that.  I tend to move things between the toolbar and the main bookmarks menu all the time, so this feature is a must for me.  I wonder if anything can be done.

Thank you!

**Comment by CrazieIvan** [comment]
I need to make one correction to the issue.  I can actually drag-move a single bookmark from the BSP pane to the FF toolbar, which creates a duplicate of the bookmark (the bookmark is then in both places).  Copy/paste using the right-click menu doesn't work for a bookmark, and nothing works for folders (drag-move or copy/paste).

**Comment by aaFn** [comment]
Hello @CrazieIvan , correct, this is due to this -> https://bugzilla.mozilla.org/show_bug.cgi?id=1531539

No workaround and no solution so far.

**Comment by CrazieIvan** [comment]
Bummer.  Oh well.

**Comment by aaFn** [comment]
Closing for now, let's hope we have a solution provided by FF one day .. and then I will solve it.
Thanks, aaFn.
