### ISSUE TITLE
"Open All in Tabs" - Add recursive subfolders.

### ISSUE THREAD

**Issue by Illegal-Services** [aaFn/Bookmark-search-plus-2#225]
Hello, I want Firefox to fetch all my favicons, and because I have ~2000 bookmarks.
It would be really nice if in each folders of the application, it asks in the right click context menu if we want to:
"Open All in Tabs"
OR:
"Open All in Tabs Recursively"
That would save me A LOT of time if this feature is gone to be possible in the future.

Also, are there currently any ways to do this? If so, I couldn't found it! ...

Thank you!

**Comment by aaFn** [comment]
Hello @Illegal-Services , so you want to open 2000 tabs at once ?
A bit excessive, isn't it ? 😄

**Comment by Illegal-Services** [comment]
Hello @aaFn, well 2000 is too much, but if i select a specific folder, it can get easier.

I actually found a Firefox extension that does exactly that so I'll happy !

**Comment by Gitoffthelawn** [comment]
> I actually found a Firefox extension that does exactly that so I'm happy !

What is it called?

**Comment by Illegal-Services** [comment]
https://addons.mozilla.org/firefox/addon/open-bookmarks-recursively/

**Comment by aaFn** [comment]
Ok, I see, and good to know, thank you @Illegal-Services 👍 
No need I believe for BSP2 to redo that for now.

Closing the issue as having a workaround by using this specific add-on, until a more frequent need occurs and is worth adding in BSP2 instead of that workaround.
