### ISSUE TITLE
Allow wiki edits

### ISSUE THREAD

**Issue by Gitoffthelawn** [aaFn/Bookmark-search-plus-2#227]
After reading #208, I took a look at https://github.com/aaFn/Bookmark-search-plus-2/wiki/Documentation-of-main-ids-and-attributes

I found a few things to fix, so I tried to make edits.  I wasn't able to do so.  Either I don't have permission to do so, or I'm not seeing something obvious.

Would it be possible to allow wiki edits?  I can't speak for others, but I promise not to make a mess or post photos of you as a baby. :)

**Comment by aaFn** [comment]
Hello @Gitoffthelawn , problem is I didn't find an easy way to give access to the wiki .. or I have to make it public, and then anyone can modify. Maybe this is the solution ?

**Comment by Gitoffthelawn** [comment]
Hi @aaFn I'm not sure, but I do know that all wiki edits can be (or always are) recorded as deltas, so it's easy to revert an unwanted change.  I suppose someone could deface the wiki, but I would hope people have more interesting things to deface. ;)

**Comment by aaFn** [comment]
Ok, let's try, I just made it public, let me know, aaFn.

**Comment by Gitoffthelawn** [comment]
> Ok, let's try, I just made it public, let me know, aaFn.

Ok... I'll try it right now.  If you see your baby photos, then it worked. ;)

**Comment by Gitoffthelawn** [comment]
> Ok, let's try, I just made it public, let me know, aaFn.

WFM.  I just edited https://github.com/aaFn/Bookmark-search-plus-2/wiki/Documentation-of-main-ids-and-attributes

Look good to you?

(sorry, no baby photos)

**Comment by aaFn** [comment]
Yep, I saw that. Strange, I see that your edits added a space at the end of a number of lines, but I can't see them (cf. https://github.com/aaFn/Bookmark-search-plus-2/wiki/Documentation-of-main-ids-and-attributes/_compare/e67a0feeee4ae494b85527d64b0329e4b9eadfb8...028e45bd1b6bd5c6c75db1f52ae335bf31080dcc)

**Comment by Gitoffthelawn** [comment]
> Yep, I saw that. Strange, I see in the delta that your edits added a space at the end of a number of lines, cf. https://github.com/aaFn/Bookmark-search-plus-2/wiki/Documentation-of-main-ids-and-attributes/_compare/e67a0feeee4ae494b85527d64b0329e4b9eadfb8...028e45bd1b6bd5c6c75db1f52ae335bf31080dcc
> 
> but I can't see them when I look at the wiki itself

Yes.  I added spaces at the end of lines where you intended to create a newline.  This is because GitHub markdown requires spaces at the end of a line to generate a hard newline.

**Comment by Gitoffthelawn** [comment]
BTW, I occasionally wish I was one of those people who had enough free time to make funny GIFs or memes.  I have some hilarious ideas for your baby photos. :)
