### ISSUE TITLE
Feature request: Ability to sort by date URL added in addition to name within BSP2

### ISSUE THREAD

**Issue by Ecofoot** [aaFn/Bookmark-search-plus-2#228]
Need to be able to sort by date added as well as name.
Thanks.

**Comment by aaFn** [comment]
Hello @Ecofoot , dud you see that you can have a sorted by added date view in the Bookmarks Library ?

Given the frequency of such a use, it is worth to add a specific sort option in BSP2, while it does not exist on the main FF bookmark sidebar ?

**Comment by aaFn** [comment]
Hello @Ecofoot, well, I am not sure that this is a frequent use case. And I do not want to develop something each time particular requests are made, as this will rapidly clutter the menu which is already quite big.

So unless there is significant feedback from a fair number of other users that this is needed and useful, I am not inclined to add this one, sorry.
All the more that there are other add-ons just dedicated to bookmark sorting which can do that it seems, cf. https://addons.mozilla.org/en-US/firefox/addon/sort-bookmarks-webext and https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks for example (I didn't use them, so I do not know if they work well or not, this is just to illustrate).

Hope this is ok, with you, thank you, aaFn.

**Comment by Gitoffthelawn** [comment]
@Ecofoot Would you mind renaming this issue to make it easier to find in the future?

I think this would be a useful feature, but I also certainly understand the desire to keep UI and scope manageable.

If this wasn't possible natively via Firefox, I think it would be very important to implement.  But given that you can more or less do this via Firefox's Library UI (its searching functionality is quite weak though), the importance to add it to BSP2, to me at least, is reduced.

That said, it's obviously a bit a hassle to have to switch between BSP2 and the Firefox Library to perform different bookmark-related tasks.  And the limits of the search function of Firefox's Library UI have consistently been a weak spot in Firefox's development and UX over the years.

**Comment by aaFn** [comment]
Closing with workaround status, for now.
Thanks, aaFn.

**Comment by Gitoffthelawn** [comment]
> Closing with workaround status, for now. Thanks, aaFn.

Do you have some sort of tag that represents "not going to implement this right now, but maybe another day"?

**Comment by aaFn** [comment]
Hello, not really .. "Workaround" is ok, that is exactly what that means = until this becomes a bigger problem, that will stay as-is because there is a way to live with it. If that becomes bigger, then it will reopen ... 🙂

**Comment by Gitoffthelawn** [comment]
Sounds good... thank you!

**Comment by Ecofoot** [comment]
How do I recover accidentally deleted bookmarks/folders?  I notice that 
in the Firefox organizer there is a folder "*BSP2 trash folder for undo 
of bookmark deletes - DO NOT REMOVE !*"

Thanks.

**Comment by aaFn** [comment]
Unless you disabled the `Create and use BSP2 Trash folder to ..` options, all BSP2 actions to delete something are in fact moving things under that folder.
And unless you pressed the `Clear History & Trash-folder now` button in BSP2 options, your "BSP2 deleted" stuff is still there for 30 days (or whatever duration you have set in the options).

Therefore, to recover accidental deletes, until I make undo/redo effective in BSP2, you simply can do:
- Enable "Show BSP2 trash folder and its content" in options
- This will show it in BSP2, in the "Other Bookmarks" folder
- Open it
- Look for what you want to "restore"
- Move it back to where you want / where it was (drag & drop, cut & paste ..)
    - Note: this "restore" will appear itself in the Bookmarks history as "Create from trash"
- And all will be ok. You can now disable  "Show BSP2 trash folder and its content" in options to protect it and avoid any other mistake on it or its precious content
    - If you believe 30 days is not eanough, you can increase the value ... (I didn't put any max to it)

In case you forgot what was deleted or where it was, simply open the Bookmark history window (right click on the magnifier glass), and look upwards from its end until you see the unwanted actions = that will tell you exactly what was deleted, when, and where it was before.

Hope this helps.
