### ISSUE TITLE
Bookmark-search-plus-2 options tab display problem

### ISSUE THREAD

**Issue by nollinvoyd** [aaFn/Bookmark-search-plus-2#233]
Firefox 99, bsp2 v2-2.0.105

The best I can describe this is when you try to scroll down the Bookmark-search-plus-2 options tab, the page starts shaking, blinking.  Very difficult to read, etc.

**Comment by aaFn** [comment]
Hello @nollinvoyd , not such problem here, whether Windows, Linux for MacOs.
That must be something on your install / your profile or your customizations, at first sight.

What happens with other add-on option pages ?

**Comment by nollinvoyd** [comment]
Hi @aaFn

I found the problem.  

I use [CustomCSSforFx](https://github.com/Aris-t2/CustomCSSforFx).  One of the files in the package is userContent.css.  

Enabling either one of the following file options causes the conflict with bsp2. 

`/* addons page appearance - [only use one at a time] (incl. version number & buttons) ***********/
@import "./css/aboutaddons/addons_manager_alternative_appearance.css"; /**/
/* @import "./css/aboutaddons/addons_manager_alternative_appearance_aero.css"; /**/	/* <-- AERO colors */

I will be reporting the issue to the developer.

thanks

**Comment by aaFn** [comment]
Hello @nollinvoyd , ok thank you for coming back and updating.
Closing the issue then.
