### ISSUE TITLE
Dated release notes

### ISSUE THREAD

**Issue by grahamperrin** [aaFn/Bookmark-search-plus-2#234]
<https://github.com/aaFn/Bookmark-search-plus-2/wiki#user-content-release-notes>

For each future release, can you mention the date? 

Thanks. 

(I shouldn't expect you to add dates for past releases. A chore!)

**Comment by aaFn** [comment]
Ok, will do .. thanks, aaFn.

**Comment by aaFn** [comment]
In next version, the release page https://github.com/aaFn/Bookmark-search-plus-2/wiki on the wiki and the [changeLog.txt](https://github.com/aaFn/Bookmark-search-plus-2/blob/master/changeLog.txt) file will both contain dates for all releases, including those in the past .. thanks to AMO history, I was able to easily get dates for each release and add them 😀
