### ISSUE TITLE
question - Dark theme (solved)

### ISSUE THREAD

**Issue by bambukouk** [aaFn/Bookmark-search-plus-2#235]
can I use it in dark mode, please? :+1: 
I use Firefox with Dark theme but Bookmark search plus 2 remain brilliantly white?

**Comment by bambukouk** [comment]
Thank you.
Am I correct in thinking that your custom theme is only affecting BSP2 or... is it affecting the whole Firefox (including BSP2) ?
`userContent.css` should be doable even for simpleton like myself (after all it is just text file?), 
but to be honest would prefer official BSP2 if it is coming in near future...

**Comment by aaFn** [comment]
Hello @bambukouk , just go into BSP2 optoins and enable the option `Match active FF Theme colors`.
That should do what you want 😁

**Comment by bambukouk** [comment]
> ...enable the option `Match active FF Theme colors`. That should do what you want

thanks, but it doesn't work for some reason?
but overriding and setting my own colours works fine :+1: 

![override_colour](https://user-images.githubusercontent.com/50301871/163353125-cce4ca5e-2b3e-4745-a1c9-5d5897e3e308.png)

**Comment by aaFn** [comment]
> thanks, but it doesn't work for some reason?

Strange .. are you using the standard FF dark theme, or another custom one ?

**Comment by aaFn** [comment]
All works fine here on Windows, Linux or MacOS, on FF 99.
There must be something else on your side which is preventing things from working, or distubing them .. which OS are you on, and which firefox version ?

**Comment by bambukouk** [comment]
```
elementary OS 6.1 Jólnir
Built on Ubuntu 20.04.3 LTS
Linux 5.11.0-44-generic
```
FF installed using command in terminal:
sudo apt install firefox

I will update to make sure I got the latest

**Comment by aaFn** [comment]
Ok, maybe try in a fresh profile, to make sure nothing else is interfering (maybe another add-on is creating a problem, or an option in your current profile ?)

**Comment by bambukouk** [comment]
Whatever it is... I would wish FF themes were working as well as your BSP2 :+1: 
I am fine with overriding FF scheme to suit my tastes 
I will try it on another machine which I have set up just for testing (also Linux) and report back
Thank you!!

**Comment by bambukouk** [comment]
Just as promised, 
I have tried it on the same machine but running Win10 instead Elementary OS and `match active FF theme` works perfectly fine, so it sounds like my problem is specific to Elementary OS...

**Comment by aaFn** [comment]
Strange ... that works well on my side on both RHEL and Void Linux ... what is special to Elementary OS ??
I believe you should try with a new profile in your Linux boot ... to eliminate anyt problem due to config and other add-ons / extensions ..

**Comment by bambukouk** [comment]
An interesting thing I have just discovered is that the search seem to be searching web addresses (`Location/URL`), rather than my carefully organised `Name/title` which makes for somewhat confusing results....
I know I am going OT , but would appreciate advice on this as well (thank you!)
unless... it is another preference setting I have missed?

**Comment by aaFn** [comment]
Got a mail with you question on search being on URL + Title, but I do not see it here, so I presume you found the answer 😀  ?
Just a few precision:
- Default is search on URL + title, like the native FF bookmark sidebar
- You can change the algorithm and scope of data + matching methods + displayed results by using the menu on the magnifying glass = title only, URL only, sub-folder, use regex, show folders only in result .. etc .. 

Hope this suits your needs !

**Comment by bambukouk** [comment]
Yes, sorry - you are faster than I thought...
I have found the answer soon after posting my question, so felt it was better to delete the question 😁
Thank you again for a great tool 👍
