### ISSUE TITLE
[question] storage location(s)

### ISSUE THREAD

**Issue by elandorr** [aaFn/Bookmark-search-plus-2#238]
Where do you store favicons, settings?
It would be helpful to export/import and mass-deploy settings. I cannot find any Mozilla support for deployment of extension settings at all, though. I'm not a plugin programmer and there seem to be dozens of ways to implement storage in just the last 5 years.

I kinda answered my own original question that led to this query, but I will leave it here for your consideration:

On one system I completely wiped Firefox (all registry, all hidden folders). Later after importing the bookmarks backup (on the same system, but fresh FF setup), magically BSP2 had all the favicons.

But the JSON does not include them. FF's bookmark manager doesn't show any either.

I skimmed the code but couldn't find what folder I might have missed. It seems to be only FF's internal DB, which was wiped.

Or do you automatically start fetching in background without any prompt?

Personally I'd strongly prefer asking the user first before making a trillion connections, generating a huge personal profile of you for even the dumbest observer to see.

Storing the favicon of a website you visit ad hoc is intuitive - you visit it, you make the connection at that point in time, it gets saved along. Not necessarily that importing bookmarks triggers this for all (if that's what happened).

It's probably more personal than your recent browsing history, if you use bookmarks a lot. If you happen to be on clearnet during that period the enemy (i.e. the various freshly baked tyrannical governments) instantly put you on a list. The EU is even boasting with a new profiling system that gives them access like straight out of a dystopian novel, and we know about the US since forever. Unwanted network traffic is a risk to life in the modern age. Imprisonment, starvation, death by mob incited by the gov. 21st century life. 

I assume this relates to #91 - my voice goes towards disabling it by default. If a user wants it he can simply click it. Defaults should always be zero network until asked. (Which Mozilla already violates a lot, FF sends more data home than Windows or Chromium with the ungoogled patch.)
Users in general are completely unaware of the thousands of unwanted connections they make every day, if not hour.

Thanks for reading.

**Comment by aaFn** [comment]
Hello @elandorr , yes add-on data is in FF local storage.
The place is not decided by the add-on.
To find where it is, type `about:profiles` in the URL bar, then click `Open directory` on the Root directory line, and then open the `extensions` folder you will find there => you will see all local storage that is hold by FF for extensions.

Yes, on new install, BSP2 **slowly** fetches favicons, unless this is disabled (like maximum 10 per second). And it waits 1 minute after each time it is started before beginning to fetch, so there is time to disable the option in the options page.
Yes, an improvement to ask before starting should be possible, I just need time to implement that .. Are you ok to rename this issue to ask for that feature ?

Thanks, aaFn.

**Comment by awalkonthebeach** [comment]
@aaFn 
A followup question about the favicon storage location.  Are you sure it's somewhere in the `extensions` folder in the profile?  Because I accidentally deleted a portion of the contents of my `storage` folder and I lost my BSP2 favicons.

**Comment by aaFn** [comment]
Hello @awalkonthebeach , I just looked again and yes you are correct, it looks like there is add-on storage in the `storage` folder indeed, under the `default` sub-directory of it.
So that is probably the place .. as said, decided by FF, add-ons have no influence on that anyway 😁

**Comment by awalkonthebeach** [comment]
Thanks, good to know.  I was tinkering with the storage/default folder because it grows very large over time (1GB+) which makes backing up my FF profile quite slow.  I'm still trying to figure out exactly what type of content is stored in that folder.  It seems to be a mix of extension settings and also saved website data, which seems really stupid how they've designed it because I only want to backup firefox settings, but not individual website data.  But that's not related to this forum.  :-)

**Comment by awalkonthebeach** [comment]
That would make sense, thanks.
