### ISSUE TITLE
Can't create bookmarks by drag&drop from history (library view). 

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#240]
When I try to drag some items I get the erroneous desynchronization message, every time.
![kép](https://user-images.githubusercontent.com/4479090/167252772-cdcd7109-4a64-43cb-b370-1d6e21e8bce3.png)
When the message is cleared, and the panel is realoaded, I see that the bookmarks are not created.
There's no reason for the message it since I didn't even open the bookmark section, much less change anything.

I tried and the same thing happens with the history menu, which has no connection to bookmarks at all.

**Comment by aaFn** [comment]
Hello @mzso , taht works well on my side. Which itels are you trying to drag exactly from the bookmark history (library view) ?
Can you show a screenshot of what you are trying to drag and from where ?

Note by the way, that dragging from bookmark history to BSP2 does not create any bookmark, but moves the one you are dragging to the new place where you place it in BSP2.

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2022. máj. 7. 15:06 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/240#issuecomment-1120206652 "2022-05-07T13:06:29Z - Replied by Github Reply Comments"):
> Hello [@mzso](https://github.com/mzso) , taht works well on my side. Which itels are you trying to drag exactly from the bookmark history (library view) ?  
> Can you show a screenshot of what you are trying to drag and from where ?
> 
> Note by the way, that dragging from bookmark history to BSP2 does not create any bookmark, but moves the one you are dragging to the new place where you place it in BSP2.

It's not "bookmark history", they're history items in the history section of the library or from the "history" menu from the main menubar. Any history item to any bookmark folder seems to fail the same.


> 
> Note by the way, that dragging from bookmark history to BSP2 does not create any bookmark, but moves the one you are dragging to the new place where you place it in BSP2.

I don't think history can be "moved" to bookmarks it does not make sense. And in fact the history items stay where they are.

**Comment by aaFn** [comment]
Hello @mzso, ok I see, this is because drag & drops from FF History look similar to bookmarks drag & drops, but they have empty data and this makes BSP2 fail (don't ask me why there is no data, probably a bug in FF ..).

So I will forbid any such drag & drops in BSP2, as nothing can be made of them.

Btw, try to drag & drop from History to Notepad or any text editor, and you will see that it is forbidden also / not creating anything .. such drag & drops probably only work within FF itself.

That improvement will be in 2.0.107.
Meanwhile, do not try to drag any history item to BSP2 = it cannot do anything because there is no data in it, so this is useless.

Thanks, aaFn.

**Comment by mzso** [comment]
@aaFn 
I tried d&d into notepad++ and the urls appeared in it, both from history menu and from library. (FF 97.0b9 )

**Comment by mzso** [comment]
@aaFn I can even drop into Total Commander and .url files are created.

**Comment by aaFn** [comment]
Hi @mzso, I checked all that is passed by FF to the add-on = there are 4 types passed, but the data is empty for each.

So maybe that works at system level for some (however not with Notepad at least, neither with Thunderbird for example), but nothing is passed to add-ons through the Web Extension API -> I will simply and purely reject the drag & drop ("no way" sign).

**Comment by Gitoffthelawn** [comment]
This piqued my curiosity, so I tried dragging a Firefox history item to several different text editors on a Windows 7 box.

The URL appeared in all text editors except Microsoft's Notepad.  Go Microsoft!  ;)

**Comment by aaFn** [comment]
2.0.107 is out, and it  reject the drag & drop ("no way" sign) from FF history or from History section in FF Bookmark Library.
Thank you, aaFn.

**Comment by aaFn** [comment]
Ok, my bad, I see that I forgot that on first step of drags as passed by FF drag API, the objects are empty ... but on the drop event, all the data is there.
=> I am adding support for FF History drags to BSP2 in 2.0.108.

**Comment by aaFn** [comment]
This is published in 2.0.108 today.
Let me know if any problem, thanks aaFn.

**Comment by mzso** [comment]
Thanks, it works fine now.
