### ISSUE TITLE
Feature - Highlight "searched for" chars/word/string

### ISSUE THREAD

**Issue by Andre-ADPC** [aaFn/Bookmark-search-plus-2#243]
Hi, @aaFn. I was wondering if you have an option to **`highlight`** the "searched" `chars/string/text` in the results pane. I went through the config, but couldn't find an option to do so explicitly, so came here asking if it is possible.

On the same note; do you perhaps have deeper insight into whether FF will incorporate something like the collections feature Edge has? I went to the Bugzilla page to have a look. It seems more folks are looking for such a feature and I added my request to the queue. Mentioned your work and that they could learn from your BSP2 to INCLUDE searchability.

It is not a total dealbreaker, seeing that I'm using a suitable tab manager, called `Tab Session Manager`, which poses similar functionality, including searching in "Tab Collection" names, and the bookmarks inside the "tab collection", when viewed. 

It is from that extension I am drawing my request, as any term you search for pops out nicely to get to the thing you are looking for.

**Comment by aaFn** [comment]
Closing the issue, as this is not supported in BSP2 for now.
Thank you, aaFn.
