### ISSUE TITLE
filter for new bookmark

### ISSUE THREAD

**Issue by justsome12** [aaFn/Bookmark-search-plus-2#244]
Is there a way to add new bookmarks to a specific folder if they fulfill some rules (similar to thunderbird filters)

e.g. all newly added youtube links added to the folder youtube

**Comment by aaFn** [comment]
Hello @justsome12 , not in BSP2, because BSP2 is aimed at searching bookmarks.
There are other add-ons, aimed creating bookmarks, which are doing what you want I believe. This is an independent function, so you can combine such add-ons with BSP2 as you want.

**Comment by aaFn** [comment]
Closing the issue, as this is not the intent of BSP2 and there are other tools / add-oins for that.
Thanks, aaFn.
