### ISSUE TITLE
bookmarks are not loading

### ISSUE THREAD

**Issue by lw108** [aaFn/Bookmark-search-plus-2#245]
Hi - my bookmarks are not loading. When I open the extension, I see "Wait background load..." with a spinning wheel in the sidebar, but the bookmarks don't ever load. Do you have any suggestions for troubleshooting/fixing this? (I have restarted FF, removed and added the extension). Thanks!

**Comment by aaFn** [comment]
Hello @lw108, which Firefox version are you using, on which OS ?

To troubleshoot:
- Disable BSP2
- Open the browser console (Ctrl + Shift + J)
- Enable Content messages on the parameter wheel at top right
- Empty the browser console with the trash icon
- Enable BSP2
- Get all the messages in the console, and paste them here in this issue

**Comment by aaFn** [comment]
Closing as no news. Please reopen with debug data if problem is still alive.
Thanks, aaFn.

**Comment by lw108** [comment]
Hi aaFn,

I'm writing to--very belatedly!--thank you for responding to my inquiry and
apologize for not responding at that time. The extension started working
again and I couldn't correlate it to any particular action I took, and then
responding got lost among all my other "to do's" at a hectic time. If it
happens again, I will get back to you with the info you requested.

Thank you also for the extension! I don't even take full advantage of all
its functions and still find it to be very useful for finding and managing
my bookmarks. I think that when I was searching for solutions I read
somewhere that you had considered adding a "contribute" button to the
extension page. I would definitely be happy to pitch in if you do, and I'd
imagine there are other users who would too!

Best,
Laurie
