### ISSUE TITLE
Cannot drag bookmarks from FF bookmarks toolbar to the extension's left panel

### ISSUE THREAD

**Issue by rogergithubbing** [aaFn/Bookmark-search-plus-2#246]
Hello,

I would say that, just a few days ago I was able to do that, but now, when I try to do it I get a "non allowed" cursor icon.

Thanks !

**Comment by aaFn** [comment]
Ok, probably linked to the protection I implemented because of #240, which then is too strong. I will have a look this week-end.

**Comment by aaFn** [comment]
Ok, I found the regression, was indeed due to what I did for #240, which was too excessive and in fact not needed, because in the process I found that in fact I could support FF History drags .. so thank you for the defect, will be corrected in 2.0.108 😁

**Comment by rogergithubbing** [comment]
I'm glad I've been helpful for you.

Regards,

Roger

Il sab 9 lug 2022, 12:48 aaFn ***@***.***> ha scritto:

**Comment by aaFn** [comment]
Correction published in 2.0.108 whic is out now.
Let me know if any problem, thanks aaFn.

**Comment by rogergithubbing** [comment]
Works perfect, thanks !!!
