### ISSUE TITLE
Drag & Drop bookmark from BSP2 pane to toolbar bookmark folder copies it instead of moving

### ISSUE THREAD

**Issue by pstein** [aaFn/Bookmark-search-plus-2#248]
Assume I open BSP2 pane on the left and drag & drop (with left mouse button) one of the found bookmarks into an existing other folder on Firefox Bookmark bar
The bookmark is COPIED instead of moved.

Left mouse button actions is normally copy not move.

Not in BMS2

I think this is a bug.

Can you fix this?

**Comment by aaFn** [comment]
Hello @pstein , no this is not a bug in BSP2, but a limitation of FF API.
For the bookmark or folder to be moved, we would need to set in drag & drop object an instance Id, but we cannot get it, it is not available to web extensions.

I opened a bugzilla on it, FF is working on it (I do not have the link here, I will paste it later when I come back home).
So for now that all depends on FF to give the function, or set the instance id transparently.

**Comment by aaFn** [comment]
Here is the link to Bugzilla -> https://bugzilla.mozilla.org/show_bug.cgi?id=1531539

Please vote for it 😁  !
