### ISSUE TITLE
Feature Requests:  Bold Fonts option; Settings Backup

### ISSUE THREAD

**Issue by nollinvoyd** [aaFn/Bookmark-search-plus-2#249]
Bold Fonts, please.  Easier on the eyes.

I know that we're all aware of this, but the most tedious chore of creating a fresh profile is reconfiguring all the addons, especially when you have a ton of them and their individual settings have numerous choices.  Any time an app has a considerable amount of options to choose from, the luxury of being able to restore them form a backup file is much appreciated.

Thanks

**Comment by Gitoffthelawn** [comment]
@nollinvoyd I read your post a couple times, and I'm trying to understand if you're making 2 separate requests.  Do bold fonts have something to do with a backup option?  Also, I'm wondering, do you really mean **bold** fonts, or do you mean larger fonts?

Personally, sometimes I find **bold** fonts a bit hard to read, but I find larger fonts *always* easier to read.  That said, screen real estate is always at a premium, so there will always be a trade-off between font size and how much you can fit on the screen.  I have noticed, in general (not referring to BSP2 at all), that some software use fonts that only people under 20 can likely see clearly!  I have a hunch those developers don't know anyone (except perhaps their parents) over 20 (which is about when everyone's vision starts to decline).

**Comment by nollinvoyd** [comment]
@Gitoffthelawn

These are two separate issues.  

Obviously, I prefer a bolder font.  Concerning my font proposal, I'm simply suggesting that a settings option be given to the user to choose a bold version of the font., perhaps in conjunction with the current option to "override" the font size.  

Let the user decide what is most comfortable, and whether they're willing to sacrifice a little "real estate".  I don't think we're talking about a whole lot of difference here, space wise, This is not an unusual request., having been offered in numerous other addons and apps.

Same thing goes for an option to export the settings.  I'm sure that users would welcome the ability to do so.

**Comment by Gitoffthelawn** [comment]
@nollinvoyd That all sounds good to me.

**Comment by aaFn** [comment]
Hello gents, ok to add a bold font option. That will be in 2.0.110.

As for backup /restore of options, I do not have enough time to add that function = this would need first some refactoring of the way I manage options .. I will do this refactoring one day as options are increasing, and this is a bit painful to add a new option each time, but not for now, and I need to think through it thoroughly before I start to do something right.

So I will decline the demand for settings backup for now, please bear with me.

Thank you, aaFn.

**Comment by aaFn** [comment]
2.0.110 is out with the new option, let me know if any problem.
Thanks, aaFn.

**Comment by nollinvoyd** [comment]
XLNT.  Makes a considerable difference, IMHO.  

Whenever you get the time to do the export/import thing, much appreciated

thanks
