### ISSUE TITLE
Show in tree. Move selected bookmark in tree to show more context.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#25]
@aaFn great work on #22. 

The escape button seems to be working as it should. Interestingly with the escape button now working in more contexts I find myself preferring to turn off `After "Show Bookmark", close search pane ...`.

The highlighting/focusing of the Shown bookmark now works well ... excepting I'd suggest that you move/focus on the shown bookmark that reveals more context:

At the moment the shown bookmark is moved to immediately underneath the bottom of the Search Pane. I generally want to see a few more bookmarks and folders before the shown bookmark.

If that seems to you like a good thing to do it's a bit unclear what should be shown before the chosen bookmark. The options include:
* Show the bookmark in the middle of the visible tree;
* Show X nodes (e.g. 5) before shown bookmark.
* Show the parent of the shown bookmark.
* Show the grandparent of the shown bookmark.

Perhaps there's a clever design algorithm to come up with: e.g. Show the grandparent of the shown bookmark unless this is more than X (e.g. where X is 10) nodes before the shown bookmark, then show X bookmarks.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , agree, I have the same feeling than you that this is too much at top and depriving me of some perspective before the bookmark ...

I am relying on scrollIntoView({behavior: "smooth"}) (https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to show the row, and it is doing that .. which I do not find nice.

I don't believe I can easily do "middle".
X nodes or parent should be easy .. but parent can be far, and more than the sidebar height.
I guess I would tend to do X (5 seems a good value).

**Comment by JohnLukeBentley** [comment]
I'm glad you broadly agree with the need for some more context.

> but parent can be far, and more than the sidebar height.

Which is why I suggested the algorithm
>  e.g. Show the grandparent [or perhaps parent] of the shown bookmark unless this is more than X (e.g. where X is 10) nodes before the shown bookmark, then show X bookmarks.

So, to flesh that algorithm out:
* Get Grandparent (or parent, if that were better) node.
* Get count of nodes from target node to grandparent (or parent) node.
* If that count > maxTopNodesToShow (e.g. 5) then
  * scrollIntoView target node minus maxTopNodesToShow (E.g. 5 nodes above target); else
  * scrollIntoView Grandparent (or parent).

But perhaps, to ease implementation, you could start with the simpler "5 nodes above target (if there are such nodes)" and "we" could improve the algorithm in the next release cycle.

**Comment by aaFn** [comment]
Looks good, I like that. I will go for Parent and maxTopNodesToShow (value to tune) for now.
Will try this week end for 2.0.13.

Thanks, aaFn.

**Comment by aaFn** [comment]
Update: by playing with the scrollIntoView values I found a behavior which is showing things at center of the bookmark pane:

`srcRow.scrollIntoView({behavior: "smooth", block: "center", inline: "nearest"});`

I am using that in 2.0.13.
Let me know if not good ..

**Comment by aaFn** [comment]
Out in 2.0.13, but not working before FF 58.0.
So in 2.0.14, I reverted the function to old behavior for FF below 58.0, and kept the new behavior for FF 58.0 and above.
