### ISSUE TITLE
Is it possible to add an search engine from the input field?

### ISSUE THREAD

**Issue by minshifu** [aaFn/Bookmark-search-plus-2#250]
Some addons allow users to add search engines from input fields ( i.e. https://addons.mozilla.org/zh-CN/firefox/addon/custom-search-engines/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search ). Is it possible to add an search engine from the input field of Bookmark-search-plus-2?  Thanks a lot!

![图片](https://user-images.githubusercontent.com/5119952/184639528-7c8b7ffa-d129-45d0-9092-f316d66ebce2.png)

![图片](https://user-images.githubusercontent.com/5119952/184639153-714cb8cd-a670-490c-a206-2a999b5d4723.png)

**Comment by aaFn** [comment]
Hello @minshifu , not sure that would make sense = BSP2 is searching on local bookmarks, which are not visible to search engines.
It is not to search for web sites or content on the internet.
What would be the benefit of an external search engine here ?

**Comment by minshifu** [comment]
> Hello @minshifu , not sure that would make sense = BSP2 is searching on local bookmarks, which are not visible to search engines. It is not to search for web sites or content on the internet. What would be the benefit of an external search engine here ?

Hi, coz my work requires frequent searchings of bookmarks. And I am using a popup search addon. Currently I have to copy and paste target text into the input field every time. But if I could add an search engine from the input of your addon, I think I would have your addon at my fingertips. I would then be able to select certain text and search it right away with your addon from a popup menu.That would make searching much easier ,effortless and time-saving. Or if this won't work. Do you happen to know any means to send selected text directly to the input field instead of switching to the addon interface and copying and pasting the text each time? Thanks a lot!

**Comment by aaFn** [comment]
Ok, I see. No this is not possible, the search box of BSP2 is dedicated to BSP2, it cannot be used as input for an internet search engine.

And no, I am not sure how to send a text to an input box instead of copying and pasting. At least I do not know of any mean to do that, but if you find one, I will be interested to know 😁

**Comment by minshifu** [comment]
> Ok, I see. No this is not possible, the search box of BSP2 is dedicated to BSP2, it cannot be used as input for an internet search engine.
> 
> And no, I am not sure how to send a text to an input box instead of copying and pasting. At least I do not know of any mean to do that, but if you find one, I will be interested to know grin

Ok,got it. I wish I could find one. I searched key words like "send text to input field" and found some technical discussions on this topic. But I am a layman to this kind of stuff and were totally clueless about those codes or scripts they are talking about.

By the way, would it be possible to have a "Recently used folders list"? That is , a list of bookmark folders into which bookmarks have been recently added. That would make handling a lot of bookmarks and folders much easier.

**Comment by aaFn** [comment]
Hello @minshifu , sorry for the delay.
The main function of BSP2 being to search bookmarks, it does not try to improve the other bookmark functions / experience.

There are already good extensions which allow to manage adding bookmarks, maybe you want for example to give a try to https://addons.mozilla.org/en-US/firefox/addon/default-bookmark-folder/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search ?

**Comment by minshifu** [comment]
> Hello @minshifu , sorry for the delay. The main function of BSP2 being to search bookmarks, it does not try to improve the other bookmark functions / experience.
> 
> There are already good extensions which allow to manage adding bookmarks, maybe you want for example to give a try to https://addons.mozilla.org/en-US/firefox/addon/default-bookmark-folder/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search ?

It's ok. Thank you for your suggestion.
