### ISSUE TITLE
While B-s-p-2 is activated, searching new URLs become very slow

### ISSUE THREAD

**Issue by MilosBranko** [aaFn/Bookmark-search-plus-2#251]
I appreciate very much your extension, but unfortunately since some months I've got this issue with Firefox. The problem does'nt occur with any URL, but with many of them and only while the extension is activated. 
Please let me know if and how the tedious problem can be fixed (without disabling the extension, of course).

**Comment by aaFn** [comment]
Hello @MilosBranko , what do you mean by "searching new URLs" ? Can you describe exactly what is slower ?

**Comment by MilosBranko** [comment]
Thank you for your prompt reply.

By "searching new URLs" I mean simply writing an URL (the internet address of a site) in the search bar and pressing Enter…

As I wrote, for some sites (non for all) it takes ages to access to those sites (I have a 1 Gb connection).

If I disactivate the app, the search time becomes normally fast (more or less) for every site.

Thanks

 

 

Da: aaFn ***@***.***> 
Inviato: domenica 28 agosto 2022 10:05
A: aaFn/Bookmark-search-plus-2 ***@***.***>
Cc: MilosBranko ***@***.***>; Mention ***@***.***>
Oggetto: Re: [aaFn/Bookmark-search-plus-2] While B-s-p-2 is activated, searching new URLs become very slow (Issue #251)

 

Hello  <https://github.com/MilosBranko> @MilosBranko , what do you mean by "searching new URLs" " ? Can you describe exactly what is slower ?

**Comment by aaFn** [comment]
That is strange, because BSP2 does not interact in any way with the address bar nor the search bar of FF .. ont even looking at them.

Do you have other add-ons installed ? Could there be one indirectly provoking an interaction on bookmarks, and therefore with BSP2 ?

**Comment by MilosBranko** [comment]
I understand what you think..

Yes, I have other add-on installed and there could be an interaction between BSP2 and one or more of them.

I’ll do my best to analyze the problem and eventually I will return to you.

Please feel free to close the issue, in case I will open a new one with more details.

Bst regards

 

 

Da: aaFn ***@***.***> 
Inviato: lunedì 29 agosto 2022 13:48
A: aaFn/Bookmark-search-plus-2 ***@***.***>
Cc: MilosBranko ***@***.***>; Mention ***@***.***>
Oggetto: Re: [aaFn/Bookmark-search-plus-2] While B-s-p-2 is activated, searching new URLs become very slow (Issue #251)

 

That is strange, because BSP2 does not interact in any way with the address bar nor the search bar of FF .. ont even looking at them.

Do you have other add-ons installed ? Could there be one indirectly provoking an interaction on bookmarks, and therefore with BSP2 ?

**Comment by aaFn** [comment]
Of course NOT, I won't close the issue 😁 . Let's see what you can gather.
Could you give me your list of add-ons ?
If things are easy, the process would be to disable them one by one, BSP2 latest, and see when the slow down disappears (supposing that disable really stops things .. I had some doubts in past .. it might require a FF stop and restart in between to make sure)

**Comment by MilosBranko** [comment]
I went to make some test, but now I have major problems:

*	BSP2 took more than 1 minute “to load saved states”
*	When finally got them, the Search bar doesn’t work properly, it doesn’t find what I input

It looks like if something is corrupted, may be the index?

I’ve already disactivated / activated the app, with no result. What do you suggest?

Thanks

 

Da: aaFn ***@***.***> 
Inviato: lunedì 29 agosto 2022 16:41
A: aaFn/Bookmark-search-plus-2 ***@***.***>
Cc: MilosBranko ***@***.***>; Mention ***@***.***>
Oggetto: Re: [aaFn/Bookmark-search-plus-2] While B-s-p-2 is activated, searching new URLs become very slow (Issue #251)

I ‘ve already 

Of course NOT, I won't close the issue 😁 . Let's see what you can gather.
Could you give me your list of add-ons ?
If things are easy, the process would be to disable them one by one, BSP2 latest, and see when the slow down disappears (supposing that disable really stops things .. I had some doubts in past .. it might require a FF stop and restart in between to make sure)

**Comment by aaFn** [comment]
I would propose to start by going iinto BSP2 options, and try a "Reload all bookmarks from FF now" .. to see if things improve.
Also, how many bookmarks and folders do you have ? (stats displayed in the options panel).

Then if things do not improve, and storage is corrupted for the add-on, then the only option will be to empty the storage and restart. The quickest way for that is to uninstall BSP2, and reinstall it.

**Comment by aaFn** [comment]
Hello, closing the issue for now, as no news.
Please reopen if / when you have new elements or more details, thank you, aaFn..
