### ISSUE TITLE
Is there a shortcut for focusing on the input field? 

### ISSUE THREAD

**Issue by minshifu** [aaFn/Bookmark-search-plus-2#252]
Is there a shortcut for focusing on the input field in a Bookmark-search-plus-2 sidebar or tab?  Thanks a lot!
![图片](https://user-images.githubusercontent.com/5119952/188411689-1cc7b15d-b508-42f6-8527-c94c33c2d70e.png)

**Comment by aaFn** [comment]
Hello @minshifu , see https://github.com/aaFn/Bookmark-search-plus-2/issues/166, there is a FF limitation on this .. please vote on the bug to raise its importance ...

**Comment by minshifu** [comment]
> Hello @minshifu , see #166, there is a FF limitation on this .. please vote on the bug to raise its importance ...

OK, thanks.
