### ISSUE TITLE
Is there a way to keep the original page title when a url from google search results is dragged to add a bookmark?

### ISSUE THREAD

**Issue by minshifu** [aaFn/Bookmark-search-plus-2#253]
Sorry to bother you again. Everything is normal when I drag a url from the brower address bar to add a bookmark. But when I drag a url from google search results (without having to open each url to save time), the original page title can not be kept as shown by the video below. Is there a way to solve this problem? Thanks!

https://user-images.githubusercontent.com/5119952/189912108-f2dfd0dd-a761-4570-9777-b373199fb875.mp4

**Comment by aaFn** [comment]
Interesting, I do not get the same thing than you ... your google page result does not have the same layout than mine, and the URL is not the same either (my result gets things embedded in https://www.google.com/....blabla...).
Also your browser look & feel looks radically different from mine in the top bar, address bar and in tabs.

Are you using Firefox ? Or another browser ?
And do you have some other extension cleaning up URLs before they get dragged ?

**Comment by minshifu** [comment]
> Interesting, I do not get the same thing than you ... your google page result does not have the same layout than mine, and the URL is not the same either (my result gets things embedded in https://www.google.com/....blabla...). Also your browser look & feel looks radically different from mine in the top bar, address bar and in tabs.
> 
> Are you using Firefox ? Or another browser ? And do you have some other extension cleaning up URLs before they get dragged ?

It turns out that you are right. I think the new layout of google results page is confusing and misleading. So I use this addon to revert to its older version (https://addons.mozilla.org/zh-CN/firefox/addon/make-google-search-great-again/).  But I really do not want to use the new layout of google results. After I disable this addon, the original page title returns. However, a url also appears in the second line as shown by the footage below. It is very cumbersome. Is this the same case for your browser? 

By the way , I edited CSS to change the layout of my firefox. 



https://user-images.githubusercontent.com/5119952/190854977-d8352754-cbc0-4620-84ff-9c7c17a2d428.mp4

**Comment by aaFn** [comment]
Ok, thank you. I will give a try to the add-on you mention, and see if I can do something to accomodate it.
I will come back here and tell you the results of my investigations.

**Comment by aaFn** [comment]
Good news, I could find a way to accomodate the add-on effect on Google results page, and I also improved the drag & drop from unmodified latest Google results page.

This will be in 2.0.111

**Comment by minshifu** [comment]
> Good news, I could find a way to accomodate the add-on effect on Google results page, and I also improved the drag & drop from unmodified latest Google results page.
> 
> This will be in 2.0.111

Thank you so much for your kind help. Looking forward to the new version!

**Comment by aaFn** [comment]
This is now out in 2.0.111, let me know if any problem, aaFn.

**Comment by minshifu** [comment]
> This is now out in 2.0.111, let me know if any problem, aaFn.

It works great so far. Thanks a lot!
