### ISSUE TITLE
History of bookmarks visited (only bookmarks)

### ISSUE THREAD

**Issue by julia29048** [aaFn/Bookmark-search-plus-2#255]
The Bookmark-search-plus-2 menu item "Bookmark history ..." shows bookmarks which were added, removed, or moved. Would it also be possible (if it is feasible) to have a history of bookmarks (only) visited, but in a separate place which allows one to click on the link and launch?

The default firefox history shows every site, whether it is bookmarked or not. The feature that I am talking about is to have this history but with all non-bookmarked items removed.

**Comment by aaFn** [comment]
Hello @julia29048 , I do not know of an easy way to do that, BSP2 is not really notified when a URL is visited and whether it corresponds to a bookmark or not.

**Comment by julia29048** [comment]
@aaFn : OK thank you for considering. Shall I close this ticket since the request seems unfeasible? 

BTW that you for creating this extension. Find it really useful.

**Comment by aaFn** [comment]
You are welcome, that's ok, I am closing with that comment.
Thank you for your interest and for your support message 😁 , aaFn.
