### ISSUE TITLE
Mouse Hover Over Result & Highlighted Selection

### ISSUE THREAD

**Issue by cvmenn** [aaFn/Bookmark-search-plus-2#256]
You have done an amazing job with this add-on, and I have just a couple of issues. Hope you can help.

1)  I have the "Tittle Only" box checked for the Mouse Hover Over feature, but get Title and URL. This is how the add-on was installed because I just began monkeying around with options yesterday. Could this result auto-correct  next time I load FF? If not,  then perhaps it's a bug.

2) My browser background color is black with white lettering by default so upon un-checking the text color "Override" option and selecting a bookmark or folder, a white highlight bar obscures my white lettering so I can't read it, and can't find an option to either: 1) change the highlight color; 2)  turn highlighting off,; or 3)  have the highlighted word(s) change color to contrast against the highlight bar,  The only remedy is to Override my browser colors to see things again.

Much appreciated.

**Comment by cvmenn** [comment]
How can I be sure to always have the latest update and know it was updated to the latest version?

**Comment by aaFn** [comment]
Hello @cvmenn , I guess you had an old version and you made an update ?

To your last question, as far as I know the only way is in "Manage extensions" = you can search for latest versions, and then extensions get updated. Or if you disabled automated updates, then a little blue dot signals which extensions have an update available, and then you can manually trigger it by left clicking on it.

Else, for BSP2 specifically, hover your mouse on the BSP2 star in the toolbar, and you will see the BSP2 version you have (or see that version number in "Manage extensions", when you click to see the options of BSP2, first tab).
Then you can compare that number with the latest version displayed here -> https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/ or here -> https://github.com/aaFn/Bookmark-search-plus-2/wiki
