### ISSUE TITLE
Unable to open bookmarks to local files

### ISSUE THREAD

**Issue by dlfg68** [aaFn/Bookmark-search-plus-2#258]
First of all, THANKS for this add-on as its really useful ! 
I've encountered a bug.  
I have lots of bookmarks to local txt and html files on my system. 
I see them listed in bookmark-search-plus-2, but when I click on them nothing happens.  
If I right click on them and select open in new tab, nothing happens.  
An example Url of the bookmark is file:///home/dlfg68/t.txt . Permissions on the file are 644 and owned by dlfg68.  
I can manually open local files in Firefox by doing Ctrl-L and entering the url - file:///home/dlfg68/t.txt.    
If I switch back to Firefox's built in bookmark manager ( Ctrl -B ) and click on the bookmarks to local files, they will successfully open.  
Running Fedora 36 amd64 with Firefox 106.0.1 and Bookmark Search Plus 2 version 2.0.111.

**Comment by aaFn** [comment]
Hello @dlfg68 , this is not a bug, but a Firefox protection applied on all add-ons (including BSP2 then), see #206, #189 and #149.

Read also the BSP2 add-on description, and the Limitations section https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/, where I explain that.

**Comment by dlfg68** [comment]
Argh ... Sorry I missed that in the documentation.  Thanks for clarifying.
