### ISSUE TITLE
How to search only folder titles?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [aaFn/Bookmark-search-plus-2#259]
My real life example was to search on folder titles looking only for those that had the word "root" so I could find my folder "Android root"

**Comment by aaFn** [comment]
Hello @UNIVAC-Colonel-Panic , simply use the filters in the red looking glass button at left of the search box:
- Title only
- Show folders only

Then you can easily reset the filters with the grey button on its left
