### ISSUE TITLE
Add bookmark dialog sizing.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#26]
> On the size of the window, since it is not a modal, you can change it at will :-)
Try it, you will see ..
Maybe what you want is that I save the size and restore it to the size it had last time it was closed (at same time than its position) ?
If so, I would suggest that you create a new issue for that. Then we would need also to figure out a way to restore it to its defaults, in case something goes wrong ... If you want to go there, I would welcome any suggestion on the way to restore defaults.
Also, maybe we should care about users who do not want to change it, even by accident (so next open should come back to default size by default) ?

All that seems like a good approach.

Perhaps the following design takes care of all of your concerns:

* You, the dev, size the dialog out of the box, at whatever size you like (e.g. the current size).

* There is an option `restore add bookmark dialog to default size`:
  * If on, a user can resize their current dialog, but on next opening the dialog it will be sized to the default.
  * If off, after a user has resized it their dialog that size preserved between calls.

 * If a user who generally has the option off wants to restore the default resize, they could just temporarily turn the option on.

 * I'd also suggest you add a resize mark in the corner(s), as a UI hint.

As to how to restore defaults I'll leave that is task for either of us to get to (in researching the relevant webextensions storage mechanism), at the high level the algorithm should be straightforward. Something like ...

* Fetch current dialog width and height;
* Store width and height;
* On open of dialogue check if there are stored width and height values. If they exist apply them.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , I also need to remember the size of the search pane, this is one of the TODO's in the list https://github.com/aaFn/Bookmark-search-plus-2/wiki

So I am edging to something like:
```
User Interface settings:
[ ] Remember size of resizeable objects - search pane, edit bookmark property, ..
     (button_enabled_only_when_above_option_is_checked) Reset sizes to defaults
```
How would that sound ?
Or it could be the reverse:
```
User Interface settings:
[ ] Forget size of resizeable objects - search pane, edit bookmark property, ..
     (button_enabled_only_when_above_option_is_*not*_checked) Reset sizes to defaults
```
Less elegant on the button "enabled or not" behavior, I feel.

**Comment by JohnLukeBentley** [comment]
You'll probably want something like ...

    [ ] Forget size of resizeable objects - search pane, edit bookmark property, ...
         [Reset sizes to defaults] (button_enabled_only_when_above_option_is_checked)

... because when the option is *not* checked those resizable objects will persist with their default sizes (and so the question of resetting sizes to defaults is not a relevant user action). That is, if you and I have the same design intentions in mind.

**Comment by aaFn** [comment]
I guess you want to say (button_enabled_only_when_above_option_is_*not*_checked) ?
Else, reset would be only when we forget .. not really going to do much :-)

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , done in 2.0.15.

I chose the form
```
User Interface:
[ ] Remember size of resizeable objects - search pane, edit bookmark property, .. [Reset defaults]
   (button_enabled_only_when_option_is_checked)
```
because easier to transition from current state.

Let me know if there are problems with it.

Note: in Linux, it appears that closing the bookmark property window with the "Close" button on top right does not leave enough time to save position, size .. etc ..
So these are not retained .. looks like a limitation for now, I cannot delay a window close to wait for completion, and I do not want to cancel the close event.
No such problem in Windows as it appears, all is saved.
