### ISSUE TITLE
[request] Take "collapse all in branch" and "expand all in branch" out of the Advanced submenu 

### ISSUE THREAD

**Issue by awalkonthebeach** [aaFn/Bookmark-search-plus-2#262]
I love this extension! I've stopped using the default FF bookmarks pane and I have fully transitioned to this awesome thing.

This is a convenience request, nothing substantial.  I just feel that having a whole extra sub-menu called "Advanced" just to hold the Collapse and Expand options is entirely unnecessary.  I think there is nothing "advanced" about those options.  Personally I hate sub-menus in general because they require an additional mouse click and then moving the mouse sideways to go to the next level, which I find uncomfortable.  I understand that sometimes sub-menus are necessary if there are too many options to fit in the main menu, but in this case it's only two options so the extra menu saves a single line of vertical space in the main menu.  

Thanks for reading!

**Comment by aaFn** [comment]
Hello @awalkonthebeach , the advanced menu was added to provide extensions for not much used commands, so that the main menu does not become too big and cluttered. It is planned for more, even if for now there are only two 😁 .

If you use those two functions quite often, then you can use the keyboard shortcuts for them, cf. https://github.com/aaFn/Bookmark-search-plus-2/issues/31#issuecomment-381116073

(by the way, that reminds me I should document them in the wiki pages ...)

**Comment by aaFn** [comment]
Done, I documented the main non obvious shortcuts in https://github.com/aaFn/Bookmark-search-plus-2/wiki/Keyboard-shortcuts

**Comment by awalkonthebeach** [comment]
That's good to know.  Although, navigating the bookmarks menu requires using the mouse, so the point was to make those options more easily accessible via mouse.  I don't like to switch between mouse and KB too much.  But I understand you have reasons to keep the options in the sub-menu.  

If I have to use keyboard, I would rather just use the single-letter shortcuts in the context menu (the underlined letters).  So I would right-click to open the context menu, then 'v' for Advanced, and then 'C' for collapse or 'E' for expand.  Those are easier to use than Ctrl+Shift+Arrow because they are all on the left side of the KB, where my left hand is by default.  

Alright, thanks for taking the time to read my convenience requests! 🙂
Feel free to close both of them.

**Comment by aaFn** [comment]
Unfortunately, the shortcuts in menus are managed by FF itself, not by the add-on, so a shortcut in a sub-menu is not active in the parent menu ..

On Shift, fortunately there are two of them 😁  => you can use the right Shift plus the arrows, which are usually just besides (no Ctrl in the combinations, see the wiki page)

**Comment by awalkonthebeach** [comment]
Still, the Firefox shortcuts work fine for me and they don't require any weird hand gestures.  I right-click on a folder with the mouse and then use "VC" to collapse all, or "VE" to expand all.  For me that's more convenient than using Shift+Arrow because I still need to select a folder with the mouse first and then I have to move one hand to the KB arrows which are on the right side of the KB, and that requires a lot more hand movement.

![2022-12-24_012620](https://user-images.githubusercontent.com/7669787/209413556-c5dd7bb3-38bf-4e42-ab8a-aa269e24e7b5.png)

**Comment by aaFn** [comment]
Ok, nice, I didn't think of that, indeed looks quite convenient.
