### ISSUE TITLE
[request] Make the alternate (yellow) folder icon the default 

### ISSUE THREAD

**Issue by awalkonthebeach** [aaFn/Bookmark-search-plus-2#263]
I want to thank you for providing an option to use an alternate folder icon with the github link to download the yellow icon.  That alternate icon is far superior to the default gray one and I think it should be made the default.  The yellow icon is much easier on my eyes especially when using he dark theme in Firefox.
The gray one is not ideal because the background color in the bookmarks pane is a darker shade of gray when using dark theme, and also the text is a lighter shade of gray.  So you have a gray background, gray text and gray folder icon.  Having 3 shades of the same color strains the eyes and doesn't look the best IMO.  The off-yellow folder icon has the perfect contrast.  

Thanks for considering!  

![yellow](https://user-images.githubusercontent.com/7669787/208596468-f2a120b0-7332-4170-84a3-feed331e932e.png)       ____ ![gray](https://user-images.githubusercontent.com/7669787/208596486-2bf988af-4017-4c57-82d9-d066b641f5ab.png)

**Comment by aaFn** [comment]
Hello @awalkonthebeach , the yellow folder icon is about 3 years old, it was the one at the start of BSP2, and it was looking like the one of FF in their native Bookmark sidebar.
Then FF changed their folder icon to the one you see, and I aligned to it.

Then they changed again lately, and I stopped aligning .. and sticked to the one you see today.
So, for users like you who prefer different icons, colors .. etc ... I made the option to change at will, and provided the old one.

Notes:
- On light themes, the current one is good. On dark themes, I can agree another one would be better.
- If there is a way to tell if the FF active theme is dark or light, maybe I could have two sets of icons, and change from one to the other based on the theme light/drak indicator .. but I didn't find a FF built-in way, nor an easy way, so far.
- If anybody has suggestions on such an indicator, I am interested 😁

**Comment by awalkonthebeach** [comment]
Thanks for the response!  I had no idea that Firefox kept changing them.  In my opinion you should just ignore what Firefox uses and use whatever looks better.  I would suggest that even on the light theme the yellow icon is more easily identifiable as a folder than the gray one, which means less strain on the eyes (the gray icon with the black outline looks similar to the text and other elements in the pane, which strains my eyes).  But I understand it's a matter of taste and what works for me doesn't necessarily work for you.  I'm grateful that I can customize it and use a different one.  
Cheers!  😊

**Comment by aaFn** [comment]
You are welcome, and do not forget that you can contribute with icons you would like, just create a Pull Request 🙂

**Comment by Andre-ADPC** [comment]
Hi aaFn,

I hope this reaches you. (sorry, to rushed now to log into GitHub to post it all there) If I hear back from you, cool, then you have it, if not I’ll try to remember to go post this on your GH profile.

 

 

Regarding your remark about detecting FFX’s dark-mode:

 

I had a chat to “Jarvis” (OpenAI’s ChatGPT)

 

My question to ChatGPT:

Can you tell me how to programmatically detect Mozilla Firefox's dark-mode?

 

The answer was as follows:

To detect Mozilla Firefox's dark-mode programmatically, you can use the prefers-color-scheme media query. This media query will return the value dark if the user has enabled dark-mode in their browser, and light if they have not.

Here is an example of how you can use the prefers-color-scheme media query in JavaScript to detect dark-mode:

if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {

  console.log('Dark-mode is enabled');

} else {

  console.log('Dark-mode is not enabled');

}

You can also use the prefers-color-scheme media query in your CSS to apply different styles depending on whether dark-mode is enabled or not:

@media (prefers-color-scheme: dark) {

  /* Styles for dark-mode */

}

 

@media (prefers-color-scheme: light) {

  /* Styles for light-mode */

}

Note that the prefers-color-scheme media query is supported in modern browsers, including Mozilla Firefox, Google Chrome, and Safari.

It sounds simple enough using JS. Not sure if your app can incorporate the method described above though. You might have tried this or something similar. If not, well you would know what can and can’t work with BMS+. 

 

On a bit of a tangent:

A feature that would be very great to help sort both folders and bookmarks:

A.	is to be able to open two BMS+ windows next to each other. 
B.	Be able to search in both.
C.	Be able to drag the windows wide enough to see the full URL (or doing text-wrapping)
D.	Users can then drag folders or BMs from one window to the other into the folders where they want them.

Just an idea I have had for a while now, and it keeps popping up when I go back to my stuff and see it might be better suited to be stored in another location in the tree.

 

Anyway, good luck and a happy festive season. Thanks again for your continued effort with this awesome Add-on.

Let us know when you have donations sorted, I would love to donate now and then as cashflow permits, and I’m sure others would too.

 

All the best,

 

 


 


 


 


André Du Plessis
ADPC Projects (IE)
