### ISSUE TITLE
cannot open file:// URL

### ISSUE THREAD

**Issue by Mail9000** [aaFn/Bookmark-search-plus-2#264]
Hello,
I have a report about BSP2 (great extension).
Among the limitations I read: cannot open file:// URL,
If I select the bookmark with "Open in a new tab" nothing happens like limit
But if I select it with "Open in New Windows" the local file is opened.
Maybe there is a workaround to allow opening local files.
[aa.txt](https://github.com/aaFn/Bookmark-search-plus-2/files/10455292/aa.txt)

**Comment by aaFn** [comment]
Hello @Mail9000 , this is not a bug, but a Firefox protection applied on all add-ons (including BSP2 then).

Please read the BSP2 add-on description, and the Limitations section https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/, where I explain that.

See also https://github.com/aaFn/Bookmark-search-plus-2/issues/206, https://github.com/aaFn/Bookmark-search-plus-2/issues/189, https://github.com/aaFn/Bookmark-search-plus-2/issues/149 and #258
