### ISSUE TITLE
[ feature request ]  shortCut for show ALL | folders only | bookmarks only

### ISSUE THREAD

**Issue by m2habert** [aaFn/Bookmark-search-plus-2#265]
If and as the user enlarge his/her bookmarking to a wide variety and huge number of pages, the output search becomes unusable.

As a consequence, I always leave the filter switched to the {folders only} option. I believe, based on my own experience, that this filtering is generally the most used one. 

Ocasionally, I'll search for that specific url or that specif big title. As a mouse-hater, It would be nice to have a shortcut to toggle among the three possibilities (me myself would be happy with just "folders vs bookmarsk" as I never use "show all"). 

A distinctive visual cue would also be great, a simple color one would be enough, nothing fancy. 

Thanks for a great and well-thought-of extension.

**Comment by aaFn** [comment]
Hello @m2habert , there are not a lot of shortcuts available, maybe a cycling one, like reset -> folders only -> bookmarks only -> .. ?
If so, what would be a good shortcut key, not already used for something else, in your view ?

**Comment by m2habert** [comment]
Yes, that solution would be just ideal, and also simple. Thumbs up!

**Comment by aaFn** [comment]
Or maybe an easier one = curretnly, a click on the middle button of the mouse on the filters icon doesn't produce anything, I could use it to do the cycle reset -> folders only -> bookmarks only -> reset -> ..

**Comment by m2habert** [comment]
As a mouse-hater, I would much prefer to have a regular shortkey available, if it's not much trouble.

**Comment by aaFn** [comment]
Hello @m2habert , I can't really find an easy shortcut, the list of free ones is mostly different from one OS to another (Windows, Linux and MacOS), and the ones which are free are not really intuitive.

Also, there is no way in FF to remap shortcut keys (no FireFox's shotcuts page ..). That means I would have to program something for it in the BSP2 options page, like I did for the BSP2 shortcut key (have a look at options), and then to manage storing it in local storage to retrieve it.

Therefore I can easily do something with the mouse, but not very easily with shortcut keys, sorry for that 😞.
As much as you hate mouse, maybe this is still a good way to start until we find a better idea ?

**Comment by aaFn** [comment]
For now, I published 2.0.113 with the feature of cycling using the mouse middle click.
At least this is useable and still easy.
I will adjust if we find a better idea, thank you aaFn.

**Comment by m2habert** [comment]
> 
> Therefore I can easily do something with the mouse, but not very easily with shortcut keys, sorry for that 😞. As much as you hate mouse, maybe this is still a good way to start until we find a better idea ?

Oh, don't mind me, I'm over-playing the "mouse-hating" card for brevity , I shouldn't be too fussy for my own good ;-)   I will certainly get the most out of the mouse-click solution, thanks!

**Comment by m2habert** [comment]
![photo1683578563](https://user-images.githubusercontent.com/7454005/236930708-94f24cf4-d3f1-475e-bd7d-789e5b44a8c5.jpeg)

> 
> Also, there is no way in FF to remap shortcut keys (no FireFox's shotcuts page ..). That means I would have to program something for it in the BSP2 options page, like I did for the BSP2 shortcut key (have a look at options), and then to manage storing it in local storage to retrieve it.

 ( but, on a curiosity note...   I don't get why you say FFx does not have a shortcuts page...
 
 There's one accessible through the "add-ons" page (through the upper right "gear" menu, see picture) 
 
 )

**Comment by aaFn** [comment]
Indeed, but:
- this one only allows to change shortcuts related to add-ons
- add-ons are not notified when you change them (or I didn't see chich event is fired), so cannot react on such changes to store them or manage them.

My message was primarily about the fact that one cannot change shortcuts in FF in the general case = no page to configure all shortcuts in FF, in particular native shortcuts.
