### ISSUE TITLE
SaveSettings

### ISSUE THREAD

**Issue by andreyjc** [aaFn/Bookmark-search-plus-2#267]
I really love the functionality of this FF add-on, it is a must-have. I have a feature request that I don't see anywhere that I can save settings to a file for backup purposes.

**Comment by nollinvoyd** [comment]
I agree.  All addons that have numerous setting choices should have export/import options.

**Comment by aaFn** [comment]
Yep, just need to think of a good format which can be easily interpreted using standard Web API calls / javascript objects so that the code to develop to write data on export and to read data on miport is minimal ...

Any suggestion ?

**Comment by aaFn** [comment]
2.0.114 is now published with the new export / import function as a JSON file. Let me know if any problem.
Thank you, aaFn.
