### ISSUE TITLE
Shift + Click on "Open All in Tabs" to Open All Bookmarks of a Folder in a new Firefox Window - Enhancement Suggestion

### ISSUE THREAD

**Issue by Cr8zyIvan** [aaFn/Bookmark-search-plus-2#268]
I would like to be able to open Bookmarks of a Folder in a new Firefox Window, similar to how Firefox's Bookmark Sidebar works (Right Click on Folder > **Shift** + Click on Firefox's Context Menu "Open All Bookmarks"). 

And of course it is possible to switch from Bookmark Search Plus 2's Sidebar to Firefox's Bookmark Sidebar. Having it be a function of Plus 2 would allow the user to remain in Plus 2's sidebar and make this operation a bit more efficient.

**Comment by Cr8zyIvan** [comment]
Wow, that was pretty fast. Thank you!

**Comment by aaFn** [comment]
2.0.113 is now published with the enhancement.
Let me know if any problem, aaFn.
