### ISSUE TITLE
Display in tab, not sidebar

### ISSUE THREAD

**Issue by VLM-TechEd** [aaFn/Bookmark-search-plus-2#269]
Is there a way to make BSP2 display bookmarks in a tab or window, rather than the sidebar?

**Comment by aaFn** [comment]
Hello, read the doc at https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/

> 
> If you want to see your bookmark tree in a full large view (the sidebar width is limited by FF), open BSP2 in a tab through the magnifier glass icon menu, or through the context menu on the yellow star in the toolbar.
> This also allows you to have two instances of BSP2 side by side to drag from one to the other, to arrange your bookmarks more easily.

**Comment by VLM-TechEd** [comment]
I have limited eyesight. My eyes sometimes miss things these days. So, I apologize if I missed an answer to a question.

 

First, is there a shortcut to open BSP2 in a tab? Or is a bookmark the only way?

 

Second, can this extension support a dark theme in tab view? I have the Theme set to Dark in about:addons. I have the settings item set to dark. And I am using the Dark Background Light Text extension. This is a great combination for me, generally speaking.

 

Third, I am one of those users with tens of thousands of bookmarks stored in thousands of folders. Can anything be done to improve performance? I realize this is an extension, that Mozilla is not supe-supportive of extension developers,  and that the tail is necessarily wagged by the dog. But I have to ask.

 

Thank you kindly!
