### ISSUE TITLE
Feature Request: Insert Bookmark at Top of Menu

### ISSUE THREAD

**Issue by markran** [aaFn/Bookmark-search-plus-2#271]
There's an add-on called [Bookmark Tab Here](https://addons.mozilla.org/en-US/firefox/addon/bookmark-tab-here/) which offers the option of choosing where to insert bookmarks (shown below). It would be great to have this option in BSP2!

![firefox_2xfJDG7YyI](https://user-images.githubusercontent.com/6378626/234335249-92471fe5-2cc2-4bdf-9ef4-cd9dfaec9f41.jpg)

I love BSP2 because I pretty much organize my life around deeply layered bookmark trees! Thanks for a great add-on.

**Comment by aaFn** [comment]
So you mean when dragging and dropping to a folder in the main sidebar panel, or when clicking on "Bookmark tab here" on a folder, be able to change default behavior to add as first child in the folder rather than append at end of folder, correct ?

**Comment by markran** [comment]
Yes, when clicking "Bookmark Tab Here". Thanks!

**Comment by aaFn** [comment]
Ok, this will be in 2.0.114

**Comment by aaFn** [comment]
2.0.114 is now published with this new option. Let me know if any problem.
Thank you, aaFn.
