### ISSUE TITLE
jump to bookmark after search

### ISSUE THREAD

**Issue by wpgerd** [aaFn/Bookmark-search-plus-2#272]
Hello,
because of an issue, I had to reinstall FF and BSP2. Now I missed the behavior to search for bookmarks and I click on the result and below in the folder tree this bookmark will be display. So I can identify in which folder this bookmark was saved. 
Actually, if I click on the bookmark in the search result it will only display the website in the content window right, but not the bookmark in the folder tree below the search result. I can't find an option to change this. Or am I remembering it wrong?

**Comment by mapibid** [comment]
Hello, the behavior you indicate corresponds to the "Advanced click" setting in the BSP2 options.
Two ways to do what you want:
- you stay in advanced click mode, and you click only on the blank parts at front of the result or behind the result (the mouse will show an arrow pointer instead of a finger hand pointer)
- or you switch the option to the "Simple click" setting (= always show bookmark)

**Comment by wpgerd** [comment]
Thanks @mapibid for explanation. Now I understand how this option works. As proposal if possible the contributors can extend the description a little bit. So it's easier to understand:

Advanced (you can choose)
click on blank parts and mouse will show an arrow pointer "Show Bookmark" or
click on bookmark an mouse will show finger hand pointer "Open" in active tab

**Comment by mapibid** [comment]
Ok, I will modify in 2.0.114 to 
![image](https://user-images.githubusercontent.com/18093528/235344325-cb33ee06-78cc-47ed-828b-3b36ee4c405a.png)

hoping this willl be clearer, but still short enough to be readable

**Comment by aaFn** [comment]
Ok, I will modify in 2.0.114 to
![image](https://user-images.githubusercontent.com/36155054/236573446-877cd1b2-81d1-4d6a-a4d3-1cddfad7490a.png)

hoping this willl be clearer, but still short enough to be readable

**Comment by aaFn** [comment]
2.0.114 is now published with the modification.
Thank you, aaFn.

**Comment by wpgerd** [comment]
Thanks very much. Hope it helps other users
