### ISSUE TITLE
Can't delete bookmarks from search results

### ISSUE THREAD

**Issue by kiwichick888** [aaFn/Bookmark-search-plus-2#273]
Not sure if it's a bug or by design but it isn't possible to delete a bookmark from search results? 'Delete' is missing from the context menu.

**Comment by aaFn** [comment]
Hello @kiwichick888 , correct, this is by design, to avoid errors = you have show it in the main panel, and then delete it from the main panel.
I guess once Undo #75 is available, I can enable it.

**Comment by kiwichick888** [comment]
> Hello @kiwichick888 , correct, this is by design, to avoid errors = you have to show it in the main panel to make sure this is the right one you want to delete, and then delete it from the main panel. I guess once Undo #75 is available, I can enable it.

Thanks, but what errors is to avoid?

**Comment by aaFn** [comment]
A result has some ambiguity, until you see where it is in the tree, and what are its sibbling bookmarks. It is lacking some context .. and you could discover after deleting that it was not the one you wanted to delete.

Therefore, until undo is in place, I didn't enable a direct "1-click" delete, to avoid that something ineluctable happens too easily.
It is for now a "2-clicks" delete to give ample time to think about it 😄

**Comment by kiwichick888** [comment]
> A result has some ambiguity, until you see where it is in the tree, and what are its sibbling bookmarks. It is lacking some context .. and you could discover after deleting that it was not the one you wanted to delete.
> 
> Therefore, until undo is in place, I didn't enable a direct "1-click" delete, to avoid that something ineluctable happens too easily. It is for now a "2-clicks" delete to give ample time to think about it 😄

Thanks, but I don't understand what you mean by "It is for now a "2-clicks" delete". Can you please explain how to delete a search result with 2 clicks?

**Comment by ErFaron** [comment]
I think it's a good feature, i was missing it today

**Comment by kiwichick888** [comment]
> I think it's a good feature, I was missing it today

Thanks. I still don't understand how we're supposed to delete search results using the 2-clicks @aaFn mentioned because he didn't answer my question. I can't see any way at all to delete search results. Hopefully one day we'll be able to.

**Comment by aaFn** [comment]
Hello, undo/redo #75 is coming with BSP2 2.0.117, so I will enable this feature at the same time.

**Comment by kiwichick888** [comment]
> Hello, undo/redo #75 is coming with BSP2 2.0.117, so I will enable this feature at the same time.

Fantastic! Thank you.

**Comment by aaFn** [comment]
The feature is now enabled in BSP2 2.0.117, which was just published.
Let me know if any problem, thank you, aaFn.

**Comment by kiwichick888** [comment]
> The feature is now enabled in BSP2 2.0.117, which was just published. Let me know if any problem, thank you, aaFn.

Thanks!
