### ISSUE TITLE
BSP2 opens itself in every new opened window.

### ISSUE THREAD

**Issue by lewie** [aaFn/Bookmark-search-plus-2#276]
Since version 2.0.116, every time I open a window, BSP2 is also opened. Even if an old session is opened in which BSP2 was not active in any window, BSP2 now opens in every window, after restart. 
I often have a lot of windows open, which consumes infinite computing power. Therefore I had to switch off BSP2.

BSP2 had this behavior before, but disappeared quickly after the next FF restart.

Is there a switch that prevents BSP2 from opening independently in newly opened windows?
Or is this a bug?

**Comment by lewie** [comment]
Hello @aaFn, thanks for the quick reply.
Very much it is not what computing power is consumed. But when opening the many windows of a session, the refresh/load just makes a little! No criticism of your great add-on!! ;-)

Previously, BSP2 was loaded only where it was also shown in the previous session. Now Always, also with each opening of a new window. Have to close in every windows single.

But if you say for it FF is responsible, then I must look for the error there. Possibly my profile...
Thanks!

**Comment by aaFn** [comment]
Closing, as this is a Firefox controlled behavior.

Note, and for future reference if FF changes things, I just made some test on FF 115 (and upper), and the behavior is:
- Pressing Ctrl-N (new window) on an an existing window with BSP2 sidebar open creates a new window with BSP2 sidebar
- Pressing Ctrl-N on an an existing window with another sidebar open (e.g. the native FF bookmarks sidebar) creates a new window with that same sidebar
- Pressing Ctrl-N on an an existing window no open sidebar creates a new window with no sidebar
