### ISSUE TITLE
After initiating BSP2, it says "Wait background load.." and doesn't complete.

### ISSUE THREAD

**Issue by Upgeya** [aaFn/Bookmark-search-plus-2#279]
Firefox 114.0.1 (64 bit)

**Comment by aaFn** [comment]
Hello, all is fine hjere, so I will need:
- more details (which OS, which version of BSP2 .. etc ..)
- and input using this procedure https://github.com/aaFn/Bookmark-search-plus-2/wiki/Getting-and-providing-logs-for-debugging-BSP2

Thank you, aaFn.

**Comment by Upgeya** [comment]
Windows 10 (21H2, Os build 19044.3086)
Firefox 114.0.1 (64 bit)
BSP2 version 2.0.116


15:16:45.504 📤 Sending <NmLockState> message to native core <431127191> background.js:2:2297130
15:16:45.530 Error: Warning processing windowTypes: This property is deprecated global.min.js:250
15:16:45.644 📥 Received message <NmLockState> from native core <431127191> background.js:2:2296019
15:16:47.197 ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.
15:16:48.066 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. c.8916.850a4921.js:1:22809
15:16:57.088 Finished loading auth configuration. Processing callbacks. global.min.js:88:471
15:16:57.094 ExtensionError: No such native application 2bua8c4s2c.com.agilebits.1password ExtensionUtils.jsm:55:5
15:16:57.097 [CHROME:NM] Port <[object Object]> disconnected: No such native application 2bua8c4s2c.com.agilebits.1password global.min.js:249:130
15:16:57.097 [AGENT] Connection [object NativeMessagingConnection] disconnected. global.min.js:105:465
15:16:57.098 1Password detected a high number of disconnections from the browser extension to the main application between Mon Jun 19 2023 15:15:16 GMT-0700 (Pacific Daylight Time) and Mon Jun 19 2023 15:16:57 GMT-0700 (Pacific Daylight Time) global.min.js:249:479
15:16:57.098 [AGENT] Connection [object NativeMessagingConnection] disconnected. 2 global.min.js:105:465
15:17:00.509 📤 Sending <NmLockState> message to native core <3781179155> background.js:2:2297130
15:17:00.587 📥 Received message <NmLockState> from native core <3781179155> background.js:2:2296019

**Comment by aaFn** [comment]
Strange, nothing specific to BSP2 .. did you disable BSP2 in the add-on management page, and then re-enable it, while keeping the browser console open ?
We should see some messages like below, and I see none of them ..

> Load saved state..
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> Read saved tree info..
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> Read saved tree..
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> Read migration state..
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> options.sidebarCommand: Ctrl+Q
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> jsonified save method
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> structureVersion: -img16-bnlist-spfldr
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> options.disableFavicons: false
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> options.pauseFavicons: false
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> Load local store duration: 98 ms
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> No install event [background.js:3252:11](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> (Bypass FF API) Tree load duration: 51 ms
> 
> [background.js:135:10](moz-extension://00db443f-01bd-4239-af03-2741bed51aab/sidebar/background.js)
> Tree build duration: 1 ms

**Comment by Upgeya** [comment]
I did the 1st experiment (opening BSP2) without the second.
Here is the 2nd experiment (disable & enable BSP2):
17:25:35.295 📤 Sending <NmLockState> message to native core <132130101> background.js:2:2297130
17:25:35.335 📥 Received message <NmLockState> from native core <132130101> background.js:2:2296019
17:25:37.583 Error: Warning processing windowTypes: This property is deprecated global.min.js:250
17:25:39.134 Load saved state..

background.js:135:10
17:25:39.294 ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.
17:25:41.678 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:826
17:25:41.678 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 9) libstore.js:434:13
17:25:41.679 fileName:   undefined libstore.js:438:14
17:25:41.679 lineNumber: 0 libstore.js:439:14
17:25:41.681 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). libstore.js:443:15
17:25:41.683 uncaught exception: null
17:25:44.171 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:826
17:25:44.171 Promise rejected after context unloaded: An unexpected error occurred
libstore.js:277
17:25:44.172 uncaught exception: null
17:25:44.510 Load saved state..

background.js:135:10
17:25:44.805 ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.
17:25:44.941 Finished loading auth configuration. Processing callbacks. global.min.js:88:471
17:25:44.944 ExtensionError: No such native application 2bua8c4s2c.com.agilebits.1password ExtensionUtils.jsm:55:5
17:25:44.945 [CHROME:NM] Port <[object Object]> disconnected: No such native application 2bua8c4s2c.com.agilebits.1password global.min.js:249:130
17:25:44.945 [AGENT] Connection [object NativeMessagingConnection] disconnected. global.min.js:105:465
17:25:44.946 1Password detected a high number of disconnections from the browser extension to the main application between Mon Jun 19 2023 17:24:04 GMT-0700 (Pacific Daylight Time) and Mon Jun 19 2023 17:25:44 GMT-0700 (Pacific Daylight Time) global.min.js:249:479
17:25:44.946 [AGENT] Connection [object NativeMessagingConnection] disconnected. 2 global.min.js:105:465
17:25:47.112 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:826
17:25:47.113 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 9) libstore.js:434:13
17:25:47.113 fileName:   undefined libstore.js:438:14
17:25:47.113 lineNumber: 0 libstore.js:439:14
17:25:47.115 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). libstore.js:443:15
17:25:47.117 uncaught exception: null

**Comment by aaFn** [comment]
Hello thank you, from the message, it looks like the extension storage is corrupted .. this is an external thing whihc BSP2 cannot act on unfortunately. This can happen to any add-on, and I see that from time to time here, although it never happened to myself.

The usual way to get out of the problem is to uninstall the add-on (here BSP2), which clears up all local storage related to it, and to reinstall it.
If you do not want to lose your settings, do not forget to export them first in the BSP2 options page, and then to reimport them after the reinstall (again on the options page).

Let me know how things go.

**Comment by Upgeya** [comment]
Yes!  This worked!  Thank you!
