### ISSUE TITLE
Searching only within a specific folder?

### ISSUE THREAD

**Issue by DiscoPanda84** [aaFn/Bookmark-search-plus-2#28]
Not sure if this is the place to ask about this, but it is bookmark-related and was part of a different addon by Alice0775, so I figure it might be worth a try to at least ask.

Currently using their old "SavedSearchButton" add-on (in Firefox ESR) purely for the ability to search only within specific bookmark folders in the bookmark library (see [https://i.imgur.com/QDQOVyh.png](https://i.imgur.com/QDQOVyh.png)).

Would this be a reasonable enhancement feature for someone to add to this addon? Or should it be its own thing? (Although believe me, I've searched quite a bit for a Webextensions replacement for this addon. Couldn't even find another XUL addon that does the same thing. Even something that requires typing into the search bar with a syntax like infolder:_foldername_ instead of using a dropdown would be _plenty_ acceptable.)

**Comment by aaFn** [comment]
Hello @DiscoPanda84 , this kind of feature is currently not available through the standard bookmarks.search() API https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/search
I guess it is possible to do it with enough coding, by searching ourselves in the tree, but most probably not as efficient as a native DB query would do ..

Anyway, I might able to do it later as a planned evolution for speeding up the add-on loading would imply caching the full tree in add-on local storage, so I am keeping that one open for later.
If I do it, I would probably go for something like "infolder:foldername" as you suggest, to be typed in the searchbox, and maybe an accelerator in typing it through right-click context menu on a folder ...

**Comment by Sundevyl** [comment]
This would be my number one request.  If you get time, I would use it almost daily.

**Comment by aaFn** [comment]
Hello @Sundevyl, done in 2.0.65 :-)

Note: with FF 68, there is a bug on add-on updates, it keeps in cache some old version of add-on contents. So once your BSP2 is updated to 2.0.65, close FF, then reopen it.

You will see immediately that something changed: the magnifying glass has become a colored active button, and clicking on it, you can change the field to search on, **the scope (all or restricted to a folder)**, and the match method, with words (classical method) or regex.

Let me know if any problem, aaFn.

**Comment by grahamperrin** [comment]
Thanks, 

> FF 68, there is a bug on add-on updates, it keeps in cache some old version of add-on contents.

Do you have the bug number?

**Comment by aaFn** [comment]
Hello @grahamperrin, no, I just observed it, didn't spend time to find if it was already open by somebody, or to open it .. I observed that it concerns at least the .png and the .css files. The .js and . hmtl files are ok ..

**Comment by aaFn** [comment]
Hello @DiscoPanda84, looks like we are ok => closing the issue now as resolved. Let me know if any problem, aaFn.
