### ISSUE TITLE
Feature request: Sort folders (on creating a folder, or possibly at other times, too)

### ISSUE THREAD

**Issue by peter-kehl** [aaFn/Bookmark-search-plus-2#281]
Thank you for BSP2.

Please, consider 

1. Adding an option that, when creating a new subfolder, it will be positioned alphabetically in the parent's list.

1.1 (If the folders are not sorted alphabetically, it would be positioned before/above the first sibling folder whose names comes after the newly created folder's name.)

1.2 And/or, that right after creation, all the immediate subfolders under its parent (that is, the newly created folder and any existing sibling folders) will be sorted by name.

AND/OR

2. Please consider adding an option to sort any and all folders automatically (or at least on BSP2 load).

2.1 We'd need to prevent a spike, for example after an import or after modified/added through Firefox UI. Could it be possible to level by level, in a background async function? Like: Sort immediate kids of the root. Collect immediate kids of those (previous, top level) kids. Sort those collected immediate kids. Repeat...)

2.2 And/or: Or at least sort folders as they are being visited. That is, sort only any folders automatically whenever listing them (whenever expanding the parent folder).

Neither of this is for sorting actual bookmarks.

**Comment by aaFn** [comment]
Hello @peter-kehl , interesting ideas, but these are out of scope of what BSP2 is aimed at.
What you are looking for is a bookmark manager.
This is not the purpose of BSP2:
- bookmarks are inserted where you place them on creation, or at end of folder when dropped or pasted or "New.."on a folder.
- there is no action on bookmarks unless you specifically ask for it
- an action on a bookmark is only limited to the scope you select for the operation, and not to other bookmarks around

If one day I develop a bookmark manager, this sort of functions would indeed be on the list. However, this is not for BSP2.
Meanwhile, I believe there are some bookmark managers around already published as Firefox extension, so you may want to look at them ?

Thank you, aaFn.
