### ISSUE TITLE
[Feature Request] Split the text and background color customization in two: for search results and sidebar

### ISSUE THREAD

**Issue by xan2622** [aaFn/Bookmark-search-plus-2#283]
Hi. 
Thank you for maintaining and enhancing this very useful Firefox extension.

Would it be possible to finetune the text and background color customization by allowing the user to separately modify the text color and background color of: 
- the search results
- the bookmarks tree sidebar

![image01](https://github.com/aaFn/Bookmark-search-plus-2/assets/1732773/a6ef2add-be4f-435f-83dc-a0743ec311fc)

**Comment by aaFn** [comment]
Hello @xan2622 , the color and background and all other UI characteristics (font size, bold .. etc ..) are for the whole sidebar, and are not designed to be at a finer grained level.
Else, nearly the whole of the UI section would need to be duplicated to be able to manage different values for both parts.
Hence, it is not intended to go into more customization at lower level of UI components.

Sorry for the negative response, and thank you, aaFn.

**Comment by xan2622** [comment]
ok, too bad.
