### ISSUE TITLE
[Feature Request] Temporarily open more than one folder with enabled option 'Only 1 open folder at a time ...'

### ISSUE THREAD

**Issue by halejok** [aaFn/Bookmark-search-plus-2#284]
Hi,
I have enabled the option 'Only 1 open folder at a time ...', but temporarily I'd like to open more than one folder.
So could you add the function to open more than one folder by clicking on the blank part of a folder item at left of the folder arrow icon? (like the 'Advanced click' mode)
Regards, hjok

**Comment by aaFn** [comment]
Hello @halejok, too complex to code and non obvious for users to distinguish on the blank part for that kind of subtle function,
however what I can propose is that if you press Shift at the same time than you click on the folder, then it won't close the rest (and I can document this behavior in https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.113), so that would be discoverable by users who take the time to read).

**Comment by halejok** [comment]
Hello aaFn,

I don't think it's obvious or too complicated for users, because they already know this behavior from the "Advanced click" mode.
And you could explain this feature in the add-on Settings panel.

My suggestion corresponds to the functionality provide by this legacy Add-on:
['Autoclose Bookmark&History Folders'](https://www.sephiroth-j.de/1/mozilla/) (for Firefox 42.0 - 56.*)
.xpi download URL from [Classic Add-ons Archive](https://github.com/JustOff/ca-archive/):
https://ca-archive.us.to/storage/258/258721/autoclose_bookmarkhistory_folders-0.7.2-fx.xpi

See the following .gif:
![AutocloseBookmark HistoryFolders](https://github.com/aaFn/Bookmark-search-plus-2/assets/50183502/56ae7c5e-7c06-4837-9bc2-972876f6f843)

Settings:
![AutocloseBookmark HistoryFolders](https://github.com/aaFn/Bookmark-search-plus-2/assets/50183502/9b4192ff-a863-4059-8960-1d5de95deb5c)

But this add-on is not so comfortable compared to my suggestion.
It's annoying to have to click precisely on the arrows.
Perhaps the code from this add-on can help you develop the code for my suggestion?

But if it's really too difficult, the option with shift key would be okay too.

Thanks very much.

Regards, hjok

**Comment by aaFn** [comment]
Hello @halejok , got it, and agree on things being too uncomfortable when trying to aim a tiny object like the twistie.
Well, with Shift, things cannot happen by accident (the same as for advanced click, one has to activate the function first, so cannot happen by accident) = when you press Shift it really means you wanted it.

Also, Shift can apply to the keyboard way of doing things, for those who do not like the mouse = Shift+Enter (like Shift + click) will then keep all other folders open, while simple Enter (like click) will close all others.

And yes, coding two times the same function but with a variation of behavior is less direct than the Shit approach.

So I'll implement the Shift approach in the next release.

Thank you, aaFn.

**Comment by aaFn** [comment]
Done, available in 2.0.119, which was just published.
Thank you, aaFn.
