### ISSUE TITLE
File bookmarks don't work

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#286]
Reproduce:

1. In the FF address bar dump a url to a local file and surf to it. E.g. `C:/Users/John/Documents/Sda/Info/ComputerSystem/Hardware/Keyboards/KeyboardQuertyFingerLayoutFromKeybr.png`.
2. Once the page load drag the bookmark to somewhere in BSP2. 
3. In BSP2 Right click the bookmark. > Properties. Obeserve Location/URL which will be something like `file:///C:/Users/John/Documents/Sda/Info/ComputerSystem/Hardware/Keyboards/KeyboardQuertyFingerLayoutFromKeybr.png` (which should be OK).
4. Close any FF tab with the file showing.
5. In BSP2 click on the bookmark. It doesn't load.

The same bookmark can be opened from the native bookmark manager.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , indeed, this is Firefox which prevents add-ons to do that.

See #264, https://github.com/aaFn/Bookmark-search-plus-2/issues/206, https://github.com/aaFn/Bookmark-search-plus-2/issues/189, https://github.com/aaFn/Bookmark-search-plus-2/issues/149 and https://github.com/aaFn/Bookmark-search-plus-2/issues/258 ...
and also the BSP2 add-on description, and the Limitations section https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/, where I explain that.

**Comment by JohnLukeBentley** [comment]
Hello @aaFn, 

Apologies. it's been so long I'd forgotten the issue. #206 is my issue. I note the FF limitation.
