### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by SteveRubenhound** [aaFn/Bookmark-search-plus-2#287]
Looking for the .xpi release files and can't find any, says "No releases published".

**Comment by aaFn** [comment]
Hello @SteveRubenhound , not sure I understand what you mean by "looking for .xpi release files".
AMO takes care of generating them for us and of distributing them.

Where to you search for that exactly ?

**Comment by aaFn** [comment]
Ah so no, in standard, the .xpi are generated and signed by AMO on Mozilla.
We do not generate and sign them ourselves ...

To view all versions, you have to get them on AMO -> https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/versions/

**Comment by SteveRubenhound** [comment]
thanks!
