### ISSUE TITLE
Auto Hide BSP - setting, shortcut

### ISSUE THREAD

**Issue by VLM-TechEd** [aaFn/Bookmark-search-plus-2#288]
I have limited use of my hand/wrist, so anything I can do move things from mouse to a setting and/or the keyboard is greatly appreciated. Is there a way to:

1. Set BSP so that the sidebar does not open automatically, but only when I ask it to.
2. Toggle BSP sidebar or tab show/hide using keyboard shortcuts.

Thank you, and I wish everyone a Happy New Year!

**Comment by aaFn** [comment]
Hello @VLM-TechEd , not sure what you mean by 1), this is controlled by FF, which restores the sidebar as it was at last close (so if it was open, it then it is open, and if it was closed, then it is closed).

For the shortcut to toggle the state in 2), read the BSP2 description, it tells you what is the default shortcut depending on your OS.
You can also retrieve it, and change it, by going to the Add-ons/Themes management panel, then click on the cog wheel, and click on Manage add-on shortcuts.

Cheers, aaFn.

**Comment by VLM-TechEd** [comment]
Ah, yes, the cog wheel. Of course! Thank you, and Happy New Year!

 

Elchanan, PE for Vibrant Living Ministries, and Successors

**Comment by aaFn** [comment]
Welcome, and same to you 😃
