### ISSUE TITLE
"properties" don't open

### ISSUE THREAD

**Issue by elandorr** [aaFn/Bookmark-search-plus-2#289]
v2.0.120 + 115.5.0
Versions don't seem important as this has been happening for a long time across different machines.

Nothing in the browser console.
Unchanged behavior even with FF's bookmark manager opened.

I just gave up on it and use the FF manager to rename things.

**Comment by aaFn** [comment]
Did you check the "multiprocess" option in the Browser console, for some reason it seems that when this is unchecked, add-on exceptions or messages do not show 😢

**Comment by aaFn** [comment]
Ok, that error  is normal, when closing the property window there are still sometimes some FF messages remaining it seems and when they arrive to the closed window which doesn't exist anymore .. this creates this error.

The property window being slow to open is not normal, this is very fast usually, so something must be going on in your FF instance which is slowing things down.
Could I suggest to open a new tab and type `about:processes` in it, sort by cpu, and have a look if anything is eating your FF cpu time ?

**Comment by aaFn** [comment]
> I noticed the "slowness" is identical to a dialog in Thunderbird. It spawns a small rectangle, then expands. Seems this is a Mozilla problem.
> 
> Since your last update and a restart, the properties opened reliably. I cannot say if this is just random luck, however.

Yes, this is a workaround to an old problem in FF to be able to open the property window with a given size and position. I will check if that problem has been cured since then, as I am reading that happened maybe on FF 109, and if yes I'll try to get rid of that old workaround.

**Comment by aaFn** [comment]
Hello, I confirm that FF corrected their bug on window position in FF 109, so I removed the workaround when running FF under that version or above, which accelerates the opening of the property window, and of the history window.

Let me know if any problem.
Thanks, aaFn.

**Comment by aaFn** [comment]
Closing, assuming all is ok now, or working better.
Let me know if not, aaFn.

**Comment by Hibrix-net** [comment]
Hi,

I have the exact same problem with the latest extension + FF version. The properties popup window opens but for some reason is unreachable even clicking on its thumbnail.
Could you please help?

**Comment by aaFn** [comment]
Hello @Hibrix-net , by thumbnail, I guess you mean the window icon in the taskbar ?
If it is showing in the taskbar, that means the window is here, and if you can not see it in any way, that means that:
- it must be in a part of the screen hiding things behind it (like the taskbar itself, another bar, .. whatever ..).
- or it is so small in size that you can't see it

Can you confirm if you have enabled the option "Remember size of resizable objects" ?
One way to get around this is to click on the "Reset defaults" button on the right of it, if enabled.

Else, I will need a log of the errors you can see when opening the Property window, as discussed above.
See https://github.com/aaFn/Bookmark-search-plus-2/wiki/Getting-and-providing-logs-for-debugging-BSP2 for instructions.

**Comment by Hibrix-net** [comment]
> Hello @Hibrix-net , by thumbnail, I guess you mean the window icon in the taskbar ? If it is showing in the taskbar, that means the window is here, and if you can not see it in any way, that means that:
> 
>     * it must be in a part of the screen hiding things behind it (like the taskbar itself, another bar, .. whatever ..).
> 
>     * or it is so small in size that you can't see it
> 
> 
> Can you confirm if you have enabled the option "Remember size of resizable objects" ? One way to get around this is to click on the "Reset defaults" button on the right of it, if enabled.
> 
> Else, I will need a log of the errors you can see when opening the Property window, as discussed above. See https://github.com/aaFn/Bookmark-search-plus-2/wiki/Getting-and-providing-logs-for-debugging-BSP2 for instructions.

Hello,

Yes, I meant the icon in the taskbar. The screen is not hiding it, it is simply unreachable. I've been using your extension for years and never happened before. I also did what you suggested but it's the same.
I assume this bug was introduced by a sudden Firefox update.

Thanks anyway,

**Comment by aaFn** [comment]
Are you under Windows or another system ?

If under Windows, one workaround can be to:
- select the window icon in the taskbar to make it active
- then press Alt+spacebar
- then use the window menu that opens with your keyboard (or mouse, as possible) to select "Move"
- and use your keyboard arrows (up, down, left, right) to move the window
- this action also binds your window to your mouse, and moving the mouse now also moves the window
- you can also use the same menu to see if the window is minimized for example and ot restore it, or make it full screen, change its size ...

If you are under MacOS, or Linux, I believe there are equivalents, but I do not know them.

Hope this can help.

**Comment by Hibrix-net** [comment]
@aaFn That worked perfectly for me! Many thanks for your kind support :)
