### ISSUE TITLE
Feature request: enable Ctrl+click and Shift+click for multiple selection

### ISSUE THREAD

**Issue by EmilianoCostantini** [aaFn/Bookmark-search-plus-2#29]
Hello aaFn,

I was still testing the addon, and it seems that neither  **_Ctrl+click_**  nor  **_Shift+click_**  would work for **multiple bookmarks/folders selection**.  Is it just me, or is it by design?

I did the test on:
```
    ◆Linux Lite 3.16
    ◆FF 59.0.1 (64bit)
    ◆Bookmark search plus 2 (version 2.0.12)
```

This is the console output when using Ctrl+click or Shift+click in the addon panel:
```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.  (sconosciuto)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”). Source: height:0.  2-pane-bookmarks
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).  2-pane-bookmarks
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).  2-pane-bookmarks:1
Evento da tastiera non disponibile in alcuni layout di tastiera: tasto=“r” modificatori=“accel,alt” id=“key_toggleReaderMode”  browser.xul
Evento da tastiera non disponibile in alcuni layout di tastiera: tasto=“i” modificatori=“accel,alt,shift” id=“key_browserToolbox”  browser.xul
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”). Source: height:0.  faviconreloader
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).  faviconreloader
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).  faviconreloader:1
Caricamento non riuscito per lo <script> con sorgente “https://www.google-analytics.com/analytics.js”.  faviconreloader:10
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”). Source: height:0.  default-bookmark-folder
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).  default-bookmark-folder
TelemetryStopwatch: key "FX_SCHEDULE_PRESSURE_IDLE_SAMPLE_MS" was already initialized  TelemetryStopwatch.jsm:356
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src”).  default-bookmark-folder:1
```

**Comment by aaFn** [comment]
Hello @EmilianoCostantini , correct, multi selection is currently not possiblen this is a TODO https://github.com/aaFn/Bookmark-search-plus-2/wiki

**Comment by wtfiwinomgs** [comment]
please add this feature, kinda make and break for people have lots of bookmark this increase efficiency drastically.

**Comment by wtfiwinomgs** [comment]
its been a year, any update on this?

**Comment by aaFn** [comment]
Progress made on that with 2.0.84 published today on AMO, which is preparing internal code structures to support multiple bookmarks selection, and is already introducing support for receiving multiple bookmarks drag from Windows, Linux and MacOs Desktop or File Manager to BSP2 (#163).

Will add the UI part of that function in a later release, hopefully the next one.

**Comment by elandorr** [comment]
Any update on this a year later? That'd be great!

Thank you for your work in general! It's a must-have addon. This is so important, it should be native. Now with multi-select and drag and drop import/export to (desktop) folders organizing is much easier. Mozzarella's included one is not that helpful, and the main feature of path-finding has an open bug from 10 years ago. Your addon helps a lot.

**Comment by aaFn** [comment]
Hello, done and published tonight with 2.0.103.
Let me know if any trouble, thanks, aaFn.

**Comment by mzso** [comment]
Thanks! So far it seems to work fine.

**Comment by EmilianoCostantini** [comment]
Thank you so much! I'll give it a try ASAP!!

**Comment by mzso** [comment]
@aaFn
Does this addon have an effect in history or places expiration in any way? Probably coincidental, but in recent days I noticed my history disappearing. At first I had only 10 thousand items, which was already low and now a few days later it plummeted below 5000, only going back to February 27th. Something's very wrong here.

**Comment by aaFn** [comment]
Hello @mzso , do you mean Firefox browsing history ? No. By the way, how do you know how many records you have in Firefox browsing history ?

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2022. márc. 15. 23:17 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/29#issuecomment-1068521655 "2022-03-15T22:17:24Z - Replied by Github Reply Comments"):
> Hello [@mzso](https://github.com/mzso) , do you mean Firefox browsing history ? No. By the way, how do you know how many records you have in Firefox browsing history ?

(Yes browser history)
Well, lacking addons nowadays that can show me, I just add a "." in the search field of the library window. Then select all the results and firefox shows shows me. History seems to progressively decreasing. The first I checked, when it got suspicious, it was 10000+ going back to early february, now it is only goes back to februar 28  (Damn, it decreased again, it was 4400+ an hour ago, now it's <del>4273</del>4218)

**Comment by mzso** [comment]
@aaFn Do you think the number of bookmarks increasing to large value can trigger a bug? (Now, because of this I have a lot more bookmarks than history, 20000+)

**Comment by aaFn** [comment]
Ok, I see, you select all, then paste in a text editor, and get the number of lines .. correct ?
On my side, I got about 28000 lines, and history goes back to more than 6 months (can't tell exactly, FF is not more precise than that).

Could you be hitting this ? https://bugzilla.mozilla.org/show_bug.cgi?id=1753729

**Comment by mzso** [comment]
@aaFn 
Not quite. Firefox shows the number of items in the library (history) window, when I select multiple items on the bottom panel.
(I checked the oldest by ordering by last visitation.)

**Comment by aaFn** [comment]
Ok, I see, so my oldest is more than 1 year old (Jan 17th ..).
Did you check your disk space .. given your symptom, you look like hitting the problem I gave in the bugzilla link above

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2022. márc. 15. 23:54 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/29#issuecomment-1068541895 "2022-03-15T22:54:06Z - Replied by Github Reply Comments"):
> Could you be hitting this ? [https://bugzilla.mozilla.org/show\_bug.cgi?id=1753729](https://bugzilla.mozilla.org/show_bug.cgi?id=1753729)

Seems like it. Thanks. Well, most of my history is gone by now...

[**@aaFn**](https://github.com/aaFn) commented on [2022. márc. 16. 00:12 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/29#issuecomment-1068552083 "2022-03-15T23:12:08Z - Replied by Github Reply Comments"):
> Ok, I see, so my oldest is more than 1 year old (Jan 17th ..).  
> Did you check your disk space .. given your symptom, you look like hitting the problem I gave in the bugzilla link above

Yeah. Just got to that part of the bug, and then complained. It's Mozilla™ stupid. Pre-emptively causes dataloss when space is getting low, don't even have to run out of it. How nice.

**Comment by mzso** [comment]
@aaFn 
Back on topic. I just realize that opening of multiple selected items in BSP+ is not possible. There's no context menu item and ctrl+click doesn't work and even dragging them to the tabbar only opens one.
Not sure if it's not working or just not implemented.

**Comment by aaFn** [comment]
Multiple drag to FF is not working, this is not supported in standard.
I may enable the "open in .." menu actions on selection ni future, need to think a little more about it would work when a folder is included in the selection.
