### ISSUE TITLE
"Match active FF theme colors" does not actually match.

### ISSUE THREAD

**Issue by antboy** [aaFn/Bookmark-search-plus-2#294]
Hi, nice add-on but for my theme, the option "Match active FF theme colors" does not actually match.  The theme I use is a dark one where the background is black (0,0,0) and text is bright green (0, 255, 0), but the bookmark panel shows a white background, with FF 122.0.1 .
I can override this by using your "Override text color and background **color"** option, but this shouldn't be necessary?

**Comment by antboy** [comment]
It turned out the theme did not have a setting for the sidebar colour, so nothing to inherit.

**Comment by aaFn** [comment]
Ok, good to know, probably a bug to open to the theme author then 😄 

Thank you, aaFn.
