### ISSUE TITLE
Show full path for folders on hover - standard navigation

### ISSUE THREAD

**Issue by peter-kehl** [aaFn/Bookmark-search-plus-2#297]
Summary: Like #129, but for (standard) navigation tree (NOT for the search results).

- Like @ejemba in #129, I have many folders with the same name all around my tree. (For example, `zOther` keeps misc. items in many parts of my tree.) And
- I do NOT use "Only 1 open folder at a time : close all other open folders under same parent when opening a folder" option.

Proposed: On mouse over/hover on a folder in the tree, show its path in the bubble, please. (We most likely don't want to show it all the time even if not on mouse over, as that would clutter the limited sidebar space.)

If this could be confusing existing users, how about an option to enable this.

**Comment by aaFn** [comment]
Yes, that one should be easily doable, and be static as you say.
Note: displaying the same text as the folder name as it is today, is a bit meaningless ..

**Comment by aaFn** [comment]
Hello @peter-kehl , I implemented this as part of 2.0.128, which is out now.

It creates an inconsistency, because this is only on folders, and I am pretty sure that next, somebody will ask for the same thing on pure bookmarks, but let's see ..

Thank you, aaFn.

**Comment by peter-lyons-kehl** [comment]
Thank you aaFn. So good.
