### ISSUE TITLE
Search tags

### ISSUE THREAD

**Issue by SteveRubenhound** [aaFn/Bookmark-search-plus-2#298]
Hi, could you guys add an option to search tags in addition to bookmarks and folders?

**Comment by aaFn** [comment]
Hello @SteveRubenhound , as can be read on the add-on description, or when searching in the issues, tags are not accessible to add-ons in FF = tags are not visible, not modifiable/writable, not manipulable .. This is simply not in the FF API, cf. https://bugzilla.mozilla.org/show_bug.cgi?id=1225916

Best regards, aaFn.

**Comment by SteveRubenhound** [comment]
Ok, thanks

**Comment by SteveRubenhound** [comment]
Ok, thanks! What does "cf" mean?
