### ISSUE TITLE
Upon bookmark search result: open web page and tree location V open tree location only

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#3]
@aaFn wrote (quoting @NicolasWeb intiallly) in #1:
>>  I would love to be able to show parent folders while not having to open the web page of search result bookmark.
>
> Sorry to be so slow gents ... as a matter of fact, you can do it :-)
> 
> Simply, click on the search result on left or right of the "image+text", where the mouse pointer is an arrow, and not where it is a "hand with finger" ... and you'll get what you want.
> Indeed, you'll notice that when you hover the mouse over the result you want to look for, the whole result row is highlighted .. that is to signal to you that you can click anywhere on it and:
> 
> - left clicking on a part which is not the link nor the image will simply show where it is in the bookmark pane, no other action,
> - left clicking on the link or image will open it in current tab, and also show the item in the bookmark pane
> - right clicking anywhere in the result will show a context menu to chose where to open the link -> I guess I could add a menu option to "show bookmark" also, to make it "not only one way of doing things" .. let me know.
> 
> By the way, the same behavior occurs for normal bookmarks, clicking outside the link/image simply highlights it with no action, clicking on it opens it in current tab, and right click = context menu ..

Thanks for that explanation. That works fairly well, once explained. 

However, if possible it is better to design an interface/system that has clues, or some discoverablity mechanism, that the user can pick up on ... making an explanation unnecessary.

So although it is true that there is a sense that your pattern (clicking inside v outside icon+text) is consistent with the native bookmarks tree ... I don't think users learn this pattern from using the native bookmark tree. That is, because it is not quite analogous. 

When you use the native bookmark tree:

* If you click inside the icon+text then you get the web page loaded.
* If you click outside the icon+text then nothing happens. 

With the second option users are not learning that "some action happens when I click outside icon+text". So I don't think you can leverage the way the native bookmark tree works to have users learn about how your BSP2 works.

Alternative patterns are a creative matter. My personally preferred solution would be to ...

First note that we probably want different behaviour for interacting with a bookmark in the search result window V the tree. Bookmark interaction behaviour in the tree should just follow whatever the native patterns are (as they appear to currently do ... e.g. middle click on a bookmark here loads the web page in a new tab). So this is mostly a matter of what ought be done with bookmarks in the search result window.

I'd suggest a change to the right click menu of the search results to:

* **Find in tree**
* Find in tree and open in this tab [Shift + Click]
* Find in tree and open in new tab [Middle Click]
* Find in tree and open in private window

I'm not necessarily attached to the phrase "Find in tree" but at least for our discussion you'll know what is meant. I don't think it is bad phrase, but there might be something better.

Following the Windows pattern the first option is bolded to indicate the default (this is a pattern you currently observe). So the consequence of that is:

* If a user `LEFT CLICK`s it only executes "Find in tree".
* If a user `SHIFT + LEFT CLICK`s this executes  "Find in tree and open in this tab".
* If a user `RIGHT CLICK`s this opens the menu (as it does currently in conformance with Windows pattern s) and the above two commands are discoverable.

If you implemented the above pattern you wouldn't have to necessarily remove your existing pattern (click inside V outside icon+text), e.g. if you had some particular fondness for your existing pattern. That is, because those two patterns don't interfere with each other.

@NicolasWeb's view about this would be valueable.

Edit: Include references to issue #1.

**Comment by aaFn** [comment]
@JohnLukeBentley  ok I liike that and agree with your reasoning and demonstration.
The only difference I see is that with the native bookmark search, left click on the (image or text) of a search result does open the page in current tab.
So to remain consistent I believe I should stick to that .. but all the rest is good with me.
I'll try as a first pass, and if that is not good, we can change ..

**Comment by JohnLukeBentley** [comment]
> The only difference I see is that with the native bookmark search, left click on the (image or text) of a search result does open the page in current tab.

Ah sorry, yes. If you implemented my proposed pattern a left click (anywhere on the line of the url) in a search result would *only* execute "Find in tree". That would contradict both the native behaviour and BSP2's existing behaviour. 

I'd recommend biting the bullet and contradicting native behaviour here and using `LEFT CLICK` for "Find in tree" only ... because BSP2 introduces new functionality.

But ...
> I'll try as a first pass, and if that is not good, we can change ..

... yes, since you have your hands on the clay you'll be better able to see what emerges as you play with the thing. So, of course, please do follow your intuitions here. In other words I'll be more than happy to see a candidate solution that is quite different from what I suggest.

**Comment by aaFn** [comment]
Ok, let's go with the intermediate then for now:

1. If a user LEFT CLICKs it should execute "Find in tree" always, and additionally "open page in current tab" if the user clicked on the image or url link (this is an HTML <a> link) = like today and like on native
2. If a user SHIFT + LEFT CLICKs this should execute "Find in tree and open in this tab", wherever he clicks (=> will not have to change if we change 1) for the other option)
3. If a user middle clicks, this should execute "Find in tree and open in new tab"
4. If a user RIGHT CLICKs this should open the menu (as it does currently in conformance with Windows patterns) and the above three commands are part of the menu.

And we'll see where to adapt if that creates too much trouble.

**Comment by JohnLukeBentley** [comment]
Yes, that sounds all good. We'll play with that implementation and see where to go from there.

**Comment by NicolasWeb** [comment]
(will read other comments later. Too busy now)
Please, add keyboard shortcuts for Linux too ;-)

**Comment by JohnLukeBentley** [comment]
@NicolasWeb yeah this is collaborative volunteerism. So I hope we foster the feeling that we get to tasks in the fullness of time, when the flow of life makes it fun and interesting to do. This handy text based method of collaboration enables the taking of our time. You'll know all this, it's perhaps worth mentioning though, from time to time.

**Comment by aaFn** [comment]
@NicolasWeb, setting the keyboard shortcut to Ctrl+Shift+B in Linux .. see https://github.com/aaFn/Bookmark-search-plus-2/issues/4

**Comment by aaFn** [comment]
@JohnLukeBentley, 2.0.4 is out, with the above defined behavior (repeated below). Let me know if we can close that issue for now, and we should open another one if this is creating more trouble, if you agree.

1. If a user LEFT CLICKs it should execute "Find in tree" always, and additionally "open page in current tab" if the user clicked on the image or url link (this is an HTML <a> link) = like today and like on native
2. If a user SHIFT + LEFT CLICKs this should execute "Find in tree and open in this tab", wherever he clicks (=> will not have to change if we change 1) for the other option)
3. If a user MIDDLE CLICKs, this should execute "Find in tree and open in new tab"
4. If a user RIGHT CLICKs this should open the menu (as it does currently in conformance with Windows patterns) and the above three commands are part of the menu.

**Comment by JohnLukeBentley** [comment]
Thanks for the coding!

> If a user RIGHT CLICKs this should open the menu (as it does currently in conformance with Windows patterns) and the above three commands are part of the menu.

I'm not seeing them. I see what might be the same menu as for 2.0.0. Under 2.0.4 I see:

* Show bookmark.
* **Open**
* Open in new tab
* Open in new window
* Open in private window

(By the way it is Windows conventional for the bolded default to be the first command).

And I still think, for the search window, the click inside/outside icon+text behaviour confusing and unrecoverable. But perhaps if you make the right click menu change first, we (or I) could better examine your currently intended behaviour.

**Comment by NicolasWeb** [comment]
An other option could be to add an option to the addon (is that possible with WebExtensions ?), like in Firefox Tabs preferences to let the user choose if a (any, right, left, middle) click should open the bookmark (and that could be the default, then).
@aaFn and @JohnLukeBentley , if you agree, let's open an new issue for that.

> Searching for a string I'm confident will get a small set of bookmarks near or around the target bookmark (having forget the string of the target bookmark). The target bookmark not necessarily being among them.

I would prefer that it never open the bookmark, as like @JohnLukeBentley in comment 1 of #issue 6 I used go-parent-folder to find a bookmark while searching for one that I remember is not far away..

In 2.0.4 I do have the RIGHT CLICK opening the menu.
I do agree with the menu items ordering proposed by @JohnLukeBentley , and that click inside/outside icon+text is not discoverable, especially a the line is highlighted while hoovering (even if now that I know it, I use it)

**Comment by JohnLukeBentley** [comment]
> an option ... to let the user choose if a (any, right, left, middle) click should open the bookmark (and that could be the default, then).

Yes, that might be a way for @aaFn to give us what we want, while keeping what she or he wants. 

However, I think that's part of the same issue .... it really depends on the shape of the out-of-the-box defaults that @aaFn settles on.

>  I would prefer that it never open the bookmark.

Yes indeed: left clicking anywhere on the url in search result pane, I think, should only "Find in Tree" not also "Open in webpage". To provide an additional argument: that would be in keeping with the former Go Parent Folder pattern.

> In 2.0.4 I do have the RIGHT CLICK opening the menu.

Do you see the same menu items I'm seeing?

**Comment by NicolasWeb** [comment]
>> I would prefer that it never open the bookmark.

> Yes indeed: left clicking anywhere on the url in search result pane, I think, should only "Find in Tree" not also "Open in webpage". To provide an additional argument: that would be in keeping with the former Go Parent Folder pattern.

An argue for that (default behaviour under an option ?) is that it's the value of this addon. To me if you want to find open you open (like a click in the native bookmark sidebar), if you want to find in the tree. you fin... ;-) . To me the default action we want to perform while searching is to find a bookmark... and *maybe* open it (then).
But maybe that's my own pattern... :-S I mean, if @aaFn made the opposite default choice, that might be for a reason for her / him.

>> In 2.0.4 I do have the RIGHT CLICK opening the menu.

> Do you see the same menu items I'm seeing?

I have a menu as you described:

>  Show bookmark.
    **Open**
    Open in new tab
    Open in new window
    Open in private window

**Comment by aaFn** [comment]
Hello, ok, I can change the order and set the bold one first indeed, no problem.
And yes, I can make the context menu change its bold (default) option depending on where we right click to make that discoverable indeed .. I was also thinking about that on my own.

I guess I could even make the highlight color change depending on where is the pointer, in addition to having the pointer iself change = this is actually the only hint that the behavios is different, the type of pointer is a hand with finger on favicon+text, and is a bare arrow on left and right parts.

Show bookmark (if it is a bookmark), and Show folder (when a folder) are now in the context menu, they were not in 2.0.3 and below.

On the option for behavior, yes I like it. Let's discuss that on  the new issue you opened then :-)

**Comment by aaFn** [comment]
Implemented in 2.0.5, both on order and on context menu change depending on right-clicked part, when the "Advanced" preference is checked.

When the "Advanced" preference is unchecked, then this is "Show bookmark" (or "Show folder") all the time first, as default / bold.

Setting to "close".

**Comment by aaFn** [comment]
Changed to use `ALT` key instead of `SHIFT` in the above, in order to mimick native bookmarks behavior, as per #44
