### ISSUE TITLE
Option request : disable favicons

### ISSUE THREAD

**Issue by mazesy** [aaFn/Bookmark-search-plus-2#30]
Hi,

BSP2 establishes connections for the sole purpose of retrieving favicons.
As I see it, localizing a bookmark in Firefox's Places is an on-line task, by nature.
Therefor, being able to localize bookmarks -- which BSP2 does perfectly well -- without the extension establishing connections seems to me a pertinent option.

As far as I'm concerned I already miss BSP2, having chosen to not use it anymore until the option be made available.

Thanks.

**Comment by aaFn** [comment]
Hello @mazesy , so if I understand well, you want an option to disable favicon retrieval, correct ?

Please note that the privacy concerns raised by TheWindBingeth in https://www.wilderssecurity.com/threads/mozilla-created-shortcuts-favicon-caching-windows.343315/ are not really applying to BSP2:
1. The favicons are only retrieved for bookmarks you have in the library, so they reveal nothing more than your bookmarks themselves already reveal
2. There is no file shortcut stored anywhere by BSP2, only the image of the favicon is stored as a base64 encoded string https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding, and all images are together in FF local storage, not as individual files in the file system (no date, no path, no mounting point, nothing .. only the binary of the image)

Let me know if you still want an option to disable favicons, and I can look at adding that if you really want.

**Comment by mazesy** [comment]
Hi @aaFn, thanks for replying.

Correct.

When I mention this option I am in no way implicitly stating privacy issues. I am only in  the scheme of a user who doesn't use favicons and from there on considers than an extension which does retrieve them is incoherent from _his point of view._

I tested again last night, simply opening BSP2 from the sidebar and Nirsoft's CurrPorts application revealed a parade of connections, to Google included. I understand your comment but I just don't want these connections initiated every time I start BSP2, especially that I block favicons Firefox-wide.

As you see, no issue in terms of functionality and privacy, only the wish of an option to avoid a process unsuitable on a browser which has been set in contradiction to that process.

Thanks.

**Comment by aaFn** [comment]
Ok, done in 2.0.15, which is scheduled to be out tonight.

Note that this also allows me to remove a TODO :-)
- TODO: Add massive refresh of all favicons, apart from the initial load at first start of the sidebar just after installing the add-on. For now, this can only be done individually by right clicking on bookmark items, one by one.

Indeed, to trigger massive refresh of all favicons, set the option, reload the add-on, then remove the option, and reload again the add-on ..

Let me know if ok, or if you see any problem after that (by opening a new issue). Thanks.

**Comment by mazesy** [comment]
I was aware that Google being called during favicons' retrieval was specific to the url, not an extra call: I should have made that clear.

I clean localStorage, I dislike sites' data, so in my case favicons would be recalled at each session.

Many thanks @aaFn for announced BSP2 version 2.0.15, I'll check it as soon as available and confirm here afterwards, but I'm sure it will be given the whole extension is flawless and that blocking favicons' retrieval is only an extra option unrelated to the core and problematic-free.

I'll be back then, reporting!

**Comment by mazesy** [comment]
Just installed BSP2 version 2.0.15, checked _Disable favicon fetching_ and all is for the best.
Many thanks @aaFn I truly appreciate it.

**Comment by aaFn** [comment]
Welcome
