### ISSUE TITLE
Error on Import Settings

### ISSUE THREAD

**Issue by markran** [aaFn/Bookmark-search-plus-2#300]
Received "Error while importing selected file, the import didn't complete !" while loading this json file [config-bookmark-search-plus2.json](https://github.com/aaFn/Bookmark-search-plus-2/files/14541192/config-bookmark-search-plus2.json)

I think the error is caused by parsing a settings file with the "Remember size of resizeable objects" fields present as I manually compared it with an export from a fresh BSP2 install was able to load it after editing the file to remove those fields.

**Comment by aaFn** [comment]
Hello @markran, indeed, there was a bug on the expected format when importing that option.
I corrected it.

I also found in the process 2 other bugs, happening when multiple options change at the same time, or on font and space size changes which were imperfectly detected.

This is all corrected in 2.0.126, let me know if there remains any problem.
