### ISSUE TITLE
Custom CSS Area

### ISSUE THREAD

**Issue by N3C2L** [aaFn/Bookmark-search-plus-2#301]
Hello!

Thanks for your effort in this addon! Highly Appreciated! May I ask you for a feature?
I find the search results too small when the addon is opened in a tab.
If I could, I would change from this:

#searchresult {
	height: 20%;
}

to this:

#searchresult {
	height: 50%;
}

It would be really helpful if you could implement a CSS text box area
where users can paste some custom CSS that work for your addon.

Please let me know what you think about this. 

Thanks!

**Comment by aaFn** [comment]
Hello @N3C2L , the searchresult area is resizeable, and if you tick the option to "Remember the size of resizeable objects ..", it will persist across sessions and FF restarts.

On the CSS text box area, probably one day, but not now.

**Comment by Gitoffthelawn** [comment]
@N3C2L 
If you are using Firefox, you can create a `userContent.css` file, and customize BSP2 to your heart's desire!  If you're not familiar with `userContent.css`, or where to place it, a web search will yield comprehensive details.

**Comment by aaFn** [comment]
Closing the issue for now, thank you aaFn.
