### ISSUE TITLE
[Feature request] Open bookmarks directly from filtered search results

### ISSUE THREAD

**Issue by kiwichick888** [aaFn/Bookmark-search-plus-2#303]
Can you please add an option to open bookmarks directly from the filtered search results? I find it frustrating having to click twice - once on the filtered search result and again from the actual bookmark folder.

**Comment by N3C2L** [comment]
You can already open the  search result in a new tab. You have to click on the text. But you have to activate this setting first:

![image](https://github.com/aaFn/Bookmark-search-plus-2/assets/74585843/5203a78e-4286-4d97-bd5b-0498b418223f)

**Comment by kiwichick888** [comment]
> You can already open the search result in a new tab. You have to click on the text. But you have to activate this setting first:
> 

Thanks, I didn't understand what that setting meant.
