### ISSUE TITLE
[Feature Request] Drag and drop bookmarks from the BSP2 sidebar of one Firefox instance into the BSP2 sidebar of another Firefox instance

### ISSUE THREAD

**Issue by halejok** [aaFn/Bookmark-search-plus-2#304]
Hi,
I usually have multiple Firefox instances (not windows) running simultaneously (versions from portableapps.com).
Is it possible to implement drag and drop bookmarks from the BSP2 sidebar of one Firefox instance into the BSP2 sidebar of another Firefox instance?
Regards, hjok

**Comment by aaFn** [comment]
Hello @halejok , indeed, right now this is failing because I am missing a firefox instance id to tell that a received drag&drop is coming from an exterior instance of Firefox, and not from our own instance.

I need to investigate if there is an easy way to detect that ..

**Comment by aaFn** [comment]
Hello @halejok, I found a way, and I implemented it in 2.0.128 which is out now.

Note that thanks to this, BSP2 allows you to do something which the native FF bookmark sidebar cannot do then :

to drag bookmarks from one FF instance to another (when you enabled several FF instances to run in parallel), giving users an easy way to export/import their bookmarks from one FF instance to another.

Let me know if any problem with the function. Thank you, aaFn.

**Comment by halejok** [comment]
Hello aaFn,
Great! It works. Many thanks.
Now I just thought of the following: Would it be possible for the 'Date added' to be transferred as well?
For me, it's often important to know when a bookmark was created.
Regards, hjok

**Comment by aaFn** [comment]
Hello @halejok , unfortunately that level of control is not given to add-ons, here is the API we get https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/CreateDetails

as you can see, we cannot set the 'Date added' (although I do transfer it, so I have it, it is just that I cannot set it ... 😿).
It cannot be updated on this attribute as well https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/update
