### ISSUE TITLE
[Feature request] Show path to bookmark and title + url

### ISSUE THREAD

**Issue by kiwichick888** [aaFn/Bookmark-search-plus-2#306]
There is an option for "On mouse hover show path to bookmark instead of title + url". I'd like to request an option to show path to bookmark and title + url.

**Comment by aaFn** [comment]
Duplicate with https://github.com/aaFn/Bookmark-search-plus-2/issues/291.
Note that the feature is implemented now in 2.0.128

**Comment by kiwichick888** [comment]
Excellent, thank you very much.
