### ISSUE TITLE
Right click menu. Collapse/Expand commands.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#31]
I suggest the following commands be added to the right-click menu:

* Collapse all in branch.
* Expand all in branch.
* Collapse all.
* Expand all.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , wht bothers me is that the menus are quite big already.
If we add more, they will be very busy and use too much of the estate to my taste.

If we want to add such things, we would need to devise something ... like sub-menus ?
Or simply, no menu, just keyboard shortcuts (like +/- on a folder to open/close, and shift + and shift - for expand all / close all under that folder we are one (cursor).

What do you think ?

**Comment by JohnLukeBentley** [comment]
I see nine commands/menu items on my right click menu in BSP2 ... that's not very big I'd suggest. Compare for example the Windows Explorer folder right click menu: I have 27 menu items.

Menu separator bars in menu's can be used to make the menu usable: putting related commands within two bars. I think you could include these commands in the main right click menu without needing to submenu them ... without creating a great space burden.

But if you want to put these commands in a sub-menu that'd be fine. I don't think, in that case, adding one other menu item (to serve as a sub menu) at the main level would be less of a space burden.

I think all these commands should have keyboard shortcuts **and** appear somewhere in the rightclick menu (whether at the main level or submenu level). Relegating them to have keyboard shortcuts only would mean disoverability is lost.

I'd suggest these keyboard shortcuts, as arrow keys are somewhat conventional for doing this sort of thing in programs with trees:

* Collapse branch (Left Arrow) [This is the shortcut in the native bookmark sidebar]
* Expand branch (Right Arrow) [This is the shortcut in the native bookmark sidebar]
* Collapse all in branch (Shift + Left Arrow)
* Expand all in branch (Shift + Right Arrow).
* Collapse all (Ctrl + Shift + Left Arrow).
* Expand all (Ctrl + Shift + Left Arrow).

... although an argument can be made that `Collapse all` and `Expand all` should not have keyboard shortcuts because they are "dangerous".

... and, indeed, my suggestion has expanded to include two more commands.

**Comment by JohnLukeBentley** [comment]
> "Collapse branch" and "Expand branch"  .. (the keyboard shortcut however is needed, whatever case).

I agree that a keyboard shortcut is needed, whatever the case.

Sure, leave them off the menu if you prefer. The original four commands are of main interest.

**Comment by JohnLukeBentley** [comment]
Bump on this. 

Given I now have a tree with all sorts of open branches it is making my tree undesirably large. So as a user I'm feeling a pressing need for, above all, "Collapse all".

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , the two first ones exist now since 2.0.45, see https://github.com/aaFn/Bookmark-search-plus-2/issues/73

For the others, I still do not see the difference with using the folder twistie at the needed level ? Visually, this is the same, and the idea of massively opening or closing folders does not look like a very frequent use case. If you believe I am wrong, could you illustrate a little more when there would be such a need ?

**Comment by JohnLukeBentley** [comment]
Thanks @aaFn 

>  the two first ones exist now since 2.0.45, see #73

I've skimmed #73 and am I right to understand by:

* "Collapse all in a branch" you mean you've implemented the OP's initial request " I can easily collapse the opened grandparent/parent/child folder path of a selected bookmark by repeat-clicking the left arrow key."; and
* "Expand all in a branch" you mean you've implemented the OP's initial request " use the right arrow and the down arrow to open a folder and then its child folder etc. and then to navigate the contents of that folder."

?

If that is right, the following commands would still be different:

* Collapse all in branch (Shift + Left Arrow)
* Expand all in branch (Shift + Right Arrow).
* Collapse all (Ctrl + Shift + Left Arrow).
* Expand all (Ctrl + Shift + Left Arrow).

(Recall my "The original four commands are of main interest").

For example "Collapse all in branch" closes everything bellow the branch at once, in contrast to #73 which would require  multiple key presses.

> For the others, I still do not see the difference with using the folder twistie at the needed level ?

The folder twistie only closes the current branch, not any opened child folder (this is desirable and should not be altered). A "Collapse all in branch" would close *all* open child folders.

> and the idea of massively opening or closing folders does not look like a very frequent use case.

It's a frequent use case for me. I suspect, for me, this is last remaining issue in BSP2, before I'd regard BSP2 as "fully fledged" (any other issues being a matter of polish).

Of the four commands, the following two would be the most important ...

* Collapse all in branch (Shift + Left Arrow)
* Expand all in branch (Shift + Right Arrow).

That is, arguably "Collapse All" and "Expand All" is near enough to being superfluous given you could execute a "Collapse all in branch" or "Expand all in branch" on one of the root folders. On that basis if you chose to implement "Collapse all in branch" or "Expand all in branch", but not "Collapse All" and "Expand All", then that would give me that main thing I'm after.

I'm happy to make further explanations if any of that is unclear, or requires further argument.

Recall also I recommend this commands (whether 2 or 4) be made available on the right click menu (in addition to being available via keyboard shortcut).

**Comment by aaFn** [comment]
Hello @JohnLukeBentley, yes on #73.

On the 4 others, ok I see the difference, and agree with the reasoning that only 2 are really needed because the other 2 are the same thing executed at top.

Now, sorry to be slow, I still fail to see the exact use case of these two commands.
More exactly, when do we want to open all sub folders, and sub-sub folders .. etc .. of a folder ?
As for the recursive close, since this is the inverse of the first, i can easily see that it's justified if the first is needed, so I am only trying to understand the benefit of the first.

At any rate, since this is you asking, I could agree to make the effort of adding the keyboard shortcuts. For menu entries, I would need to get more convinced though :-)

**Comment by JohnLukeBentley** [comment]
Thanks for being open to more convincing.

## Use cases

> Now, sorry to be slow, I still fail to see the exact use case of these two commands.
More exactly, when do we want to open all sub folders, and sub-sub folders .. etc .. of a folder ?
As for the recursive close, since this is the inverse of the first, i can easily see that it's justified if the first is needed, so I am only trying to understand the benefit of the first.

Actually I think the first, "Collapse all in branch", (and/or "Collapse all" if that was also to be implemented) is more important than "Expand all in branch". As I previously mentioned the use case is ...

In a deeply nested tree, with many branches opened, there comes a point where you want to "clean the slate" and close everything to avoid clutter that you've built up over time. At present to close everything would require multiple key presses or twisty clicks (the more branches you have open, the more key presses/twisty clicks required). By contrast a "Collapse all in branch" (and/or "Collapse all") command would achieve the desired result, closing everything, at once.

"Expand all in branch" (and/or "Expand all") ought be implemented:
1. For symmetry with "Collapse all in branch" (and/or "Collapse all"); and
2. (As in independent use case) Because sometimes you want to open an entire branch, including all subfolders recursively. You want to do this, for example, when you are cleaning out your bookmarks.

## Other outlining applications having these commands

These sort of commands aren't some idiosyncratic desire of mine. In almost all applications that use some kind of outlining they exist.

For example ...

... in MyLifeOrganized (https://www.mylifeorganized.net/) we have:

![mylifeorganized-collapseexpandcommands](https://user-images.githubusercontent.com/18357541/52101341-4eddfc00-262f-11e9-95a8-4ae6ec0ff504.jpg)

* "Collapse/Expand subtasks" (Collapse all in branch/Expand all in branch)
* "Collapse entire outline" (Collapse all)
* "Expand entire outline (Expand all)

... in BrainforestProfessional we have:

![brainforestprofessional-collapseexpandcommands](https://user-images.githubusercontent.com/18357541/52101345-58fffa80-262f-11e9-8efd-433b1b916c7f.jpg)

* "Collapse branch" (Collapse all in branch)
* "Expand branch" (Expand all in branch)
* "Collapse all" (Collapse all)
* "Expand all" (Expand all)

There are some exceptions. For example Windows Explorer doesn't have a "Collapse all" or "Collapse all in branch" command. But there is good reason for that: the entire tree is collapsed (to a high level) on each session close: when you open up a new Windows Explorer the tree is expanded to at most one level.

**Comment by aaFn** [comment]
Now that I can do more complex menus, I will look at doing something for this in 2.0.71, for FF >= 64.
As I do not want the menu to get too big, I intend to add a submenu for such Advanced commands.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley, 2.0.71 is out with
- Collapse all in branch (Shift + Left Arrow)
- Expand all in branch (Shift + Right Arrow).
in a new Advanced context menu, which also now hosts the "Refresh favicon" action.

I hope this is ok on your side, let me know, aaFn.

**Comment by JohnLukeBentley** [comment]
Hi aaFn,

Thanks!

That certainly gives us the main functionality I was after. In particular I can quickly collapse my entire tree by selecting my "Bookmarks Menu" node and "Collapse all in branch". The shortcut key is also very handy.

On my root node, "Bookmarks Menu", both commands operate really fast. With quite the large tree size of ...

```
Bookmarks:            4680
Favicons to fetch:    0 (0.0%)
Folders:              1610
Separators:           9
Oddities:             0
```

So well done with the optimization there!

However, I'm of the view that it would further improve things, from more important to less important, to:

* Have these commands on the top level of the menu, not in an "Advanced" submenu. My menu has only 14 commands (counting "Advanced"). Having 15 or 17 commands is no big deal, I'd suggest.
* Publicize the shortcut key in the menu, for all commands with a shortcut key. E.g. With "Collapse all in branch (Shift + Left Arrow)", rather than ""Collapse all in branch",  in the menu.
* Add the "Collapse all" and "Expand all" commands.

But those suggestions are less significant that the functionality you have already implemented. And if you (still) objected to those suggestions I don't think I'd push back. Particularly given there's not a great deal of argument to be had: it's just a matter of making the call one way or the other.

Incidentally, I also see the "Refresh Icon" when I click on a bookmark node (rather than folder node). So that looks all as you've intended. Although I haven't really tried to test it: the handful of my bookmarks that have the default icon, and that I've looked at, either: no longer exist; or the website author has not set up a icon.

**Comment by aaFn** [comment]
Good, glad this is working well then :-)

On menus, I took the approach that all that is not part of the standard menu in the native Bookmark sidebar shoud be in Advanced as much as possible .. Hence those additional folder commands there, as well as Refresh favicon. Only exceptionn to that is "Go parent folder" as this is a core missing feature of FF.
Maybe wrong .. for now I'd rather stick to that, and then we can change later.

Yes, on shortcuts I need an elegant way for people to know about them. I'll think about it, maybe indeed add them simply to the menu as you say.

Thanks, aaFn.

**Comment by aaFn** [comment]
Closing as all is working now. Thanks, aaFn.
