### ISSUE TITLE
Search "Current folder tree", cut link, then paste into new directory - search is reperformed

### ISSUE THREAD

**Issue by woofie56** [aaFn/Bookmark-search-plus-2#315]
Hi, when I do the following : 

1)Select directory "A"
2)Toggle "Current folder tree" & "Title only"
3)search for item "ABC" in title
4)Cut
5)Paste into new directory "B"
6)The addon reperforms the search

Is there any way for me to switch off the reperforming of search? i.e. what I want is to see the set of results of the original search as I cut and paste items from directory "A" into directory "B"? Thanks.

**Comment by aaFn** [comment]
Hello, the search is a realtime panel, reflecting always the latest state.
So the answer is no.

**Comment by woofie56** [comment]
OK thanks. Is there any way to reperform a realtime search on the original directory (rather than the destination) as one copies and pastes individual items?

**Comment by aaFn** [comment]
Not sure I understand your question: in "Current folder tree", the search panel shows the realtime search results in the folder selected at time of first executing the search.
Later on, you can select other folders / bookmark items, the search result will not change its focused folder.

So simply select the source folder for the focused search, and it will always be showing the realtime search on the source folder.

**Comment by 7295QB** [comment]
Hi, if in the lower panel I select an alternative folder, the search does not refresh (as you pointed out above). 

However if I do : 

1)Search 
2)Select Item in lower panel
3)"Cut"
4)Select alternative folder in lower panel
5)"Paste Into" -> at this point search results are refreshed to that of destination folder

**Comment by woofie56** [comment]
Hi, if in the lower panel I select an alternative folder, the search does not refresh (as you pointed out above).

However if I do :

1)Search
2)Select Item in lower panel
3)"Cut"
4)Select alternative folder in lower panel
5)"Paste Into" -> at this point search results are refreshed to that of destination folder

**Comment by aaFn** [comment]
Hello, thank you for the detailed scenario to reproduce.
I improved the behavior of scoped searches to make them more consistent and stable: they will only change / refresh when the scoped search option is changed/reset, or when the content of the searchbox changes, or when the scoped bookmark is deleted.
No change when another folder is cut and moved to another, like in your scenario.

This will be in 2.0.131.

**Comment by aaFn** [comment]
2.0.131 is out with the enhancement, let me know.
Thank you, aaFn.

**Comment by woofie56** [comment]
@aaFn : tested it out and it works really well. Thank you very much.
