### ISSUE TITLE
Firefox Doesn't Remember Bookmark Search Plus

### ISSUE THREAD

**Issue by murph146** [aaFn/Bookmark-search-plus-2#316]
When i close Firefox with BSP open, typically when i re-open Firefox BSP is remembered and pinned to the right side of the browser. Lately, it will not remember the position or that it was open and I have to click on the extension to open it. Done a Firefox refresh and uninstall and reinstall. Any help would be appreciated as this is my go to bookmark manager.

**Comment by aaFn** [comment]
This seems related to, although the inverse of, https://github.com/aaFn/Bookmark-search-plus-2/issues/312
I believe this is also related https://github.com/aaFn/Bookmark-search-plus-2/discussions/314

This is all controlled by Firefox, and nothing that BSP2 or an add-on can do about.

Searching on Bugzilla, as I see that we have several occurrences now, it appears that something was made as part of FF 128 which is causing this sort of instability. And some cases would be related to the "Clear Recent History" option in FF.

Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1922777 and https://bugzilla.mozilla.org/show_bug.cgi?id=1908019 for example and for more details. There are probably more around in Bugzilla, to search for.
I read there that a fix could appear in FF 133 ..
