### ISSUE TITLE
Request for feature : collapsing the tree for compacting the whole scope of the tree

### ISSUE THREAD

**Issue by PY-Delens** [aaFn/Bookmark-search-plus-2#317]
Dear,
Bookmark-search-plus-2 is really wonderful; 
It allowed us to switch our Knowledge Management from disk files to bookmarks collection : a [more and more necessary] revolution.

The bookmarks tree becomes very large, and the performance is still ok  :-)  👍 

> Bookmarks:             12900
> Favicons to fetch:     0 (0.0%)
> Unsuccessful favicons: 774 (6.0%)
> Folders:               1035
> Separators:            477
> Oddities:              0

The search tool is OK, but walking throughout the tree is often more efficient.
We would need to be able tos sometimes collapse the tree to the top level (or 2 levels).

Are there possibilities? Turnaround? via FFX API?
Do you have a roadmap for tasks and updates about that?

Anyway, thanks for this tool, really.

**Comment by aaFn** [comment]
Hello @PY-Delens , not sure of what you mean by collapsing the tree to the top level.
If you are talking about closing all open branches, there are 2 options to 2 that:
- Right click on the top "Bookmark menu" blookmark, then on Advanced->Collapse All in Branch
- Or navigate using the keys in https://github.com/aaFn/Bookmark-search-plus-2/wiki/Keyboard-shortcuts, using `Left Arrow` / `Shift Left Arrow` as appropriate.

There is no specific roadmap published, all things which are planned to be done are still open on the issues page, with a "todo" flag on them, and those where something could happen are flagged as "for later consideration".

**Comment by PY-Delens** [comment]
Thanks a lot !

*

 

 

De : aaFn ***@***.***> 
Envoyé : dimanche 17 novembre 2024 23:40
À : aaFn/Bookmark-search-plus-2 ***@***.***>
Cc : Pierre-Yves Delens ***@***.***>; Mention ***@***.***>
Objet : Re: [aaFn/Bookmark-search-plus-2] Request for feature : collapsing the tree for compacting the whole scope of the tree (Issue #317)

 

Hello @PY-Delens <https://github.com/PY-Delens>  , not sure of what you mean by collapsing the tree to the top level.
If you are talking about closing all open branches, there are 2 options to 2 that:

*	Right click on the top "Bookmark menu" blookmark, then on Advanced->Collapse All in Branch
*	Or navigate using the keys in https://github.com/aaFn/Bookmark-search-plus-2/wiki/Keyboard-shortcuts, using Left Arrow / Shift Left Arrow as appropriate.

There is no specific roadmap published, all things which are planned to be done are still open on the issues page, with a "todo" flag on them, and those where something could happen are flagged as "for later consideration".
