### ISSUE TITLE
Issue: cannot find mobile bookmark

### ISSUE THREAD

**Issue by lewinr** [aaFn/Bookmark-search-plus-2#33]
Hi, I'm liking this firefox addin but I think I might have found a big.

I use firefox on my Android phone and and on Windows PC and sync my bookmarks.
I created a new bookmark on my phone.
Now I see it on my PC and can find it in Bookmark Search Plus, but when I click on Show I am not shown where this bookmark sits in my hierarchy.  (The pane does not update, the previous bookmark stays highlighted.

In this example I've highlighted the "Greek lamb chops..." bookmark that I created on my phone and synced to my PC, but when I click "Show" the previous bookmark "Crispy Rack of Lamb" stays highlighted and I am not shown where the "Greek lamb chops..." bookmark resides...

![image](https://user-images.githubusercontent.com/38337281/38712209-fab1de6e-3e7e-11e8-9934-ba15951f7b33.png)

**Comment by lewinr** [comment]
Hi, I’m not sure what exactly you’re asking… when I close the “Booksmarks Menu” tree I see just three items: “Bookmarks Toolbar”, “Bookmarks Menu” and “Other Bookmarks”.
Indeed there is no top folder “mobile”.
Here’s a screenshot:

[cid:image005.jpg@01D3D2F4.4B1A3BE0]

When I switch to the native FF bookmarks manager, I see the mobile folder:

[cid:image006.jpg@01D3D2F4.4B1A3BE0]

**Comment by aaFn** [comment]
Ok. Images missing, but you confirm what I thought.
I'll look into supporting the optional  top level "Mobile" folder, should be in 2.0.17.

**Comment by lewinr** [comment]
Thanks.  (I suspected that the images might be lost in an email reply, this is my first experience with github…)

**Comment by aaFn** [comment]
Hello @lewinr , 2.0.17 is out and should handle Mobile bookmarks.
I am not really using the Sync feature of FF, so my tests may not be so good.

Normally things should be ok from the few test I could make with a few sync'ed bookmarks, but better if you let me know if all is good or not (and sorry to take you as "beta tester" to validate).

I will wait for your feedback before closing the issue, or for debugging further with you, if you agree.
Thanks, aaFn.

**Comment by lewinr** [comment]
Thank you, it appears to work correctly now.

**Comment by aaFn** [comment]
Thank you, closing the issue then.
