### ISSUE TITLE
Provide way to re-trigger 16x16 favicon migration

### ISSUE THREAD

**Issue by aaFn** [aaFn/Bookmark-search-plus-2#35]
As seen with @JohnLukeBentley in #2 , and comparing display times with #5 , it may be that the migration to 16x16 favicons didn't complete properly in some cases.

This issue is to have a better status of the migration, to robustify it further,  and to provide a way to retrigger it in case there is suspicion it previously didn't complete well.

**Comment by JohnLukeBentley** [comment]
I'm here and automatically subscribed to this thread. So if you want me to test anything let me know.

**Comment by aaFn** [comment]
Thank you.
2.0.17 is out. Could you:
- upgrade
- open the Browser console (Ctrl+Shit+J)
- go to the options page, tick "Activate traces" in the "Traces / debug" section
- press the button `Re-trigger 16x16 favicon migration` in the same section
- recycle the add-on through Ctrl-Q and Ctrl-Q again (for example)

You should see in the trace textarea that structureVersion is empty.

Then wait 1 minute after the last favicon load (which should be somewhat more than 1 minute after the add-on load now) and you should see:

```Migrating <xxx> favicons to 16x16```

And when the migration is complete:

```
Migration to 16x16 favicons complete
Count of abnormal favicons: <yyy>
```

Then, if you can paste here:
- The contents of the trace textarea
- The contents of the browser console

we should see if there's anything abnormal, or if all is migrated, or maybe all was already 16x16 (doubtful, but we never know).

If needed, you can do the above multiple times, that shouldn't hurt in any way (only a few % of cpu when doing the migration), and if there where favicons still remaining to migrate, the count should be 0 with a message:
```
Nothing to migrate to 16x16 favicons
Count of abnormal favicons: <yyy>
```

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , are things ok now, or is there still no display speed improvement on your side ?

**Comment by aaFn** [comment]
I guess things should be ok by the time .. :-)
Closing the issue, let me know if we need to reopen.

**Comment by JohnLukeBentley** [comment]
Sorry @aaFn, I've been busy and some of these have slipped by me.

I followed your procedure above.

At "You should see in the trace textarea that structureVersion is empty." I don't get this. Rather

    PlatformOs: win
    Setting Windows variations
    structureVersion: -bnlist
    Load local store duration: 498 ms
    Tree load duration: 852 ms
    Tree build duration: 12 ms
    Display duration: 1294 ms
    fontFamily = '"Segoe UI"'
    fontSize   = '12px'
    Stats:
    ------
    Bookmarks:  4267
    Folders:    1486
    Separators: 8
    Oddities:   0
    --------------------
    Save duration: 1036 ms

After one minute I get

Trace


    PlatformOs: win
    Setting Windows variations
    structureVersion: -bnlist
    Load local store duration: 498 ms
    Tree load duration: 852 ms
    Tree build duration: 12 ms
    Display duration: 1294 ms
    fontFamily = '"Segoe UI"'
    fontSize   = '12px'
    Stats:
    ------
    Bookmarks:  4267
    Folders:    1486
    Separators: 8
    Oddities:   0
    --------------------
    Save duration: 1036 ms
    Migrating 0 favicons to 16x16
    Nothing to migrate to 16x16 favicons
    Count of abnormal favicons: 0

Browser Console

    ERROR BaseProcess IFrameProcess.start Could not start process: Did not receive handshake in time [] [{"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0","extensionLogId":"b0aeecdc-b95d-4f2f-be2f-8706e00539d5"}]  Extension.built.min.js:74
    ERROR ProcessManager _createProcess Failed to start process Feed firefox59.0 {"major":1,"minor":1,"build":1,"revision":1} (Feed): Could not start process: Did not receive handshake in time [] [{"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0","extensionLogId":"b0aeecdc-b95d-4f2f-be2f-8706e00539d5"}]  Extension.built.min.js:74
    Error: WebExtension context not found!  ExtensionParent.jsm:855:13
    POST
    XHR
    https://fls-na.amazon.com/1/ubp/1/OE
    [HTTP/2.0 204 No Content 735ms]
    GET
    XHR
    https://fls-na.amazon.com/1/action-impressions/1/OE/bit-reporter/action/ProcessManager.createProcess.Feed_:Failure@v=1,Failure.1@v=1,Failure.firefox@v=1
    [HTTP/2.0 204 No Content 734ms]
    POST
    XHR
    https://fls-na.amazon.com/1/ubp/1/OE
    [HTTP/2.0 204 No Content 732ms]
    SyntaxError: test for equality (==) mistyped as assignment (=)?  panel.js:3399:50
    SyntaxError: test for equality (==) mistyped as assignment (=)?  panel.js:3408:50
    GET
    XHR
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
    [HTTP/1.1 200 OK 59ms]
    POST
    XHR
    https://titan.service.amazonbrowserapp.com/
    [HTTP/1.1 200 OK 749ms]
    Error: db is undefined  undefined
    GET
    XHR
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
    [HTTP/1.1 200 OK 56ms]
    Error: db is undefined  undefined

**Comment by aaFn** [comment]
Hello @JohnLukeBentley, thank you.

So:
1. Yes `-bnlist` is a new flag in 2.0.18, post dating those instructions, to signal we're now using an internal tree structure instead of a simple hash list, to prepare for next optimization phase, and which also accelerate copy, cut, paste, drag&drop when plenty of bookmarks.
The important point is that the `-img16` flag is missing, meaning a migration step will re-occur 1 minute after start.
2. Then migration starts 1 minute later.
And `Migrating 0 favicons to 16x16` simply means all your icons are already in 16x16 format, nothing more to migrate.
3. The two errors on `mistyped as assignment` should be without consequence (or let me know), and anyway not related to favicon migration, they are related to a drag & drop operation you were doing.
=> even if presumably no consequence, this is not clean, so I will correct them in 2.0.19.

Well, so this means no gain for you .. neither on display, neither on storage.
I am a little surprised by that, but if any favicon was not 16x16, the migration code would have reacted, so ... I don't know what to do more on this front.

Or maybe you have the "Disable favicon fetching" option set ? And so there is nothing to optimize since in that mode, favicons are not stored .. (see #30).
In any case, it looks like we can leave that issue closed then, there appears to be nothing more to get out of this. Thank you.

**Comment by JohnLukeBentley** [comment]
No I didn't have "Disable favicon fetching" set.

Anyway, I'll take your lead and go over to #2 "Optimising loading" for the more general issue. Thanking you!
