### ISSUE TITLE
Feature Request - add an icon in toolbar

### ISSUE THREAD

**Issue by blueray453** [aaFn/Bookmark-search-plus-2#36]
It would be very helpful to have an icon in toolbar instead of using Ctrl+Q.

**Comment by aaFn** [comment]
Hello @blueray453 , indeed, this is also what #18 is asking for.
This is in plan yes, not sure yet in which coming version, but I wil provide an option (disabled by default) to activate a button in the toolbar for those who wish indeed.

**Comment by aaFn** [comment]
Working on it for 2.0.18.

**Comment by aaFn** [comment]
I found it is not possible to make the button appear on option .. As soon as it is specified in the add-on, it is here and cannot be removed by code.
So it will be here for all, no option to show or to hide it .. :-(

For people finding the button annoying, they will have to manually remove it from the toolbar.
Sorry.

**Comment by aaFn** [comment]
Function provided with 2.0.18.

**Comment by stef204** [comment]
> I found it is not possible to make the button appear on option .. As soon as it is specified in the add-on, it is here and cannot be removed by code.
> So it will be here for all, no option to show or to hide it .. :-(
> 
> For people finding the button annoying, they will have to manually remove it from the toolbar.
> Sorry.

This can't be right. Even when one removes the button from toolbar manually, it reappears on next startup.  Surely, something can be done about it.
If not, would be best to disable this altogether (unless you can make it optional but apparently, you cannot?)
