### ISSUE TITLE
Release Note (changelog/what's new) not displayed in Browser's Addon update page

### ISSUE THREAD

**Issue by v00p** [aaFn/Bookmark-search-plus-2#39]
**Current Behav**: no changelog shown:
![no changelog shown when updating extension from browser](https://im3.ezgif.com/tmp/ezgif-3-a6427ebe53.gif)

**Expected:**
Include either the actual changelog**ⁱ**, [or a link to it](https://github.com/aaFn/Bookmark-search-plus-2/wiki#release-notes)

**ⁱ**![](https://i.imgur.com/jlMqCWi.png
)

**Comment by aaFn** [comment]
Interesting, I didn't know about that function ...
Done, I have put the link in there

https://github.com/aaFn/Bookmark-search-plus-2/wiki

I should do it from now for all next releases also.
Thanks, aaFn.
