### ISSUE TITLE
Keyboard shortcut, Alt+B, doesn't work.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#4]
... to determine whether this is a problem at my end or a genuine bug ...

@NicolasWeb does `Alt+B` work for you?

**Comment by aaFn** [comment]
So on that one, the behavior is inconsistent .. sometimes it works, sometimes not.
But basically there is a conflict I didn't catch initially:
Alt+B is in fact the shortcut for the Boomarks menu on the menu bar.

So I need to pick another keyboard shortcut.
Choice is either semantic, either practical ...

Anything against Ctrl+X ? (= practical, not far from Ctrl+B for the Bookmark native sidebar, still same left hand, still holding the same Ctrl key ..)

**Comment by JohnLukeBentley** [comment]
> Alt+B is in fact the shortcut for the Boomarks menu on the menu bar.

... And Alt on its own opens the menu (if hidden) or moves the cursor to the menu, ready to shortcut to another choice. E.g. Alt+T+O opens Options, from the Tools menu. 

> Anything against Ctrl+X ?

Yes. As you'll recall once reminded: that's the universal Cut command. If I intend to Cut something with that shortcut and you intercept it and open BSP2 ... that's not going to work.

How about Ctrl+Alt+B? (Ctrl+Shift+B opens the native bookmark manager, not in the sidebar but as full window).

**Comment by aaFn** [comment]
So bad news: Ctrl+Alt+something is not supported:

> Error processing commands._execute_sidebar_action.suggested_key.default: Value "Ctrl+Alt+B" must either: match the pattern /^\s*(Alt|Ctrl|Command|MacCtrl)\s*\+\s*(Shift\s*\+\s*)?([A-Z0-9]|Comma|Period|Home|End|PageUp|PageDown|Space|Insert|Delete|Up|Down|Left|Right)\s*$/, match the pattern /^\s*((Alt|Ctrl|Command|MacCtrl)\s*\+\s*)?(Shift\s*\+\s*)?(F[1-9]|F1[0-2])\s*$/, or match the pattern /^(MediaNextTrack|MediaPlayPause|MediaPrevTrack|MediaStop)$/

Alt+Shift+something would be possible .. however both Alt+B and Alt+Shift+B open the Bookmark menu. As a matter of fact, only in english .. for another language where the word for Bookmark is not starting by a B, this is working. So need to avoid anything starting by Alt then if I want to be working with all languages .. :-(
And also need to avoid Shift+.. since this is very common in typing text ..

Therefore I guess I need to find something not already used in:
- Ctrl+..
- Ctrl+Shift+..

Ctrl+Q seems to fit in such a hole ..
Also Ctrl+F1 or Ctrl+F2 ..

**Comment by JohnLukeBentley** [comment]
Therefore it seems like any mnemonic combination is denied us. 

Ctrl+Q, Ctrl+F1 and Ctrl+F2 are not executing anything at my end at the moment. They don't trigger anything either native nor from the set of add-ons I have (which are probably at least slightly different from the set you have). So I can confirm those three options fit a hole here too. 

Ctrl+Q would, among the non-mnemonic options, seem better than Ctrl+F1 or Ctrl+F2, since you don't have to use two hands for Ctrl+Q.

**Comment by aaFn** [comment]
Ok, go for Ctrl+Q in 2.0.3.
Thanks for the continued feedback :-)

**Comment by aaFn** [comment]
Update:

In Linux, or at least in my Void Linux VM, Ctrl-Q is used by FF .. it closes the browser :-(
However, Ctrl+Shift+B seems free there, because the "All bookmarks" library appears to be tied to Ctrl+Shift+O (go figure ..)
@NicolasWeb, do you confirm ?
So setting Ctrl+Shift+B in Linux, and Ctrl+Q in all other platforms for now ..

**Comment by aaFn** [comment]
@JohnLukeBentley, @NicolasWeb, does 2.0.3 resolve the issue ? Let me know if ok to close it.

**Comment by JohnLukeBentley** [comment]
Yes, Ctrl+Q works fine here on Windows 10 pro 64bit. Terrific!

**Comment by NicolasWeb** [comment]
I wouldn't had chosen Ctrl+Q, as:
- Not all keybaords are azerty ;-) depending on locale...
- Cmd+Q close the app too on macOS and all Linux/Windows shortcuts translate Cmd to Ctrl. So when switching platform you end up closing the browser each time you try to bookmark....
- mentally it's far from a reflex to associate Ctrl+Q with Opening the bookmark pane for this addon... and any other exotic keyboard shortcut for others installed addons

I would had chosen a:
- consistent shortcut across platorfm
- semantic shortcut. Something+B.

To me Ctrl+Shift+B was a good choice.

That said, on Linux:
- the shortcut works fine- 
- however, it is not displayed in gray in the switch-panel menu, like for others and on macOS

**Comment by JohnLukeBentley** [comment]
> Linux/Windows shortcuts translate Cmd to Ctrl.

Not here on my Windows. Windows Key + Q opens Windows Search, rather than translates this to Ctrl + Q.

> To me Ctrl+Shift+B was a good choice.

But ...

> Ctrl+Shift+B opens the native bookmark manager, not in the sidebar but as full window).

...

**Comment by NicolasWeb** [comment]
> Windows Key + Q
To me Windows key do not mind map Cmd (or any other key) while switching OS. The only thing is it's just not far from the options keys on keyboards... and related to OS action.
BTW nice catch for this exotic one ! ;-)

**Comment by JohnLukeBentley** [comment]
I might not quite be following ...

> To me Windows key do not mind map Cmd (or any other key) while switching OS.

Then which key, when using a keyboard attached to a Windows machine, did you mean by "Cmd" in ...
> Linux/Windows shortcuts translate Cmd to Ctrl.

?

> The only thing is it's just not far from the options keys on keyboards... and related to OS action.

Well it, the Windows Key, is adjacent to the Alt key on a conventional keyboard (i.e. one into which Microsoft has asserted its dominance). And as far as I can tell the Alt Key is functionally equivalent to the "Options" key in the Mac world

See https://cdn2.macworld.co.uk/cmsdata/features/3462401/Mac_keyboard_800home.jpg and https://en.wikipedia.org/wiki/Option_key
> The Option key is a modifier key (ALT) present on Apple keyboards.

If you are intending to express ... switching between OSs (Windows and Mac) and relying on shortcuts that include the Alt/Option key or Windows/Command key becomes fraught as those keys swap positions ... then that would seem right. Commiserations for that (I'm lucky enough to be able to stick to one desktop OS). 

I'm not sure however, one could avoid that problem in general, given that so useful many shortcuts depend on the Alt key (in the Windows context).

But if you could find a keyboard combination that is the same in all OS, and isn't already taken, I think that would be very welcome. It would to compete, however, with one handed convenience of Ctrl + Q on a  QWERTY, AZERTY, QWERTZ, Dvorak, Colemak, and Workman layouts ;)   https://en.wikipedia.org/wiki/Keyboard_layout#QWERTY-based_Latin-script_keyboard_layouts

**Comment by NicolasWeb** [comment]
> Linux/Windows shortcuts translate Cmd to Ctrl.

Yes, that's what I mean (like Cmd+X -> Ctrl+X) .

**Comment by aaFn** [comment]
Hello @NicolasWeb , so to summarize:
- Ctrl+Shit+B is not available on Windows, it's already taken
- Same for all xx+B combinations we can use
- I didn't find any easy to use or meaningful common combinationn for all platforms
- It is free in Linux
- Don't know about MacOS ..; if somebody can tell ?

Therefore, for now:
- Ctrl+Shit+B in Linux
- Ctrl+Q in all others ... until somebody can tell me if Cmd+Shift+B or something in B in free for Mac ..

Last, the shortcut is indeed not displayed in the sidebar switch-panel menu. Apparently this is the same for all sidebar add-ons I could test, and I didn't find a way to make it display .. FF simply doesn't appear to make that available.

Closing the issue then since it works for all. If we find a better combination, let's open a new one :-)
Thank you.

**Comment by NicolasWeb** [comment]
> Ctrl+Q in all others ... until somebody can tell me if Cmd+Shift+B or something in B is free for Mac ...

It opens the Library window. BTW, others option-key+B (Cmd, alt, ctrl, shift) seems free, as any other combination with 2/3 keys is free on Mac. ie. Cmd+B and Shift+Cmb+B are taken.

**Comment by aaFn** [comment]
@NicolasWeb, ok, if you have a particular suggestion which is guaranteed free for Mac, and which matches the pattern below, let me know.

```
pattern = /^\s*(Alt|Ctrl|Command|MacCtrl)\s*+\s*(Shift\s*+\s*)?([A-Z0-9]|Comma|Period|Home|End|PageUp|PageDown|Space|Insert|Delete|Up|Down|Left|Right)\s*$/
or pattern = /^\s*((Alt|Ctrl|Command|MacCtrl)\s*+\s*)?(Shift\s*+\s*)?(F[1-9]|F1[0-2])\s*$/
````

**Comment by NicolasWeb** [comment]
> In Linux, or at least in my Void Linux VM, Ctrl-Q is used by FF .. it closes the browser :-(
In mac OS too, like any app on this OS. So SBP2 shortcut should be changed, for sure.

Seems like there are a lot of enhancement request in core Firefox about shortcuts [bug 1426958 (approved, no staff working on it)](https://bugzil.la/1426958), [bug 1215061](https://bugzil.la/1215061), [bug 1410509](https://bugzil.la/1410509), [bug 1303384](https://bugzil.la/1303384)

For now, I suggest to use alt+B or Cmd+alt+B
(as native bookmarks sidebar opens with Cmd+B)

**Comment by JohnLukeBentley** [comment]
As discussed above, in Windows FF, alt+b, opens the bookmarks menu (any alt will open the menu).

By "Cmd" do you mean, in a windows context, the window key or the ctrl key?

**Comment by aaFn** [comment]
So:
- Linux = Ctrl+Shift+B
- MAC = Alt+B (Cmd+Alt+B doesn't match with the pattern above .. it will get rejected)
- All other, including Windows = Ctrl+Q

A good example of how unified all this is on cross platform software products ... lol (not their fault I believe, they probably rely on local libraries for compatiblity and smiplicity, and none are converged ..)

**Comment by aaFn** [comment]
@NicolasWeb, set MacOS to Alt+B in 2.0.5. Let me know if not good. Thank you.

**Comment by aaFn** [comment]
FF63 enables more combinations ... So in BSP2 2.0.46, I have added in the options page an option to dynamically change the shortcut, so that the user can define what he/she wants (and can reset it to default if needed).

Cf. #74

**Comment by Muddy7** [comment]
> To me Ctrl+Shift+B was a good choice.

Ctrl+Shift+B in Firefox opens up the Bookmarks Backup and Restore Windows—a very useful shortcut key!

**Comment by aaFn** [comment]
Not on Linux ...
FF key combinations are not constant across platforms .. this is making that difficult to pick one choice across all ..

**Comment by Muddy7** [comment]
Right! Being a humble Windows only user, I didn't know that. Indeed, this complicates things considerably :-/
