### ISSUE TITLE
(v2.0.22) Persistent window display in left pane

### ISSUE THREAD

**Issue by gejmis** [aaFn/Bookmark-search-plus-2#42]
Under FF 60.0.1, the following window displays inside the left pane.

![image](https://user-images.githubusercontent.com/39999516/41049902-f4e45a76-697f-11e8-9fd8-dac15eb02a2b.png)

Operation is OK apart from the window's persistence. Tested on two OSs, with both a light user profile (no active add-ons, less than ten bookmarks) as well as standard ones with 2000+ bookmarks and 20 add-ons.

**Comment by aaFn** [comment]
Hello @gejmis, indeed this is an erroneous leftover of a temporary version made to investigate #40.
Sorry for that.
Corrected in 2.0.23 which is out now just to remove that.

Thank you for notifying me.
