### ISSUE TITLE
Add key navigation in context menus and in bookmark panes

### ISSUE THREAD

**Issue by aaFn** [aaFn/Bookmark-search-plus-2#46]
Feature to add = be able to navigate using arrow keys and home/end .. etc ... in bookmark panes (tree view and results view), and in context menus.

**Comment by bzip2** [comment]
Hi. Now that I've reached the promised land and discovered your add-on, I expect to be deleting lots of bookmarks. It would be great if hotkeys worked in the context menu (e.g. D for delete), and it sounds like this issue covers it but I wasn't sure.

**Comment by aaFn** [comment]
Hello @bzip2 , yes that is the place.
Progressing by steps on this one .. Keyboard navigation was added in 2.0.45, next step will be context menus indeed :-)

**Comment by aaFn** [comment]
This is now getting easier with integrated FF context menus that I implemented with 2.0.69, which contain native navigation with keyboard.
I will add key shortcuts to context menus in 2.0.70 (only for FF >= 64).

**Comment by aaFn** [comment]
2.0.70 is out, with accelerator keys inside the menus for FF >= 64.
Closing the issue as done.

Thank you, aaFn.

**Comment by N3C2L** [comment]
@aaFn 

Thanks for giving us shortcuts for navigating.
May I ask you for some improvements here?

It would be beneficial to have 3 more shortcuts:

A shortcut for jumping to the search results (if the search input field is currently focused).
A shortcut for jumping to the search input field on top (if a search result is focused).
By pressing the enter key for opening the the active focused item in a new tab.

I'd be happy if you could implement this.
This would improve the search experience for keyboard users a lot.

**Comment by aaFn** [comment]
Hello @N3C2L

Some of them already exist;
- A shortcut for jumping to the search results (if the search input field is currently focused) -> press Enter
- A shortcut for jumping to the search input field on top (if a search result is focused) -> doesn't exist today
- By pressing the enter key for opening the active focused item in a new tab -> press Alt+Enter to open in same tab, Ctrl+Enter to open in new tab, and Shift+Enter to open in a new Window.

See https://github.com/aaFn/Bookmark-search-plus-2/wiki/Keyboard-shortcuts

**Comment by N3C2L** [comment]
Thank you, I didn't know these enter key shortcuts.
For quick searches I'd love to have the bookmark search plus 2 interface to be opened in a popup instead of a tab/sidebar. Do you think it's much work for implementing your addon to be opened as a popup?

**Comment by N3C2L** [comment]
Just for clarification, I'm not a dev, and I don't know the answer to my question. I am just curious if a popup version of your addon could be implemented in a future update some day? I'd be happy about that. There would be some advantages, like not to be forced to switch to the bookmark tab or force to change the sidebar content addon (I have the grasshopper plugin, a tab manager inside my sidebar).

**Comment by aaFn** [comment]
Hello, I see I forgot to answer on this one.

Popup is not a classical form for add-ons.
The best way to do what you want / simulate a popup is simply to open a second FF window (typically Ctrl+N), and then to open BSP2 inside it as a tab.
