### ISSUE TITLE
Feature request: option to set the font size of the bookmarks

### ISSUE THREAD

**Issue by Asteriod1** [aaFn/Bookmark-search-plus-2#56]
The default font size for the bookmarks of 12px on linux is a bit too small for me.
Is there a possibility to increase it ?
Or better: could you add an option to set the bookmark font size ? 
Thanks.

**Comment by aaFn** [comment]
Hello @Asteriod1, I guess I can indeed add an option to override the defaults with an <input type="number"> control https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
which would let you try different sizes from the options page.

I will see if I can add it in 2.0.35.

**Comment by aaFn** [comment]
Hell @Asteriod1, I added the function today with 2.0.35. Hope this suits your need, now you can change to a value between 10 to 16 px (default remains 12 px).
Let me know if any problem, else I will close the issue.

Thanks; aaFn.

**Comment by Asteriod1** [comment]
Hello @aaFn, I've just installed 2.0.35. 16 px work well for me. Thanks a lot for the quick implementation.

Asteriod1

**Comment by aaFn** [comment]
Welcome. Thank you for the quick feedback
