### ISSUE TITLE
Bug? When clicking "Properties" over a bookmark whose name contains an ampersand.

### ISSUE THREAD

**Issue by Blengurp** [aaFn/Bookmark-search-plus-2#58]
Hello @aaFn,

First of all, thank you very much for your excellent extension. It's so useful that I don't know what would I do without it.

While managing my bookmarks with Bookmark search plus 2, I've noticed that every time I do right click and then "Properties" over a bookmark whose name contains one or more ampersands, in the popup menu the name string gets truncated right before the first ampersand position and address field shows "undefined" and a red border. And even if I click on "cancel" to discard changes, name string gets truncated anyway.

For instance:
Let's say I have in my bookmarks the URL "https://www.jnj.com/"
whose name is "Johnson & Johnson Homepage | Johnson & Johnson"
Now, if I do left click over it and then click on "Properties", this is what I get (without quotes):
Name: "Johnson "
Address: "undefined"
And even if I click cancel, name changes to "Johnson ".

Please, test it and see if this can be fixed. Again, thank you very much. Keep up the good work!

**Comment by aaFn** [comment]
Hello @Blengurp , indeed, due to poor dialog mechanisms between the sidebar and a popup it opens, I used the URL convention of passing parameters with an "&" .. and overlooked that the main name could contain "" itself.

Well caught .. I will look at correcting this week-end, should be 2.0.39 ...

Thanks, aaFn.

**Comment by aaFn** [comment]
Hi @Blengurp, bug corrected in 2.0.39 which is out now.
Let me know if all is ok or not, and then we can close that issue.

Thanks, aaFn.

**Comment by Blengurp** [comment]
Hi @aaFn, yesss!! a fast test shows that this bug has been totally ironed out in your last version.

Thank you for your fast answer and solution. And again, thank you very much for your wonderful extension! Of course, I am going to close this issue.

Have a nice day!
