### ISSUE TITLE
[Feature Request] - Dragging-Copy (<CTRL>+Drag) of bookmarks within bookmarks folders

### ISSUE THREAD

**Issue by v00p** [aaFn/Bookmark-search-plus-2#63]
Just like the built-in FF Bookmark manager allows us to.
Copying bookmark to another bookmark folder is possible through holding <CTRL> key and mouse-dragging the bookmark item into the target folder.

Currently can't be done within  this extensions

**Comment by aaFn** [comment]
Good point.
I added the feature in 2.0.40 which will be out tonight.
Let me know if any problem or if ok.

Thanks, aaFn.

**Comment by aaFn** [comment]
Closed with 2.0.40
