### ISSUE TITLE
Stuck "Prepare tree display..."

### ISSUE THREAD

**Issue by Dimas-sc** [aaFn/Bookmark-search-plus-2#65]
When I open the sidebar a "Prepare tree display..." message appear and never ends. I can search but I can't locate results in the tree.

Firefox 64.0b9
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by aaFn** [comment]
Hello @Dimas-sc, ok it might be modified functions coming in FF 64 like
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/buildID
or https://github.com/tc39/proposal-well-formed-stringify
or a bug.

Could you do the following:
1. Go to the options panel and activate traces
2. Go to the `about:addons` page and deactivate BSP2
3. Open the browser console = Ctrl + Shift + J
4. Press the tray Icon in the top left of the console to clear its contents
5. Return to the `about:addons` page and activate BSP2
6. If the sidebar does not open, open it
7. And when things are stuck on "Prepare tree display...":
   - go into the trace textarea, copy its contents and paste it here
   - go to the browser console, copy its contents, and paste it here

Let's see what you get.
I will see if I can easily put my hand on FF64 on my side and install it to verify anything which could be obvious.

Thanks, aaFn.

**Comment by Dimas-sc** [comment]
This was happening in two differents PCs. I tried your instructions but after disabling and enabling again BSP2 it was working again. I tried the same in the second PC, where I checked that the bug exists, and after enabling it again it worked too. So it seems now to be fixed :-)

**Comment by aaFn** [comment]
Strange .. if it re-happens, I will need to find a way to get some traces without having you deactivate / reactivate. This is certainly not the good procedure to resolve a bug :-)

I will leave the issue open for 1 more week, and if nothing in 1 week, I'll close it as is, we'll see if it reoccurs later.

Thank you, aaFn.

**Comment by Dimas-sc** [comment]
Before disabling/enabling it in the second PC I looked at the browser console when I enabled the sidebar and "Prepare tree display..." msg appeared but I didn't see error messages. Well, I saw some recurring errors but I suppose that are caused but other addons...

If it happens again I will tell you. Thx!

**Comment by aaFn** [comment]
Ok, I reviewed the code and found a few cases of "silent errors", where the code was trapping and nothing was shown in the browser console. This is linked to nested promises with the outer try{} or .then() having a catch() statement, but not the inner ones.
A javascript peculiarity, at least on FF, that I didn't know about.

I am now catching them individually to make sure they show, this will be in 2.0.42.
Hopefully, this will get your trap if it comes again.

**Comment by aaFn** [comment]
Looks like we're good, so closing. Let me know if not.

Thanks, aaFn.
