### ISSUE TITLE
Feature Request: Add "Open in Bookmarks Editor" to options for a selected bookmark.

### ISSUE THREAD

**Issue by jnoa** [aaFn/Bookmark-search-plus-2#68]

**Comment by jnoa** [comment]
Option to edit a selected bookmark's property is often not enough. If possible, please add "Open in Bookmarks Editor" option that will open the standard Bookmarks Editor window so that it is already positioned at the selected bookmark instance. This will allow users to fully manipulate the properties, ordering, position within folder, and parent folder location of the selected bookmark.

MANY THANKS FOR THE WORK DONE SO FAR!!! THIS PLUGIN IS A GREAT HELP THAT PARTIALLY COMPENSATES FOR THE DEFUNCT OLD "BOOKMARKS EDITOR" PLUGIN THAT  ADDED A "PARENT FOLDER" COLUMN TO THE "BOOKMARKS EDITOR" SEARCH RESULT LIST.

**Comment by aaFn** [comment]
Still not possible to call/open FF features from an add-on, so closing that.
Let's see if one day FF gives us more control ...
