### ISSUE TITLE
Mouse clicks and modifiers summary table (as of 2.0.42 )

### ISSUE THREAD

**Issue by chr7** [aaFn/Bookmark-search-plus-2#69]
Version 2.0.43
Setting "Search results bookmark behaviour": Advanced

According to the table [Mouse clicks and modifiers summary table (as of 2.0.42 )](https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.42-)), searching for a bookmark and left clicking the blank part while holding down the Ctrl key at the same time should "select" (=open the location of the bookmark in the tree?) - but nothing happens (apart from the search and result pane being closed).

Clicking the image or text part, the bookmark is opened in a new tab but not selected in the tree.

Is the description wrong? Or is a bug of the plugin?

**Comment by aaFn** [comment]
Hello @chr7, "select" means that the cursor is set on the item, and the item is then subject to any keyboard action on it (like Del, Enter, arrow up, down ... which will move the cursor by 1 step from it to the previous or next one).

I updated the page to add a legend, to be explicit.

**Comment by chr7** [comment]
I can't confirm the "select" feature: no keyboard action has any effect on the item.

**Comment by aaFn** [comment]
In the search panel, not yet indeed, as I didn't implement them yet :-)
That should come soon .. this is already active in the bookmark pane.

**Comment by aaFn** [comment]
2.0.45 added key navigation in the Search result panel, and 2.0.46 added selection as per latest summary table https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.46-)

Closing the issue now, thanks aaFn.

**Comment by chr7** [comment]
Works now, thanks :-)
