### ISSUE TITLE
Feature Request: right click and open all links in a folder

### ISSUE THREAD

**Issue by shoulders** [aaFn/Bookmark-search-plus-2#70]
In the firefox bookmark manager you can right click on a folder and select **'Open All in Tabs'**

![image](https://user-images.githubusercontent.com/319997/49510921-9d665880-f881-11e8-9c57-f2bd7c288933.png)
and I use this to open all of my links and then i can sort throught them and remove the ones I dont need etc...

Can you add this 'right click' option to both the search pane and the bookmarks tree.

The firefox command only opens the immediate child links of that folder.

tar

**Comment by Muddy7** [comment]
I support this Feature Request. For my personal use, it is the most important feature currently missing.

**Comment by JohnLukeBentley** [comment]
Yeah this is would be good to have. The "Open All in Tabs" is available in the native sidebar, not just the full native bookmark manager.

**Comment by JohnLukeBentley** [comment]
I'll add that in the native sidebar "Open All in Tabs" works either when:

* A folder is selected (and so all the children will be opened); or
* Multiple bookmarks are selected (something which, if implemented in BSP2, would require #29 to be implemented first).

I thing it would be good to implement both behaviours.

**Comment by aaFn** [comment]
Hi there, I have updates pending for #100, once I have finished on that (2.0.68), I will look at this one as candidate for 2.0.69.

Thanks, aaFn.

**Comment by JohnLukeBentley** [comment]
Thanks aaFn!

**Comment by JohnLukeBentley** [comment]
... although, for me, #31 is a higher priority.

**Comment by aaFn** [comment]
Hello, this is in 2.0.69.
Let me know if any trouble.

Happy new year, aaFn.

**Comment by shoulders** [comment]
Thanks for this new feature, and I hope the new year goes well for you.  😃

**Comment by Muddy7** [comment]
Brilliant!!

 Adding _'Open all in new tabs'_ to Context Menu actions and _'Properties'_ to Search Result Pane Context Menu actions were, if I remember, the main feature requests I was going to make when I found time to put pen to paper or, rather, fingers to keyboard ;-)

Many thanks!

**Comment by Muddy7** [comment]
I **_think_** (I don't currently take notes) the only other major feature I'd like yet to see is the Ctrl-Z (delete) / Ctrl-Y (undelete) one.

But as you said [here](https://github.com/aaFn/Bookmark-search-plus-2/issues/74#issuecomment-445996179), this is by no means an easy one to code—particularly given the fact that this (amazing) FF add-on has all been, and is being, created and developed by a one-man outfit.

**Comment by Muddy7** [comment]
I **_think_** (I don't currently take notes) the only other major feature I'd like yet to see is the Ctrl-Z (delete) / Ctrl-Y (undelete) one.

But as you said [here](https://github.com/aaFn/Bookmark-search-plus-2/issues/74#issuecomment-445996179), this is by no means an easy one to code—particularly given the fact that this (amazing) FF add-on has all been, and is being, created and developed by a one-man outfit. 

Btw I think the wording of this request should be nuanced a little bit:
"You already have a 'Delete' option in the Context Menu. It would be great to also add an 'Undelete' option to that Context Menu." (added [here](https://github.com/aaFn/Bookmark-search-plus-2/issues/75#issuecomment-570150738))

**Comment by JohnLukeBentley** [comment]
Thanks @aaFn. "Open in all tabs" now works on a folder.

That leaves when ...

> Multiple bookmarks are selected (something which, if implemented in BSP2, would require #29 to be implemented first).

... assuming that is also desirable.

**Comment by aaFn** [comment]
Hello, yes, when multi-selection will be implemented, the "Open all in tabs" action will show and open as many tabs as bookmarks are selected, just like a folder.
I will handfle that as part of #29

**Comment by aaFn** [comment]
Closing this issue as done.
Thanks, aaFn.
