### ISSUE TITLE
feature request: remove the sidebar max width

### ISSUE THREAD

**Issue by shoulders** [aaFn/Bookmark-search-plus-2#71]
is it possible to remove the max-width so i can stretch the bookmarks sidebar wider to make managing bookmarks easier. Maybe 50% if you have to put a limit on it.

The max width that is present now is probably ok when you are using it to navigate the web but it is a little restrictive when trying to organise your bookmarks.

I am aware of the horizontal scroll bar at the bottom.

thanks

**Comment by aaFn** [comment]
Hello @shoulders, apparently this is nothing we can do about, as this is imposed by FF (and I didn't put any limit on it in the code).
As an illustration, the native bookmark sidebar appears to suffer from the same limitation.

Let me know if you see something that I am missing.

**Comment by aaFn** [comment]
Closing as there is nothing I can do with it from inside the WebExtension API, and the limit is imposed by FF itself.

**Comment by aaFn** [comment]
The main page is here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions
but maybe it would be opportune to create a feature demand if there is none already existing ? https://bugzilla.mozilla.org/

**Comment by v00p** [comment]
@shoulders 
A workaround (open the extension on main page rather than sidebar), is to launch the extension from the address bar instead, like so: `moz-extension://[your extension's internal UUID]/sidebar/panel.html`

You could create a desktop shortcut to launch it from there as well, using the -url switch: `firefox.exe -url moz-extension://[your.extension's.internal.UUID]/sidebar/panel.html`

Find your extension's UUID at: `about:debugging`

**Comment by aaFn** [comment]
Another way, built-in, that I am using for my own debug :-)

- Set "Activate traces" on, in the Options page
- When you want to see the sidebar in a full main page, do `Alt+left click` on a protected special item in the sidebar, like on "Most visited" folder, or "Recent tags", or "Recently bookmarked"

This will open the BSP2 sidebar on the main page.

**Comment by shoulders** [comment]
@aaFn I cannot find "activate traces" in options.m Do I need to enable developer options or something like that?

**Comment by aaFn** [comment]
On second thought, given the number of people asking for a wider view, this manipulation is too complex and hidden for being practical.

So I am adding as part of 2.0.54 a context menu on the magnifier glass of the search box, and on the blank parts of the sidebar body, which will contain for now one default entry = `Open BSP2 in new tab`.

This will make it easy for everybody to get access to a full page view of the bookmark tree, and to run BSP2 in a wide window.

**Comment by Twistyness** [comment]
I like to give first impressions before I forget them. It took me forever to find this **wonderful new full-screen view** I right-clicked everywhere. I looked up "magnifying glass" in Firefox options, and as an addon. 

I had no idea you were talking about the search icon. My instructions came from your replies to my comments elsewhere, and I think from instructions on the addon page:
https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2 

I suggest a heading **"Full screen view"** in those instructions. 

I suggest putting the "**Open BSP2 in new full-screen tab**" option in the main menu of the addon. That would be more intuitive.

**Comment by shoulders** [comment]
Great feature but very hidden. Maybe add a tooltip

**Comment by aaFn** [comment]
As part of #90, I am going to rework a bit things on the Magnifier glass icon to make it a button for a drop down list, or something alike, so that should make it more obvious.

As soon as I have enough time to concentrate on that one .. :-)
