### ISSUE TITLE
Feature Request: Collapse grandparent/parent/child folder path to shown bookmark using left arrow key

### ISSUE THREAD

**Issue by Muddy7** [aaFn/Bookmark-search-plus-2#73]
In the Firefox Bookmarks sidepane, I can easily collapse the opened grandparent/parent/child folder path of a selected bookmark by repeat-clicking the left arrow key. This performs the actions of go to folder/close folder/go to parent folder/close parent folder/go to grandparent folder/close grandparent folder etc. Equally I can also easily use the right arrow and the down arrow to open a folder and then its child folder etc. and then to navigate the contents of that folder. These actions make it relatively effortless for me to navigate Firefox Bookmarks. Unfortunately, this does not seem to be possible in BSP2 (maybe because of coding limitations in FF Quantum, in which case this Feature Request is in vain).

At the moment, after just 2 days of using BSP2 (which I love!), this is the one key feature that I miss. This means that after searching and going to a searched bookmark, the only quick way I can find to collapse the folder path is by closing and reopening BSP2. A little more cumbersome for me than some, as I am already using the assigned open/close BSP2 hotkey Ctrl+Q in the particular setup of my devices.

If this Feature Request is not possible or is deemed too time-consuming regarding coding to be viable, an alternative solution might be to add to the Options page the possibility of manually setting the open/close BSP2 hotkey to Ctrl+_another key_.

**Comment by aaFn** [comment]
Hello @Muddy7 , ok done, this will be in 2.0.45, out tomorrow evening latest.

**Comment by Muddy7** [comment]
> 
> 
> Hello @Muddy7 , ok done, this will be in 2.0.45, out tomorrow evening latest.

Brilliant! Thanks a million!!

**Comment by Muddy7** [comment]
...tho' I see now I can collapse the path by simply pressing Esc. All the same, this will certainly be a welcome enhancement, making it easier to use just BSP2 without toggling so often between BSP2 and FF bookmarks.

A welcome enhancement :-))

**Comment by aaFn** [comment]
> ...tho' I see now I can collapse the path by simply pressing Esc

Not sure what you mean by that ? Esc does nothing as I can see on the native Bookmark sidebar (except close the context menu). Or what am I missing ?

**Comment by Muddy7** [comment]
Not on the native bookmark sidebar but on yours (BSP2).

**Comment by aaFn** [comment]
Thank you, I registered there if anybody has something to say (although it is best to come here on GitHub).

I didn't know about Webroot, I'll keep an eye on it, even if I do believe that without a firewall and an HIPS, an antivirus is only a half solution for controlling what is going on on our computer(s) ..

Anyway, this is a truly interesting community. I like a lot the post about password constraints https://www.webroot.com/blog/2018/11/05/password-constraints-unintended-security-consequences/ .. this is so true !!

**Comment by Muddy7** [comment]
It does have a firewall (it uses Windows for its inbound firewall as it believes it can't beat it, and it has its own outbound firewall); and, as I understand it (I am admittedly no IT expert :-(  ), it does have its own kind of HIPS, Webroot being at its heart a behaviour blocker. For what it's worth, [here](https://www.wilderssecurity.com/threads/webroot-secureanywhere-discussion-update-thread.364655/page-155#post-2790747) is my personal story with Webroot.

What is now Webroot SecureAnywhere began as an innovative approach to AV technology by a small British firm, Prevx, in the early early noughties which was acquired by Webroot in late 2010.

**Comment by Muddy7** [comment]
> 
> 
> 2.0.45 is out ... let me know if this is working ok or if something is wrong.
> I also added keyboard navigation in the search result pane, to continue o,n #46

I like it!

And you've thrown in the keyboard navigation to _open_ folders and bookmarks in the bookmark folder tree as well.

One thing: in the present BSP2 version, you have to click on the bookmark in the bookmark tree for the left arrow function to work—which means opening the bookmark in an existing tab. It'd be nice if this (excellent) function could work without having to click on the bookmark and therefore having to open it on an existing tab.

Btw talk about responsiveness! I make this request this morning. Just ten hours later, you have both written the code AND released it to consumer version. Impressive!!

Thanks!!!

PS. Btw I had read that article by Randy about passwords and 'fraid it goes way above my small, feeble brain :-((   I did like the "cats and hippos are friends!" password idea though.

**Comment by aaFn** [comment]
As a matter of fact, much like in the native bookmark sidebar, if you click on the blank part of the bookmark item at left of it in the pane, nothing happens apart from selecting it.

And differently from the native bookmark sidebar, you will notice that the mouse pointer is changing to indicate that:
- just a classic arrow pointer when there will be no action apart from select
- a finger pointer when the click will trigger an action (it is always that pointer in the native sidebar)

That should do what you want I believe.

**Comment by Muddy7** [comment]
A bit confused by the last part of what you say.

So what I've discovered from your above post:
In the BSP2 bookmark pane, to change the active folder (colour=blue when active while grey when inactive), I must click on the arrow/pointer to the left of the folder. The colour turns to blue and then I can navigate from there.

Thanks! That's a great help :-))

In Firefox (and, _I think_, other browsers but I'm not sure and haven't checked), I can right-click on a bookmark and then press Esc, and that makes that bookmark the actively selected bookmark (colour=dark blue). I can find no way of doing something similar in BSP2.

But I'm afraid I'm a bit thick :-(( and don't understand when you say in the last part of your post:




> And differently from the native bookmark sidebar, you will notice that the mouse pointer is changing to indicate that:
> 
>     * just a classic arrow pointer when there will be no action apart from select
> 
>     * a finger pointer when the click will trigger an action (it is always that pointer in the native sidebar)

Maybe you can explain in other words?? When you have time, of course!

**Comment by aaFn** [comment]
On right click, that is correct, that does not do any select, as per
https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.42-)

I guess I could change it if this is confusing. Let me know.

---------------------------------------

On the second part of your post, you can observe that the mouse pointer is changing to a finger pointer when hovering on the favicon and on the text of bookmarks, to show that the default action will be triggered if we click. Else it is an arrow pointer to show that only a select will occur.
This mouse hovering change is happening on bookmarks only, not on folders. And now that I think about it, I believe this is illogical and I need to change that to align, and to have the same mouse hovering pointer behavior.

In the native bookmark sidebar, this is always a finger pointer when hovering on the bookmark items, not indicating that a different action will occur when you click on blank or when you click on the favicon+text, which is not very indicative of what will happen.

Is that clearer ?

**Comment by Muddy7** [comment]
Wow! That's much clearer for dull dudes like me LOL!!! And it's perfectly logical.

However, I feel that it is nevertheless not intuitive as "intuitive" should be translated  to "intuitive for creatures of habit". Creatures of habit as we are, we get used to Firefox's (arguably less logical) protocols (is that the right word??) for mouse and pointer actions, and when we encounter a different set of "protocols", we tend to get confused. Unfortunately.

For me, I now understand perfectly. The question is: what about others who haven't had that explained to them? It's a debatable point, given the elegant and logical way your mouse and pointer protocols (again that word :-/ I'm sure it's the wrong word but I can't find a better one for the time being) work.

Food for thought...

Thanks so much for taking the time to explain to me. And your weekend too!

**Comment by aaFn** [comment]
I like your choice of "protocol" word, looks good to me, so I'll take it :-)

Ok, given this is a very fine visual distinction, I believe most users do not notice. And I do find the FF protocol confusing for those who pay attention to such details, this is why I decided for something more logical:
- those not paying attention won't notice
- those paying attention will get a better experience

To your point on "intuitive for creatures of habit", this is a good point .. and that tells me I should modify the right click behavior to also do "select", like in FF native sidebar by the way, so that you retrieve your habit of right click and pressing Esc. So I'll do that for the next release.

Thank you, aaFn.

**Comment by Muddy7** [comment]
So what I requested (this Feature Request) it appears your Bookmark Side Pane App already did, i.e. collapse the folder path to the _bookmark-searched-for-&-then-shown_ by repeat-clicking the left arrow button. What you have in fact done—and this is very interesting—is force the tree structure to remain UNcollapsed when the left arrow is repeat-clicked so we are "walked up" the tree structure while the path/tree structure remains open. We can then close the path in the same way as previously: by simply clicking the cross at the right of the search window.

Not what I asked for because you already had what I asked for. Something different but **very** interesting. Makes it easier to see and trace the path of the selected bookmark!

Thanks again!

**Comment by Muddy7** [comment]
Our posts crossed! And I like your reaction to my post. You seem to be a very open person (more open, I fear, than I am :-((  ). Listening to other people's observations and taking them in to further improve your ideas.

**Comment by aaFn** [comment]
You are welcome. Yes there is not one way of doing things, people have different habits and likeliness as you point out, and the goal is to make life easier, which can only happen by listening I guess ;-)

You pointed out very good things on the left and right keys behavior of the native bookmark sidebar which I had missed, and that is really an improvement because as you say that allows an easy "walk up" the tree structure. Thanks for that.

-----------------------------------------
A little more details as I see you're getting around it :-)

About showing and highlighting something from search, yes you are getting on another subtlety for fine eyes :-)
- If the shown bookmark item is under closed folders, these folders are **visually** expanded _but they remain in closed state_ .. look at the twisties along the path, the closed folders remain with "closed" twisties ... And this remains so unless you voluntarily twist them differently.
- This is so that anything you let "closed" or set to "closed" during a search will remain closed, and their contents will come back to invisible, when you quit the search (= hit Esc, or click the cross in the search box, both work).
- So if you twist nothing differntly during a search, then Esc / click on cross will just restore things as they were before the search + show, not disturbing anything.
- And if you twist something differently, this is on purpose, so BSP2 will keep your will as an override.

Subtle net is that when doing left arrow on a search, if it is on a "closed folder which was visually expanded", it will remain closed .. and won't change the visual expansion as you noticed.

**Comment by Muddy7** [comment]
Very clever ;-)

**Comment by aaFn** [comment]
All that is discussed here is now implemented in 2.0.45 and 2.0.46, I am closing the  issue.

Thanks;, aaFn.
