### ISSUE TITLE
Assorted Feature Requests

### ISSUE THREAD

**Issue by Muddy7** [aaFn/Bookmark-search-plus-2#74]
I don't know if it's OK to introduce several feature requests in one thread but, hoping it is, here goes:

1. It would be good to make Ctrl+Q user-configurable in the settings part of the Options page (I normally use Ctrl+Q for another app on my devices)
2. It would be nice if you could add the shortcut keys Ctrl+Z (for Undo) and Ctrl+Y (for Redo) to the keyboard options
3. It would be really neat if, in the Properties pop-up window from the Context Menu, you could add a field for path of bookmark or folder, e.g. _Bookmarks Toolbar > Home > Cooking > Recipes > Pasta > Spaghetti > Sauces_ (that way, it would be **_SO_** dead-simple for simple dudes like me to see, remember and re-memorise the folder path ;-D )

Thanks!

**Comment by aaFn** [comment]
Hello @Muddy7 , no problem to put several things together. Now:

1. Ok, I'll see what can be done with https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands
Just mind that many combinations are already taken natively by FF menus and features, that the add-on has no way to know that (it changes depending on the OS), and trying to override them may lead to unpredictible behavior depending on the combination you chose .. :-)  (not counting about other add-ons competing on the same shortcut of course ..)
2. Unfortunately this is not something easy to do. The FF bookmarks API is not meant for that. In particular, a delete is really deleting things, there is no way to come back in the past ... undoing a delete could only mean "recreate", however there are attributes not accessible by the API like Tags, Description .. etc ... which would be lost as these are not exposed through the FF API and an add-on has no way to know about them. Another way could be to delay the delete, but then in the real native bookmark sidebar and manager, it would still show ... This requires careful thinking.
So for now I will defer this one, and it would be best to list it independently in another issue to not lose it.
3. Ok, good idea.

**Comment by Muddy7** [comment]
> Hello @Muddy7 , no problem to put several things together.

Thanks for clearing that one up. And thanks for saying it's OK :-))

> 1. Ok, I'll see what can be done with https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands
Just mind that many combinations are already taken natively by FF menus

I'm aware of the usual culprits like Ctrl+A,+C,+E,+F,+K,+T,+V,+X. Hope there aren't too many others :-(  And I take your point about possible unpredictable behaviour...

> 2. Unfortunately this is not something easy to do. The FF bookmarks API is not meant for that. 

That' funny. I've just tested using the Delete key in the resident FF Bookmark Sidebar to delete a bookmark and then pressing Ctrl+Z and it worked perfectly. Then I pressed Ctrl+Y and it deleted again. Ctrl+Z and I got it back again.

> 3. Ok, good idea.

Brilliant! Thanks!

**Comment by aaFn** [comment]
> That's funny. I've just tested using the Delete key in the resident FF Bookmark Sidebar to delete a bookmark and then pressing Ctrl+Z and it worked perfectly. Then I pressed Ctrl+Y and it deleted again. Ctrl+Z and I got it back again.

Yeah that is the problem, the native bookmark stuff has access to things not exposed to the API .. of which there is no undelete command on the API, and as I said, no access to Tags, Description, Keyword -> https://bugzilla.mozilla.org/show_bug.cgi?id=1225916

**Comment by Muddy7** [comment]
> Yeah that is the problem, the native bookmark stuff has access to things not exposed to the API

Yeah I wondered if that was so. So, as you say, I should make this a separate request so it's not forgotten. And even then it may prove too complicated coding-wise to be feasible for a one-man operation like this. Hoping that's not so, but realising it may well be :-/

Thanks!

**Comment by aaFn** [comment]
I got some ideas based on a trashbin approach, but as said this requires careful thinking of the diversse possible cases, so not something that would come with a snap of fingers :-)

**Comment by Muddy7** [comment]
Great!

**Comment by Muddy7** [comment]
Btw I added yesterday my support to Issue #70 as the Folder Context Menu Option _"Open All in Tabs"_ is the feature I most miss from the resident Bookmarks Sidebar. If I am not mistaken, it is the only operation I currently feel the need to toggle from BSP2 back to the resident Bookmarks Sidebar to use (which incidentally shows how good your Bookmarks Extension is :-))

**Comment by aaFn** [comment]
Both are now implemented in 2.0.46, let me know if ok.

**Comment by Muddy7** [comment]
Incredible! This morning (GMT+1=my time zone), in my hurry I hadn't noticed that you had not only implemented the issue in #73 (thank you!) but also issues 1 & 3 from this thread (issue 2 having been transferred to a new thread #75 as this requires further reflection by the developer before implementing—if feasible). I am truly impressed by the speed at which suggestions that are deemed acceptable are then implemented. Thanks!
(For me, this multi-issue is now closed but I shall leave that to the discretion of the developer.)

**Comment by aaFn** [comment]
Maybe "Folder path" to be more explicit ? Or simply "Parent folders" ?

On its position, indeed, that could be below the two other fields .. I just thought it was logical to show the series of folders leading to the item, and the item name just after. I didn't look at aesthetic considerations so far.

**Comment by Muddy7** [comment]
As I say, a _very_ minor point indeed. But I stand by my preference for placement in pop-up window. Personally (for others it might be different! As I said, personal tastes may vary) the first thing I would like to see is the name of the bookmark. Then where it is on the internet. Finally where it is located in my bookmark tree structure.

Regarding "Folder path" or "Parent folders", why not? For me, "Path" is crystal clear. Just thinking of those who don't know any computer jargon at all ;-)

**Comment by Muddy7** [comment]
I am falling more and more in love with your Bookmarks Extension, and the ease with which I can now find a bookmark's folder—and even see _in a nutshell_ its path in the Properties window.

**Comment by Muddy7** [comment]
I am falling more and more in love with your Bookmarks Extension, and the ease with which I can now find a bookmark's folder—and even see _in a nutshell_ its path in the Properties window.

**Comment by aaFn** [comment]
Thank you. Well no merit, this is just that FF is missing a key function .. I was missing it myself a lot, this is why I made it ...

**Comment by Muddy7** [comment]
The best compliment that both you and your extension could receive would be Firefox implementing this function into their Bookmark module as a result of their seeing yours >:-D

And yes, I agree. This is an obvious and howling omission.

**Comment by aaFn** [comment]
Yes, the utilmate goal for that add-on is to disappear when Firefox does it :-)

Ok, for now I am c:losing that issue as complete for the functionalities. We can always tweak cosmetic variations later if needed.

Thank you, aaFn.

**Comment by Muddy7** [comment]
> Yes, the utilmate goal for that add-on is to disappear _**(EDIT) if and**_ when Firefox does it :-)

> Ok, for now I am c:losing that issue as complete for the functionalities. We can always tweak cosmetic variations later if needed.

Perfect. And thanks :-)
