### ISSUE TITLE
Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2

### ISSUE THREAD

**Issue by Muddy7** [aaFn/Bookmark-search-plus-2#75]
It would be nice if you could add the shortcut keys Ctrl+Z (for Undo) and Ctrl+Y (for Redo) to the keyboard options
(carried forward, as requested by developer, from Issue #74 in order for this to be treated as a separate request)

**Comment by Muddy7** [comment]
I think the wording of my request should be nuanced a little bit:
You already have a 'Delete' option in the Context Menu. It would be great to also add an 'Undelete' option to that Context Menu.

**Comment by aaFn** [comment]
Helllo @Muddy7, as a matter of fact, I am considering to record all actions in an history, and then to show the history of actions in a pane in place of the search pane when needed, for the user to:
- exactly pick in one or two clicks which state he wants to move back to,
- but also to enable a replay of actions (in case things are missed and lost by FF, which for some reasons happens to a few people, and they lose their work :-( )

Ctrl-Z and Ctrl-Y would just be keyboard shortcuts to "navigate" the current position in that pane, even when it is not shown.

Let me know your thoughts.

**Comment by Muddy7** [comment]
Sounds amazing!!

Then the 'Undelete' button would simply be a shortcut for going back to the immediate last state (or the last state +1/+2/+3/...

It sounds like a much more sophisticated version of what we had in Xmarks before that excellent FF add-on was tragically discontinued by LogMeIn. Brilliant idea!

**Comment by Muddy7** [comment]
Great to see from the 2.0.74+ Release Notes that this is an active project in progress 😀 Thanks!

**Comment by aaFn** [comment]
Hello @Muddy7, today with 2.0.76, I added a first significant step for that feature, which is the "Bookmark history" window.

It allows to examine the history of all recorded bookmark actions since 2.0.71 is out, as well as some meta actions (like BSP2 start, or reload).
- The window is refreshed real time when there are updates and it is open.
- It also shows the undo/redo cursor position in the history stack, as well as undo/redo operations triggered by BSP2 (undo/redo in the native bookmark sidebar cannot be identified as such by BSP2, which only sees them as normal operations).
- It shows details for each history record, and has a bunch of action buttons, not yet active,

So it is only for browsing then. No undo/redo operation available either for now, that will be a next step.

The window can be open from the context menu on the BSP2 icon in the toolbar, or from the magnifying glass search button menu in the sidebar.

Let me know here if anybody has problems with, or suggestions on, that new feature.
AaFn.

**Comment by Muddy7** [comment]
Nice. Very nice.

 

Thank you 😊. Very much.

 

I haven’t yet thought this (tentative) suggestion out clearly, but do you think it would be a good idea to have a display mode that is able to group together multiple changes to a single bookmark?

 

This could be effected by having the option to sort the changes:

*	not only by time-date
*	but also by the bookmark sidebar (current) top-to-bottom order.

 

Just an idea. But perhaps too complicated code-wise to make it worthwhile for the sake of this modest improvement? And I’m still not sure if it’s really desirable. Still thinking this through.

 

Keith

**Comment by Muddy7** [comment]
Changes in red for further clarity

 

From: Keith at ILS <keith.mills@ils-international.be> 
Sent: 30 April 2020 03:27
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com>
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Nice. Very nice.

 

Thank you 😊. Very much.

 

I haven’t yet thought this (tentative) suggestion out clearly, but do you think it would be a good idea to have a display mode that is able to group together multiple changes to a single bookmark?

 

This could be effected by having the option to sort the changes:

*	either by time-date
*	or by the bookmark sidebar (current) top-to-bottom order.

 

Just an idea. But perhaps too complicated code-wise to make it worthwhile for the sake of this modest improvement? And I’m still not sure if it’s really desirable. Still thinking this through.

 

Keith

**Comment by Muddy7** [comment]
Or, better (regarding the second sort option below), to be able to click on a bookmark or a folder in the sidebar and see if, and if so what, changes have been made to it.

 

Keith

 

From: Keith at ILS <keith.mills@ils-international.be> 
Sent: 30 April 2020 03:29
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com>
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Changes in red for further clarity

 

From: Keith at ILS <keith.mills@ils-international.be <mailto:keith.mills@ils-international.be> > 
Sent: 30 April 2020 03:27
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Nice. Very nice.

 

Thank you 😊. Very much.

 

I haven’t yet thought this (tentative) suggestion out clearly, but do you think it would be a good idea to have a display mode that is able to group together multiple changes to a single bookmark?

 

This could be effected by having the option to sort the changes:

*	either by time-date
*	or by the bookmark sidebar (current) top-to-bottom order.

 

Just an idea. But perhaps too complicated code-wise to make it worthwhile for the sake of this modest improvement? And I’m still not sure if it’s really desirable. Still thinking this through.

 

Keith

**Comment by Muddy7** [comment]
Changes, once again, in red!

 

From: Keith at ILS <keith.mills@ils-international.be> 
Sent: 30 April 2020 03:38
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com>
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Or, better (regarding the second sort option below), to be able to click on a bookmark or a folder in the sidebar and see a history of the creation and, where appropriate, changes that have been made to it. Also the option of being to be able to display ( in grey?) deleted items and to display their history?

 

As I say, I’m not yet sure whether the effort codewise would be worthwhile for the (possibly?) modest improvement that this would provide.

 

Keith

 

From: Keith at ILS <keith.mills@ils-international.be <mailto:keith.mills@ils-international.be> > 
Sent: 30 April 2020 03:29
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Changes in red for further clarity

 

From: Keith at ILS <keith.mills@ils-international.be <mailto:keith.mills@ils-international.be> > 
Sent: 30 April 2020 03:27
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com>
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Nice. Very nice.

 

Thank you 😊. Very much.

 

I haven’t yet thought this (tentative) suggestion out clearly, but do you think it would be a good idea to have a display mode that is able to group together multiple changes to a single bookmark?

 

This could be effected by having the option to sort the changes:

*	either by time-date
*	or by the bookmark sidebar (current) top-to-bottom order.

 

Just an idea. But perhaps too complicated code-wise to make it worthwhile for the sake of this modest improvement? And I’m still not sure if it’s really desirable. Still thinking this through.

 

Keith

**Comment by Muddy7** [comment]
Sorry for the avalanche of mails ☹☹☹

 

From: Keith at ILS <keith.mills@ils-international.be> 
Sent: 30 April 2020 03:47
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com>
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Changes, once again, in red!

 

From: Keith at ILS <keith.mills@ils-international.be <mailto:keith.mills@ils-international.be> > 
Sent: 30 April 2020 03:38
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Or, better (regarding the second sort option below), to be able to click on a bookmark or a folder in the sidebar and see a history of the creation and, where appropriate, changes that have been made to it. Also in the sidebar the option of being to be able to display ( in grey?) deleted items and to click to display their history?

 

As I say, I’m not yet sure whether the effort codewise would be worthwhile for the (possibly?) modest improvement that this would provide.

 

Keith

 

From: Keith at ILS <keith.mills@ils-international.be <mailto:keith.mills@ils-international.be> > 
Sent: 30 April 2020 03:29
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Changes in red for further clarity

 

From: Keith at ILS <keith.mills@ils-international.be <mailto:keith.mills@ils-international.be> > 
Sent: 30 April 2020 03:27
To: 'aaFn/Bookmark-search-plus-2' <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: RE: [aaFn/Bookmark-search-plus-2] Add Ctrl+Z and Ctrl+Y shortcut keys to BSP2 (#75)

 

Nice. Very nice.

 

Thank you 😊. Very much.

 

I haven’t yet thought this (tentative) suggestion out clearly, but do you think it would be a good idea to have a display mode that is able to group together multiple changes to a single bookmark?

 

This could be effected by having the option to sort the changes:

*	either by time-date
*	or by the bookmark sidebar (current) top-to-bottom order.

 

Just an idea. But perhaps too complicated code-wise to make it worthwhile for the sake of this modest improvement? And I’m still not sure if it’s really desirable. Still thinking this through.

 

Keith

**Comment by aaFn** [comment]
Hello @Muddy7 , yes currently things are sorted by time-date.
I have in plan to implement a search panel like in the normal sidebar, so I guess it could address your second option.

The search panel would then combine the filter to reduce the wiew, and the time sort, plus a similar "show" feature as in the normal BSP2 sidebar to highlight where it is.
It is all then a matter of which filtering criteria we can use .. and my polan was to use the same settings as in the BSP2 main search configuration (do a click on the magnifying glass button to see them). Hoping this would address the majority of cases.

How does that sound ?

Btw, just note that for storage limits purpose, I am trimming the history list to 30 days (for now not configurable, I guess I will add that as an option later :-) ).

**Comment by Muddy7** [comment]
I haven’t completely understood, but from what I have, that sounds (as per usual 😉) even better than my suggestion!! I greatly look forward to the full functionality of this excellent undo/redo feature (though even at this early stage, it has already proved great: I managed only yesterday to easily get myself out of my mistaken renaming of a folder—I had intended to add a child folder but mistakenly renamed the existing folder—and easily go back to the original name)

**Comment by Muddy7** [comment]
To add: I am really impressed by this new BSP2 undo/redo feature (currently under development). It is so much more sophisticated than the basic Windows version. Thanks!

**Comment by Alpengreis** [comment]
About the trashfolder: deleting works ok after it's activated in options, if NOT activated, after deleting (with mouse) it needs a "refresh" till the deleted bookmark is no more visible.

**Comment by aaFn** [comment]
Hello @Alpengreis , indeed, I see I introduced a bug in 2.0.95 generating a code exception when removing a bookmark to the  BSP2 Trash while the rtash is invisible (see options page to make it visible for debug).

Sorry I missed that test case.
This is corrected in 2.0.96, which is out now. Let me know if all ok or if you still experience a problem, thanks aFn.

**Comment by Alpengreis** [comment]
Hi @aaFn All good now, thank you very much for fast fix!

**Comment by Cr8zyIvan** [comment]
I was coming to the GitHub to file an Enhancement Suggestion for Ctrl + Z (Undo), and found this thread, and I found the Bookmark history option.

I am writing only to say that I am in Awe and that this is amazing. This Firefox Add-On is steadily becoming my favourite. Just... great job!

**Comment by aaFn** [comment]
Correct, the history feature is a building block for it.
That enhancement (Undo Ctrl-Z and Redo Ctrl-Y) is now next on my list .. should be coming soon, hopefully in the next release after the one of today 🤞

**Comment by Muddy7** [comment]
> Correct, the history feature is a building block for it. That enhancement (Undo Ctrl-Z and Redo Ctrl-Y) is now next on my list .. should be coming soon, hopefully in the next release after the one of today 🤞

Great news! Just the bookmark history feature alone is already epic (_sooo_ useful). The Undo and Redo shortcuts will make it perfect!

**Comment by aaFn** [comment]
At last, that long due undo/redo function is now provided, in BSP2 2.0.117, which was just published.
This went through intensive testing, but I might have missed a few things.
So let me know if any problem.
Thank you, aaFn.

**Comment by Muddy7** [comment]
That's really great news!! Thanks for all the hard work that this must have entailed!

However, I seem to be having some teething problems:
1. When I went to my Firefox app, I found myself on the previous version of BSP2. so I needed to manually update from v.116 to v.117
2. Unfortunately, the **Actions** option _Undo(Ctrl-Z) etc._ in the Bookmarks History window was still greyed out after updating to the latest BSP2 version
3. I tried adding a new webpage bookmark to my BSP2 favourites, and then deleted the entry. However, when I went to this deleted entry in the BSP2 Bookmarks History, I still found the Undo(Ctrl-Z) was greyed out
4. I closed and restarted Firefox, but the problem persisted
5. I restarted Windows, but the problem still persisted, even after repeating point 3 above.

FYI I am on Windows 10 Version 22H2 (OS Build 19045, 3324).

I am hoping this problem can be ironed out, as I am very much looking forward to this brilliant new addition to your (already fantastic) extension.

**Comment by aaFn** [comment]
Hello @Muddy7 , for now the way to undo/redo is through keyboard = CtrlZ and Ctr-Y, on the main panel (and not in the history).
I will look at enabling buttons, and also activating Ctrl-Z and Ctrl-Y in the history window, in the next version.

Sorry for the inconvenience.

**Comment by Muddy7** [comment]
Aaah! Right! Got it. Many thanks.

Btw I'm amazed at what this will be like when everything is activated in the history window!!

**Comment by mzso** [comment]
What is this history window you guys speak of?

**Comment by Muddy7** [comment]
> What is this history window you guys speak of?

To the left of the search box:
1. Click the button with a square and a diagonal line inside it
2. Click "Bookmark history" at the bottom of the pop-up menu
Voilà!

**Comment by mzso** [comment]
[**@Muddy7**](https://github.com/Muddy7) commented on [Sep 9, 2023, 2:08 PM GMT+2](https://github.com/aaFn/Bookmark-search-plus-2/issues/75#issuecomment-1712496305 "2023-09-09T12:08:13Z - Replied by Github Reply Comments"):
> > What is this history window you guys speak of?
> 
> To the left of the search box:
> 1. Click the button with a square and a diagonal line inside it
> 2. Click "Bookmark history" at the bottom of the pop-up menu
> Voilà!
> 
> _Originally posted by @Muddy7 in https://github.com/aaFn/Bookmark-search-plus-2/issues/75#issuecomment-1712496305_

Ah. So this is some list about what BSP2 done with bookmarks? The last items are fairly old, so it can't be all bookmarks changes. dropping tabs/windows into bsp's sidebar don't even seem to be listed.

**Comment by Muddy7** [comment]
@mzso 
No. It's an **exhaustive** history of the last 30 days (I think) of deleted, modified, moved and new bookmarks. This is the first stage in my request to be able to undo (Ctrl+Z), or redo undone (Ctrl+Y), past actions in the BSP2 bookmark history. It goes much further than my original request, and will be streets ahead of the FF native bookmarks Ctrl+Z and Ctrl+Y option.

**Comment by aaFn** [comment]
I confirm that this is the last 30 days by default, but you can change it in the options, to a value between 1 and 9999 days.

The history pruning is happening at each BSP2 restart, which is in general when you start Firefox (you can also provoke it by disabling and re-enabling BSP2 in the add-ons page, whic is triggering a stop and a restart).

All bookmark changes are there, including the ones made through the native FF bookmark panel, or made through any other add-on manipulating bookmarks. This can be title or URL modification, moves, delete, creation (by drag and drop of tabs or any other).., Note, that there is no way to know which ones were made by which, as we cannot place any signature in bookmarks, and we do not know who originated the action when it is sent tot the add-on by the FF API.

**Comment by Muddy7** [comment]
Thanks, @aaFn, for all that really helpful information.

**Comment by Muddy7** [comment]
Thanks, @aaFn, for all that really helpful information.

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [Sep 9, 2023, 5:32 PM GMT+2](https://github.com/aaFn/Bookmark-search-plus-2/issues/75#issuecomment-1712538029 "2023-09-09T15:32:06Z - Replied by Github Reply Comments"):

> All bookmark changes are there, including the ones made through the native FF bookmark panel, or made through any other add-on manipulating bookmarks. This can be title or URL modification, moves, delete, creation (by drag and drop of tabs or any other).., Note, that there is no way to know which ones were made by which, as we cannot place any signature in bookmarks, and we do not know who originated the action when it is sent tot the add-on by the FF API.

Doesn't seem like that to me the latest bookmarks I created are not there and there's repetitive stuff I didn't touch for a long while that is shown moved many times.

**Comment by Muddy7** [comment]
Thanks, @aaFn, for all that really helpful information.

**Comment by Muddy7** [comment]
@mzso 
I dunno what to say. Works flawlessly for me.

**Comment by aaFn** [comment]
2.0.118 is out, with buttons enabled in the history window.
And there is now an expandable menu in the sidebar, under the search box, which contains also an undo and a redo button.
Use the twisite on the left of the search box to show it / hide it.

The buttons are enabled when it is possible to do the corresponding action, or disabled when not possible.

I also enabled Ctrl-Z and Ctrl-Y in the history window.

Let me know if any problem.
aaFn

**Comment by aaFn** [comment]
@mzso , do you still see problems on your side ?
Would you mind wharing a screen capture of what you see, and what you believe is abnormal or missing ?

Thank you, aaFn.

**Comment by Muddy7** [comment]
Great stuff, @aaFn !!

The Undo and Redo buttons in the Expandable Box under the Sidebar Search Box work flawlessly. Fantastic!!

However, at the moment, on my device at least, the Undo and Redo buttons now enabled in the History Window only work in the same way as those in the Expandable Box under the Sidebar Search Box, i.e. I can undo the latest single, or multiple, creations/modifications/deletions in backwards chronological order of their creation/modification/deletion but cannot (yet) select one particular past creation/modification/deletion for Undoing (except, of course, for the latest creation/modification/deletion). I presume this is because you are introducing your programming into the updates one step at a time. If that is so, so far it's perfect!

Oh, just one tiny proviso. I seem to have lost, with this latest update, the shortcut key to open and close the BSP+2 sidebar (Ctl-Q by default). It is also greyed out in the Options menu.

Thanks for all your excellent work 😁 !

**Comment by Muddy7** [comment]
Great stuff, @aaFn !!

The Undo and Redo buttons in the Expandable Box under the Sidebar Search Box work flawlessly. Fantastic!!

However, at the moment, on my device at least, the Undo and Redo buttons now enabled in the History Window only work in the same way as those in the Expandable Box under the Sidebar Search Box, i.e. I can undo the latest single, or multiple, creations/modifications/deletions in backwards chronological order of their creation/modification/deletion but cannot (yet) select one particular past creation/modification/deletion for Undoing (except, of course, for the latest creation/modification/deletion). I presume this is because you are introducing your programming into the updates one step at a time. If that is so, so far it's perfect!

Oh, just one tiny proviso. I seem to have lost, with this latest update, the shortcut key to open and close the BSP+2 sidebar (Ctl-Q by default). It is also greyed out in the Options menu.

Thanks for all your excellent work 😁 !

**Comment by Muddy7** [comment]
This morning I have discovered an interesting apparent quirk.

Yesterday I began testing the new BSP2 Undo/Redo function by adding a new bookmark (let's call it Bookmark X). In the process of testing I Undid, i.e. removed, and Redid, i.e. restored, this bookmark numerous times. It would seem that when I turned off my computer last night, I had Undone, ie. removed, that bookmark and subsequently added another bookmark (let's call it Bookmark Y).

Here is the apparent quirk: this morning I find that **Bookmark X is greyed out**, and it is no longer possible to Redo, i.e. restore, this bookmark with the Redo (or, indeed, the Undo) button in the Expandable Box. Bookmark Y and the preceding bookmarks in Bookmarks History, with the exception of Bookmark X, can be Undone without problem.

**Comment by aaFn** [comment]
Yes, the "undo all after" and "redo all until" functions are not activated, they will come later, as they are iterative calls to the base undo & redo functions towards the objective position. Incremental coding and release 😄 

On the second post, yes this is normal, this is the notion of active and passive branches in the history, and it acts like any undo/redo stack in an editor, or any other software:
- when you undo something (so come back in past on the stack)
- and then do "another action" which is not a redo, then this action takes the place of the redo in the stack and of all that follows it, and becomes the new active branch
- at this point, the part overwritten by the "another action" is lost
- so it is not possible anymore to redo what you overwrote with "another action".

Example:
in an editor, type ABCDEF, then Ctrl-z, Ctrl-z, Ctrl-z (= 3 times in past).
At this stage, you will see ABC
Then press Ctrl-Y, and you will see ABCD = D was just redone, and "EF" are still in the stack as being undone, waiting to be redone.
Then type G -> you will see ABCDG, and it is not possible anymore to do Ctrl-Y and see the E and F appear, because the "G" action replaced "EF" in the stack, and so "EF" are lost forever.

In BSP2, "E" and "F" still show because I implemented the history in a bit different way than just a pure stack.
However the effect is the same, the undo "E" and undo "F" become inactive, so are greyed out, and cannot be redone anymore, since the state on which they apply is not valid anymore, because "G" appeared, changed the stated, and forced a forking of the branch, leaving the "E" "F" branch inactive and non applicable anymore.

Hope this is clear.

**Comment by Muddy7** [comment]
OK! Thanks for that very clear explanation 😀.

What I hadn't realised is that what I imagined to be _undo an earlier bookmark_ will be in fact _"undo all after" that earlier bookmark._ I thought it would be _"undo just this single (earlier) bookmark creation/modification/deletion"._ I would have preferred the latter, and was hoping for and expecting (due to my misunderstanding 😳) this latter. Perhaps it is impossible*? If so, never mind. But if by any chance it is possible, might this be feasible to build into the programming code? If too much work, don't bother! But if possible, that would be really great!

--------------------
_*Sometimes of course, this will indeed be (presumably) impossible such as **the creation of a folder**, which is subsequently renamed and then subsequently filled with new bookmarks._

**Comment by Muddy7** [comment]
The sidebar shortcut key is working again! I don't know if this was some quirk to do with my computer, or something you fixed on the backend? Anyway, whatever the reason I'm glad I've got that back.

**Comment by aaFn** [comment]
Yes, that is the point, the state on which you want to undo / redo must be the same.
If the state changed, you cannot do an undo or redo.

It can be a "recreate", or a "delete", or a "rename/change to", but it won't be the same action exactly, and neither an undo nor undo.
To your point, once finished on "restore to" or "replay to", I will see how to add another one where you can select one action in the history, and "reproduce" it .. but for example, if the action is "undo remove", then this will simply execute a recreate, and if the bookmark already exists, another one will appear besides ...

**Comment by Muddy7** [comment]
Re your above comment: excellent!!

**Comment by aaFn** [comment]
On the shortcut, this is now managed through FF, so I am showing it in the options page, but it is greyed out, because only one place to manage it, in FF. You can only reset to default ni the options page, because "reset to default" does not exist in FF.

Note: the place to manage shortcut keys is in the cogwheel menu of the FF manage extensions page.

**Comment by Muddy7** [comment]
Yes. For some strange reason, I lost the BSP2 sidebar shortcut key yesterday after manually updating to latest BSP2 version, but it seems to have returned after booting this morning.

I was a bit confused when you said: 
`On the shortcut, this is now managed through FF
...
Note: the place to manage shortcut keys is in the cogwheel menu of the FF manage extensions page.`
but now I've just seen it. Yes, at the top of the Extensions page, I see the title "Manage your Extensions" and a cogwheel to the right of this. When I click the cogwheel, I see "Manage Extension Shortcuts" at the bottom of the Context Menu that appears.

Thanks for that!

Why I momentarily lost that shortcut key after manually updating BSP2 will have to presumably remain lost to the mists of time. But I got it back, which is the main thing!

**Comment by aaFn** [comment]
ok, great, thank you 😺 
aaFn

**Comment by Muddy7** [comment]
Today, I had for the first time the occasion to use the Undo feature outside of test conditions, and as expected it worked like a dream. For some inexplicable reason. I had unknowingly moved two important folders out of their normal paths. I spotted this very quickly and so, as these remained the most recent two changes I had made to FF bookmarks, I was able to use this new BSP2 function. It worked flawlessly 😁.

**Comment by Muddy7** [comment]
Today, I had for the first time the occasion to use the Undo feature outside of test conditions, and as expected it worked like a dream. For some inexplicable reason. I had unknowingly moved two important folders out of their normal paths. I spotted this very quickly and so, as these remained the most recent two changes I had made to FF bookmarks, I was able to use this new BSP2 function. It worked flawlessly 😁.

**Comment by Muddy7** [comment]
Unfortunately, two retrogade steps have taken place in the evolution of the Bookmark History window.

1. When you enabled the Undo feature in a BSP2 update (which was great!), quite a few of the changes made started manifesting themselves as "Multiple selection" in the Bookmark History window. Unfortunately, the "Muliple Selection" entries did not display any details of what changes had occurred in these Multiple Selections. That is to say, _all_ fields in the Bookmark History window regarding changes made (eg. Bookmark id, Bookmark type) were blank.
![Multiple Selection Entry](https://github.com/aaFn/Bookmark-search-plus-2/assets/12870935/c5c9d377-9f01-416f-ae4b-14b3dfa7982d)
What I found excellent about the Bookmark History window is that I can see details of every change made and so can manually undo any individual change (eg. undelete a deleted bookmark, undo modifications made to an edited bookmark). However, now that I can't see those changes in the Mutliple Selection entries, that is no longer possible.
2. Today this situation has unfortunately escalated. As of today, I can no longer see the details of ANY of the Bookmark History changes, not only multiple selections but also single entries as well. So I am unable to reverse ANY of the changes I have made, except through the Undo button.
![Single Selection entry](https://github.com/aaFn/Bookmark-search-plus-2/assets/12870935/4c7f78d1-e5bc-4d74-900d-5b0a01bdeed0)

I do hope the two above problems can be rectified as I have found this Bookmark History window to be extremely well-conceived and, as a result, VERY useful.

Thanks!

**Comment by aaFn** [comment]
Ok, sorry for that, if you switch to the "Raw list" view mode, could you show me what you see ?

**Comment by Muddy7** [comment]
Already tried that. I see the same, unfortunately, ie blank fields.

Is this a problem with the BSP2 code, or may it be a problem with a corruption in the installation of the extension on my computer?

**Comment by aaFn** [comment]
I do not have the problem, but there might be a bug remaining in spite of all my testing, showing off on your side and not on mine.
What is strange is that:
1. I do not see the "undo/redo" cursor on your capture
2. I do not see either the #xx value at top, which should always be there.

All looks like the window is not terminating its display .... and so is not really operational.

Can I ask you to:
- close the history window
- disable and re-enable BSP2 in the add-on page (not uninstall, just disable to ensure a proper restart)
- execute the procedure here https://github.com/aaFn/Bookmark-search-plus-2/wiki/Getting-and-providing-logs-for-debugging-BSP2, but when you arrive to step 5, then simply open the History window (not before)
- and report to me what is logged in the browser console

Hopefullly, we will catch an error message / an exception which will indicate what is going wrong.

**Comment by Muddy7** [comment]
OK. No problem. But before I do this, can you tell me where I will find the **Browser Console** so that I can be sure to capture any error messages/exceptions. Will it just appear automatically at Step 5 of your procedure?

**BTW I'm not sure what you mean by the "undo/redo cursor"??** As you see I have an Undo and a Redo button in my Bookmarks History window and of course, at the top of the BSP2 bookmarks sidebar on my Firefox Browser Pages, I can reveal the two buttons with semicircular arrows for Undo and Redo by clicking the downwards facing arrow to the left of the magnifying glass in the BSP2 search window.

**Comment by aaFn** [comment]
The browser console is opened by pressing Ctrl+Shit+J, or it is open from the menu in Tools->Browser Tools->Browser Console

**Comment by Muddy7** [comment]
OK. I followed the debugging procedure to Step 5, opened the BSP2 Bookmarks History window, and then did a capture of the log window with Snip & Sketch (Aargh! Now I see that "Step 6" describes a way of copying the log with the Browser Console. If the sceen capture below doesn't provide you with all the necessary information, I can always redo the procedure).
![FF Multiprocess Bowser Console after Step 5, ie  opening BSP2 Bookmarks History window, of BSP2 Debugging Procedure](https://github.com/aaFn/Bookmark-search-plus-2/assets/12870935/84208d38-14da-4fe2-9ff0-a82e18a7b246)
Unfortunately, after following the debugging procedure I still have the same problem as before, ie.  the fields (Bookmark id, Bookmark type, Path etc.) for each entry in BSP2 Bookmarks History window are still completely blank, regardless of whether I select "Link undo/redo" or "Raw list". And the #xx is still blank.

Thank you for the explanation about the Undo/Redo Cursor. Yes, I had that before but didn't quite understand what it was or did. When this problem has been sorted out, I'll have a closer look at that cursor so that I can understand better what it does and how it works. Thanks!

**Comment by aaFn** [comment]
Hello @Muddy7 , of the screenshot was enough to catch the problem, this is related on the exception on history.js that we can see inside it.
I corrected, it was an undeclared variable exception (I really find javascript and all untyped and uncompiled languages like python and others very painful for that ..!).

I just published 2.0.120 with the correction, update your add-ons, and your BSP2 instance should now move to that new version, and the history window should be ok now (or there might be another bug on your side hidden behind it, but at least this one is cured).

Let me know, aaFn.

**Comment by Muddy7** [comment]
Excellent!

Everything seems to be working correctly.

Thanks so much!

1. I can see the data for a selected line in the fields on the RH side of the Bookmarks History window (Bookmark id, Bookmark type, Path etc.), both in "link undo/redo" and "raw list" format.
2. _BTW with regard to the above, can you briefly explain the difference between those two options for the user (such as myself!)?_
3. The favicons are back in the Bookmarks History window (I can't remember if they were there before on my computer, but they're certainly there now!)
4. I've now found out how to expand the Multiple Selection entries. I'm not sure if this function was not previously working on my computer, or if I was just having problems because this option is a bit tricky to find (one has to locate _exactly_ the right place on the line to click)

So all is good now!

However, I was a little confused by the position of the "undo/redo" cursor on the capture image of your Bookmarks History window. My understanding, after communicating with you and after testing, is that the undo/redo function, as with all Windows apps, starts from the latest change made. Yet I can see a Multiple Selection change entry BELOW (and therefore presumably more recent than) the entry with the undo/redo cursor on your capture image. How can that be??

**Comment by Muddy7** [comment]
Sorry for the pain in the neck you had with javascript! And thanks for such a super-rapid correction of the coding!! We (I'm confident I can use the plural "we") really appreciate the trouble you go to to work on and perfect this EXCELLENT Firefox extension 😉.

**Comment by aaFn** [comment]
Thank you @Muddy7 , good news then !

In the past versions, the multiple bookmark entries were always expanded, and the twistie was not active.
When I introduced the full undo/redo support, I made those twisties active, and the default is that they are not expanded. This is why this was a bit misleading to you, sorry for that inconvenience (bringing functions by increments makes things happen faster, but introduce more changes on the users .. that is one of the drawbacks of what is called "Agile" development ..).

True this is a bit tiny, I will think about how this could be improved for useability.

The "link undo/redo" and "raw list" formats are 2 ways to look at the same things:
- In the history, undo and redo actions can happen at any time in future, so they are stored on their own.
- The raw list shows where they are really, however they are visually disconnected from the bookmark operation they relate to
- The linked list shows them attached to the bookmark operation they relate to, and then the user loses the visual information of when that really happened in the history ..
- Each responds to a different need, so I kept both (at least the raw view allowed me to debug several situations 😄 ).

The undo/redo cursor has always been here, but it was not useful until I introduced the undo/redo buttons, because it was always at the end ..

It shows the place in the history stack where you are in the undo/redo capabilities:
- All that is above (before) it, including the line it is on), can be undone if they are active
- All that is below (after) it, can be redone if they are active

For something to become inactive, it must have been undone, and then replaced by another action of the user - which is not a redo.
In that case, the history keeps track that it happened one day, but it cannot be redone / replayed anymore, because something different happened in the middle which is changing the state of the reality, and a new branch is then made (see that as multiverses 😆 ).
The same happen in any editor by the way ...

**Comment by Muddy7** [comment]
Thanks so much for that explanation. All is clear now! I had to read a couple of bits of your post a couple of times to understand, but now I do understand. I like your allusion to "multiverses"; that's quite an apt analogy for performing an undo or a series of undos and then introducing a completely new action. Multiverses...yes indeed 😁.

BTW, please don't forget, **_IF_** you find time to do it (you already are doing a great deal for us), your suggestion in your post in this thread of September 25, 12:11 PM G%T+1:
https://github.com/aaFn/Bookmark-search-plus-2/issues/75#issuecomment-1733364924
