### ISSUE TITLE
Add user option to control spacing between items.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#78]
... An issue arising at https://github.com/aaFn/Bookmark-search-plus-2/issues/77#issuecomment-449173415

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , 2.0.49 is out with the feature. Let me know.

**Comment by JohnLukeBentley** [comment]
Seems to be working perfectly. You can close this issue. Thanks very much!

**Comment by aaFn** [comment]
Ok, thank you :-)
