### ISSUE TITLE
[Feature Request] Launch extension headless

### ISSUE THREAD

**Issue by v00p** [aaFn/Bookmark-search-plus-2#79]
This would make the extension more comfortable for managing our bookmarks.

I'm not sure exactly how to implement this, but I can already launch a couple extension like so. (ie: CRXView by Rob W.) 
It might only require to adapt the current sidebar.html file to create one dedicated for such headless mode, and adjust your manifest accordingly (adding that html to your [web_accessible_resources] section I believe)

**Comment by aaFn** [comment]
Hello @v00p , what do  you mean by "headless" ?

**Comment by aaFn** [comment]
Hello @v00p , looking more, are you talking of https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode ?

Still not sure what exactly you would like BSP2 to do when in that mode ?

**Comment by aaFn** [comment]
Closing as not able to interpret the demand.
Please reopen when you want if you are willing to give more details :-)
