### ISSUE TITLE
Use the page name for the Name filed when adding a bookmark

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#8]
Step to reproduce:
- drag the (i) icon from the location bar to the bookmark tree

Both Name & Address fields contains the URL.
Name should have the page's name, like the native Firefox bookmark manager does.

**Comment by aaFn** [comment]
Ok, I'll look at that, this is a case I missed.
I did the Tab and a link in the HTML page, but didn't know about the (i)

**Comment by aaFn** [comment]
That was an easy one, just had to look for "text/x-moz-url" in the dragged attributes and find the title in there .. :-)
Will be part of 2.0.5.

**Comment by aaFn** [comment]
Hello @vitaaliy, by the way, I really need some stats from you as asked in #5, if you are ok to do that for me.
This should allow me to make a proper choice for the design strategy on "asynchronous load+display", as explained in #2 .. if you can :-) ?
Else I will make a choice a little blindly, which may not be optimal for your case.

**Comment by aaFn** [comment]
Implemented in 2.0.5, Let me know if not working on your side, else let's close the issue.

**Comment by aaFn** [comment]
Closed
