### ISSUE TITLE
Position in tree preserved on reopen.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#82]
Currently if you scroll some way down the BSP2 sidebar; close the sidebar; reopen it - then the sidebar opens to the top of the bookmarks. Your prior location is lost.

I suggest that the prior location should be presented when you reopen the sidebar (at least within the same browsing session). If not always then as an option.

**Comment by aaFn** [comment]
Yes, this relates to this #47 by @phmio
For now, I delayed that implementation, as the pull request happened at a bad time and was too far off from the main code which deeply evolved at the same time.

**Comment by JohnLukeBentley** [comment]
OK, great.

in #47 you rightly mention two issues.

The first is ...

> BSP2 is made to function in multiple FF windows.
> In case of such multiple windows, each time one bookmark is selected in any of the windows, the remembered value being unique will serve to all other windows .. would that be ok ?

Your question makes the answer obvious (as good questions often do): ideally, and if possible, the remembered bookmarks should be window specific. But I'm not sure this is vital....

... I generally work with a triple monitor setup so I very much face multiple windows of FF with BSP2 sometimes open on each window. To the extent that I close and reopen BSP2 I think this is generally with respect to one "main" window. That is, while the other FF instances are generally untouched. In other words, if the closing/reopening on the main window corrupted the other windows ... I'm not sure it matters so much.

... Maybe it will be a choice between how easy each option is to code. If it is significantly harder to track multiple windows then we could start with the general solution and see how that feels (as a user).

> What to do in case a bookmark is selected during a search, but is in fact hidden (one of its parent folder is closed) ? What you propose in the PR forces it open and unhidden on next time the add-on is open. However, when you cancel the active search, it becomes hidden again .. so that wouldn't be consistent, because next add-on restart would reopen the folder while the user left it closed when stopping the add-on ..

Perhaps this is approached as a separate issue first: That is, I'd suggest that when you get a folder in the search result and you click on it then it should open the folder in the main tree (even if currently closed).

**Comment by aaFn** [comment]
On the first issue, since we are not guaranteed that window ids are the same across FF restarts when it reopens them (and as a matter of fact, I believe this is not the case ..), that looks not really appropriate to save values associated with window ids.
However, there is nothing else to identify an FF instance .. so that means only one value can be saved in local storage.

For the cases of BSP2 closed and open while the FF window remain, maybe something can be done .. by having a second structure in memory organized by window id, not saved to local storage.

So each time a bookmark is selected, it would be saved once in local storage, window independant, and the last window who saved wins, and it would be saved in the background page per window id, for retrieval by BSP2 when re-opening ... and if no window, take the saved value in local storage (and if none, start at top).

For the second problem, I guess a simple answer is to delete saved values (in memory and in local storage) when the selection is lost - for exmaple when closing an ancestor folder containing it.

**Comment by JohnLukeBentley** [comment]
On the first issue: yes I don't think handling this across FF restarts is important. But within a FF session if you have available a Window ID, as you suggest, than that seems the key to making it work.

> For the second problem, I guess a simple answer is to delete saved values (in memory and in local storage) when the selection is lost - for example when closing an ancestor folder containing the selection.

(Unless I'm misunderstanding): wouldn't we just want to preserve the state of the tree whenever selection (in the search window) is lost? That is:

* User searches for folder.
* Folder shows up in search pane.
* User selects folder in search pane results. This triggers: folder in tree is autofocused and opened (given we've assumed it is closed).
* User moves focus out of search pane (whether going to the tree; or moving focus to another app).
* State of tree with folder open is preserved.

**Comment by aaFn** [comment]
Yes, when focus moves our, selection is kept, so this is ok (selection is managed by me, resulting from focus at a given time, and making it permanent).
Selection on an element disappears when another element is selected, or when an ancestor forlder is closed, or when it is deleted (either directly or as a result of an ancestor folder delete).

**Comment by JohnLukeBentley** [comment]
So on selection and how that relates preserving position in the tree ... I'm a bit too tired at the moment to see the interaction and the problems that might cause ... so I'll just leave you to it. 

... Multiselect was on my list of suggestions to make. So I'm glad that's on your TODO list.

**Comment by aaFn** [comment]
Implemented in 2.0.66 - let me know how it goes, thanks aaFn.

**Comment by JohnLukeBentley** [comment]
Thanks aaFn. I've updated to 2.0.66 but don't see this option. There's a chance I'm reading past it. What's the text of this option?

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , this is not an option, this is always on.
If you believe that should be an option, let me know.

**Comment by JohnLukeBentley** [comment]
In that case it's not working for me. I have restarted browser. Would you like me to clear my browser cache or [Reload all bookmarks from FF now]?

**Comment by aaFn** [comment]
Well, here is what should happen (after making sure you have 2.0.66 of course):
- Select a bookmark item anywhere in the tree, preferably at bottom of the tree
- Maybe wait some seconds to make sure the position is is well written in local storage ..
- Close FF
- Reopen FF = BSP2 will focus (scroll down) to the bookmark you had selected when closing FF. Or if it does not exist anymore, then the first bookmark in the tree is selected (highlighted)

I tested on Win10 and Linux. Let me know if there is a problem on your side.

**Comment by JohnLukeBentley** [comment]
Ok that works.

But it doesn't work if the bookmark has been selected in virtue of a BSP2 search result. Moreover, even if I manually select the found bookmark (after a BSP2 search) that doesn't work.

**Comment by aaFn** [comment]
Ok, that's a bug :-)

**Comment by JohnLukeBentley** [comment]
:)

**Comment by aaFn** [comment]
So verifying, no this works in fact as designed:
- If you have the option `After "Show Bookmark", leave bookmark tree open by default when closing search pane` set, all works well
- If that option is not set, then two cases:
  - If the search result iin a part of the tree already open (or if you force it to remain open), then on next FF start, BSP2 scrolls down to it.
  - If the search result is in a part of the tree which is normally closed, then when restarting, since that part is closed (hidden), BSP2 goes back at top.

**Comment by JohnLukeBentley** [comment]
"then on next FF start, BSP2 scrolls down to it".

The original suggestion is to preserve tree position not on FF close and reopen (restart) (although that's good too) but BSP2 close and reopen (restart). Maybe you meant to type "next BSP2 start"?

Anyway with that design goal in mind:

>If that option is not set, then two cases:
> * If the search result in a part of the tree already open (or if you force it to remain open), then on next FF start, BSP2 scrolls down to it.

Yes that works as described, and is desirable.

> * if the search result is in a part of the tree which is normally closed, then when restarting, since that part is closed (hidden), BSP2 goes back at top.

I see that behaviour now. But I'd suggest you change that behaviour. If you search for a bookmark, and click it in the search pane to take you to it's position in the tree then you want it: not only to be opened now; but to stay open if you restart BSP2.

> If you have the option After "Show Bookmark", leave bookmark tree open by default when closing search pane set,

With that option set the behaviour appears to be identical to when it is not set, in terms of preserving tree position on BSP2 restart. That is, (as above) upon BSP2 restart the tree is at the bookmark, or at the top, depending on whether the found bookmark was in a folder originally open or not.

**Comment by aaFn** [comment]
> With that option set the behaviour appears to be identical to when it is not set, in terms of preserving tree position on BSP2 restart. That is, (as above) upon BSP2 restart the tree is at the bookmark, or at the top, depending on whether the found bookmark was in a folder originally open or not.
So now, that is a bug .. I guess I forget to save the open folder state after changing it ... I'll see during the week-end to investigate / correct.

Note that a tree position cannot really be stored, as graphical coordinates depend a lot of screen resolution, size .. etc ... what is stored is the selected bookimark Id.

**Comment by JohnLukeBentley** [comment]
> Note that a tree position cannot really be stored, as graphical coordinates depend a lot on screen resolution, size .. etc ... and these can change between restarts. What is stored is the id of the selected bookimark.

By "tree position" I only meant that the selected bookmark is properly brought into view on BSP2 restart, as you've successfully achieved under some conditions.

> > With that option set the behaviour appears to be identical to when it is not set, in terms of preserving tree position on BSP2 restart. That is, (as above) upon BSP2 restart the tree is at the bookmark, or at the top, depending on whether the found bookmark was in a folder originally open or not.

> So now, that is a bug.

Well I'd suggest there should be no difference in behaviour if `After "Show Bookmark", leave bookmark tree open by default when closing search pane` is set or not.

The main thing is that you show the found bookmark in the tree upon BSP2 restart, regardless of other settings, and regardless of whether the found bookmark was with a close or open folder (keep the folder open if found in a close folder).

**Comment by aaFn** [comment]
As a matter of fact, opening the tree to show it on FF restart would perturb the tree structure .. indeed, on FF restart, the search result is not open, so there is no way to close what was just open as result of a search.

Therefore, this is working as intended = if the option is not set, that means the user does not want to change the open state of a tree upon a search. A selection on search is temporary .. so on FF restart, it is not retained.

**Comment by JohnLukeBentley** [comment]
Tell me what I need to do to have a bookmark remain open after BSP2 restart (let's put aside FF restart for the moment), where the bookmark was the child of a closed parent prior to search.

**Comment by aaFn** [comment]
Set the option After `"Show Bookmark", leave bookmark tree open by default when closing search pane` .. whne I will hve corrected the bug :slightly_smiling_face:   (this week end)

**Comment by aaFn** [comment]
Bug is now corrected in 2.0.67. We should be good now. Let me know

**Comment by JohnLukeBentley** [comment]
aaFn great work! That seems to work now as I intended. 

Tree position is now preserved between BSP2 restarts (and, as a bonus, FF restarts) regardless of whether the found bookmark was a child of a previously closed parent, or not.

Thanks very much.

Only #31 to go before I'd regard BSP2 as feature complete, notwithstanding the many more open issues.

**Comment by aaFn** [comment]
Yes, more difficult, the menu starts to be quite crowded, I would need a sub-menu I think ...

**Comment by phmio** [comment]
Hello @aaFn

It's been a while since I've been here. It's even a chance that I was able to remember my password.
I just updated BSP2 with the latest version, and I was pleasantly surprised :smiley: to see that you succeed to implement @JohnLukeBentley's requests and my initial PR #47.

So again, a big thanks for all your work!
