### ISSUE TITLE
Search pane: some bookmarks wrongly represented as children of returned folder.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#84]
In the search pane sometimes a folder, among bookmarks, is returned. This is as desired.

Furthermore, sometimes bookmarks are represented as being children of returned folders, in virtue of the indentation of icons. 

However, sometimes these child bookmarks are not sufficiently demarcated from other bookmarks that are listed below the folder, but aren't children of the folder shown in the search results.

Here is an example ...

![image](https://user-images.githubusercontent.com/18357541/51467096-d02bc800-1dbf-11e9-99d1-2b24dac82ca9.png)

... the bookmark "About OED V ...." is (truly) a child of the "Oxford" folder. The bookmark "Oxford Toilet Roll Holder ... " is not (truly) a child of the "Oxford" folder.

However, in the search pane they both appear to be children of the "Oxford" folder.

I suggest implementing some kind of visual design to clearly distinguish, in the search pane, between:
* bookmarks that belong to a parent folder, that also appears in the search pane; and
* bookmarks that do not belong to the parent folder appearing the search pane

For example, perhaps you could code in a grey background around the "Oxford" folder and the bookmark "About OED V ....", to show their grouped relationship ... and that the bookmark "Oxford Toilet Roll Holder ... " is excluded from that relationship.

Edit: Or maybe a top and bottom margin would better show the group.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley, here is the rule that is applied:
- all folders have no indentation
- all bookmarks have the same fixed indentation

I.e., indentation in search results is meant to just visually distinguish between folders and bookmarks, and not to mark children of folders.
Indeed, in a search result, the notion of "children of" is not relevant = this is a flat list of all matching objects, and in addition the order of these objects is as the API returns them (which I believe is ordered by their creation time, with oldest first and most recent last).

As far as my memory goes, this is mimicking what the original Bookmark Search Plus from alice0775 was doing, but I will need to check again.

**Comment by aaFn** [comment]
Helllo @JohnLukeBentley, I checked ... and as a matter of fact, the old Sidebar Bookmark Search Plus from alice0775 was not showing folders at all in the search result.

From my point of view, it was a missing feature ... :-)

The visual distinction through "no indentation" is quite useful, at least for me.
I understand it can be a bit misleading, however I am not sure it is creating a real problem.
Would you have a better suggestion ?

**Comment by aaFn** [comment]
I resolved as follows:
![Image1](https://user-images.githubusercontent.com/36155054/59151517-d223ba00-8a34-11e9-91c8-d47f73d1a1df.png)

So shifted the folder to the right like normal bookmarks, but added the twistie at front to make it conspicuous / visually distinguishable from normal bookmarks in big lists.

Hope this is solving your point.
It will be in 2.0.62.

**Comment by aaFn** [comment]
In 2.0.62, so closing the issue as resolved.
Let me know if any problem.

**Comment by JohnLukeBentley** [comment]
Hello aaFn,

Yes, that you search for folders, as well as bookmarks, is a great enhancement over native or alice's thing.

What you have done in 2.0.62 is an improvement. However, I'd suggest you either:

* Keep your current search display algorithm, where folders and bookmarks are first order items of equal rank. In this case: remove the twisty but keep the folder shifted like normal bookmarks. Otherwise you break the visual language that the twisty can be clicked to reveal children; or
* (Preferred) Change the search display algorithm to show the relationship between child bookmarks that match the search string and a parent folder that matches the search string. In this case, indent accordingly. So:
  - For folders that match "foo" but have no children that match "foo": return the folder as a first order item (in equal rank with any other non-child bookmarks that match "foo")
  - For folders that match "foo" with some immediate children that match "foo": return the folder as a first order item (in equal rank with any other non-child bookmarks that match "foo"); and indent the returned children
 - For folders that match "foo" with some grand-children that match "foo" (but no immediate children that match foo): return the folder as a first order item (in equal rank with any other non-child bookmarks that match "foo"); indent the returned grand-children in their proper hierarchy but with any intermediate folders that don't match "foo" being greyed out (or otherwise visually distinguished as not matching the search).

In all cases I wouldn't include a twisty because I don't think folders should be openable/closeable in the search pane. If there are relevant children to display the you, the dev, just open the folder. If there are no relevant children to display then there shouldn't be a twisty.

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , these are good suggestions, however, the search result is not mine, it is FF one, and I do not master the order in which things are returned.

It is just a flat list (no structure neither hierarchy realtionship between the object), and as a matter of fact, I suspect they are ordered by time of creation .. or simply by bookmark id, which should amount to the same.

And I need the visual catch of where are the folders inside the returned list ..

Hence for now the twistie in first "column", which makes the line look as it is in the main tree by the way, so is not so misleading as the previous display, but help catch very wuickly those lines.
Again, if you have a better idea on how to make the folders quickly visible (without changing the result order from FF), I'll welcome your ideas.

**Comment by JohnLukeBentley** [comment]
Thanks for your welcoming my ideas.

Given you have no control over the search, in terms of order or hierarchy, then my previous suggestion remains for this case. That is, 
* Keep folders and bookmarks in line (as they are now); and
* Remove the twisty

> And I need the visual catch of where are the folders inside the returned list ..

As a developer or user?

If you mean as a user then I agree: we want to differentiate folders from bookmarks. Why, then, is not the existing folder icon sufficient (without a twisty)?

**Comment by aaFn** [comment]
As user yes .. remember I made that add-on for myself initially, before publishing it :-)

Sometimes I have big return lists, and the folder icon is not sufficient to quickly pick the folders, need something visually different to catch them quickly .. For now I'll keep the twistie until we find something less meaningful but still eye catching .. (and not ugly ..)

**Comment by JohnLukeBentley** [comment]
> Sometimes I have big return lists,

Me too.

> the folder icon is not sufficient to quickly pick the folders

I think we'll just disagree on this aesthetic point.

> Having something in the first "column" (different indentation) plays that role very well. For now I'll keep the twistie as it is at that place, until I find something less meaningful but still eye catching .. (and not ugly of course ..)

How about:
* Almost any other symbol in that first column. E.g. An asterisk (*); or hash (#); or
* A border around the folder icon and folder text; or
* A slightly greyed background underneath the folder icon and folder text.

... I think almost any other choice will be superior to a twistie, as conventionally the twistie says "you can open and close this corresponding folder".

**Comment by aaFn** [comment]
Thank you, "slightly greyed background" on the whole row could be a good idea.
Will think about it, just need to be careful because of #100

**Comment by JohnLukeBentley** [comment]
Hi aaFn, I hope you are well.

I had forgotten about this thread but in using BSP2 I've rediscovered the issue this thread raises. And there remains an annoying problem for me ...

In the Search Pane I can, like you, sometimes get long lists of items. Frequently in the list I get folders that have identical names, because I have identically named folders in my searchable set. These identically named folders have different meanings given the context in which they are placed. E.g. In my searchable set I'll have something like the following folders ...

* Software Development
  - Architecture
* ...
* Buildings
  - Architecture

... and when I search on the String "Architecture" I'll get a big list of bookmarks and both "Architecture" folders. But I don't know which "Architecture" folder is relevant. Forgetting how BSP2 works in the search pane I click on the twisty because that conventionally indicates that you *can* open the folder to examine the children. However, BSP2 just jumps me to the "Architecture" folder in the bookmark heirarchy which is, for a moment, unexpected.

Scanning through our previous dicussion I note your options for what gets returned in the search plane is limited. But we didn't discuss the following possibility. So I now suggest both ...

(If this is possible) returning the first part of a folder's parent folder name, e.g.,

* "Architecture (Software Dev ...)"
* "Architecture (Buildings)"

And/Or (at least) ...

> How about:
> * Almost any other symbol in that first column. E.g. An asterisk (*); or hash (#); or
> * A border around the folder icon and folder text; or
> * A slightly greyed background underneath the folder icon and folder text.
> 
> ... I think almost any other choice will be superior to a twistie, as conventionally the twistie says "you can open and close this corresponding folder".

**Comment by aaFn** [comment]
Hello @JohnLukeBentley ,

   on the first one, did you try using that option ?
`On mouse hover above search result, show path to bookmark item instead of title + url`

On the second one, I could use maybe this one https://github.com/aaFn/Bookmark-search-plus-2/blob/master/icons/searchsub.png instead of the twistie, to signal a folder with another easy sign, what do you think ?

**Comment by JohnLukeBentley** [comment]
Hi @aaFn!

Apologies. I should have reviewed those options. And thanks for pointing to them. Those options are successful at disambiguiting folders with the same name in the search pane. I still might prefer, or would like to have in addition, (truncated?) path data displayed next to the folder's text itself e.g "Architecture (Software Dev < Coding < ...)", to save from having to hover. However, that you've got these hover features implemented is sufficient. So you could take or leave my suggestion here, as you see fit.

On the twistie icon issue. Good of you to point to an alternative. But I think searchsub.png just perpetuates the same problem with the twistie. It's suggesting this folder can be opened to reveal its children.

Recalling your motive ...
> And I need the visual catch of where are the folders inside the returned list ..

My position was, and remains, that it is better just to eliminate the twistie, or alternative, in the search pane. You disagree (or, at least, once disagreed) ...
>  the folder icon is not sufficient to quickly pick the folders

As an alternative to my preferred position (elimination) I think anything that *doesn't* suggest the folder can be opened is what we'd need. It could well be a character rather than an icon. E.g. Any of (subject to seeing how they look in context) ...

> * ¤∙∎⊕⊚⊜⊡╬█▇■☻●◙

**Comment by aaFn** [comment]
Thanks, I like the simple round bullet ... let me see how that renders in context by trying in a dev version

**Comment by JohnLukeBentley** [comment]
Yeah a simple round bullet might be best. Take your time with your dev tests.

**Comment by aaFn** [comment]
Done in 2.0.93 which is out now.

Thanks, aaFn.

**Comment by JohnLukeBentley** [comment]
Thanks aafn, much better. The hollow circle icon seems like a good choice.

It's not vital but would making it a bit darker be more pleasing? E.g. the color of an open twisty.

**Comment by aaFn** [comment]
Ok, yes, that makes sense, it is somewhat too light.
In 2.0.94, just published now .. thanks aaFn.

**Comment by JohnLukeBentley** [comment]
I'd go darker still. But at this point it's a matter of arbitrary detail and if left as is, it would be fine. That is, whatever your preferences here, they'll be fine in my view.

**Comment by aaFn** [comment]
Ok, I will vait for other reactions .. for now this is the same "dark" as the open twistie.
Thank you, aaFn.

**Comment by JohnLukeBentley** [comment]
Thanks aaFn. That's fine.

**Comment by aaFn** [comment]
Update on search lists returning multiple items with same name,, and need for disambiguation = I will enable in 2.0.97 the "Bookmark path" context submenu which is available everywhere in FF on bookmarks, except inside BSP2 sidebar itself so far.
This shows the path to the bookmark.

That way, there will now be 3 ways to get the path to a bookmark, inside BSP2 sidebar:
- "Bookmark path" context submenu = one click + "mouse stay" away, active everywhere in FF
- open property window = 2 clicks away, also allows to change values or cancel, active in the whole of BSP2 sidebar
- option to show it on mouse hover = only active in Search pane, and replacing the bookmark title + URL hover bubble

That way, each user can pick what is suiting them best ... 🙂
