### ISSUE TITLE
Local page does not open

### ISSUE THREAD

**Issue by Wernfried** [aaFn/Bookmark-search-plus-2#85]
I have a bookmark to local file, i.e. "file:///C:/Perl64/html/index.html"
The page does not open when I click on it. There is just no response on the click.

Can this be fixed, please?

Best Regards

**Comment by aaFn** [comment]
Hello @Wernfried , correct, this is a feature of FF = WebExtension add-ons are not allowed to open local files or even to trigger actions to it.

If you open the browser console (Ctrl+Shit+J), and then click on your bookmark from within BSP2, you will see a security exception appear in the conosle => FF has prevented BSP2 to do the action.

There's nothing which can be done about it as I know, and this is good for our security as users .. but as always with security, this also means limitations for us ...

**Comment by Wernfried** [comment]
No problem, I will install an apache server on my PC, then I can open the files from http://localhost/...

**Comment by aaFn** [comment]
Wow :-) Not the solution for Mister everybody, but will work perfect :-)

**Comment by JohnLukeBentley** [comment]
This is an unfortunate limitation.

I'll note that in the native bookmark manager local pages, as in 
"file:///C:/SomeFolder/index.html", open fine.

:/
