### ISSUE TITLE
Don't open it in every window on install

### ISSUE THREAD

**Issue by tbertels** [aaFn/Bookmark-search-plus-2#86]
On install (or enable), it opens itself in every window (and replaces Tree Style Tab), where we have to close it or switch back. It would be better to open it only in the active window or none at all if that's not doable.

**Comment by aaFn** [comment]
Hello @tbertels, this the default of FF, cf. "open_at_install"
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action
and I believe this is the right thing to do from security and user protection point of views, as it avoids that anything can install without going unnoticed by the user.

This effect is on install only. It does not happen when activating / enabling an add-on.

The use case of somebody installing and then regularly uninstalling then re-installing an add-on is not a frequent use case (if that really happens ..).
Users most frequently deactivate / disable and re-activate / enable add-ons .. and I tested it to verify, BSP2 when being activated (or any other add-on by the way) does not replace Tree Style Tab sidebar, as designed by FF.

Also, in general, users installing an add-on immediately want to see what it is doing .. If it installs silently, and they have to search how to activate it, they can just conclude it is doing nothing.

So I'd rather remain with the FF default.

Let me know if you have other views, thank you, aaFn.

**Comment by aaFn** [comment]
Closing the thread as this is working as designed.

Thank you, aaFn.
