### ISSUE TITLE
Clearer addon title, and simpler initial use as a bookmark folder finder

### ISSUE THREAD

**Issue by Twistyness** [aaFn/Bookmark-search-plus-2#88]
I just installed the addon. I almost gave up. I thought it had destroyed my bookmarks because **it removed all the leading spaces in my folder and bookmark titles** that I use to keep stuff in my preferred sort order when I resort the contents of folders and subfolders via "sort by name".

So I uninstalled it, and restarted Firefox. **My bookmarks were back to normal and everything was unchanged,** so I reinstalled the addon. **Need an on/off button I can put anywhere.** Versus disabling and enabling the addon via the _tools menu > addons._

Then I looked for a folder I had recently lost or forgotten its location. I saw a bunch of folders at the top with the word I was looking for in the titles. 

But I was interested in the whole folder tree above these folders. Looking below did not look like a folder tree. I almost gave up again. I am giving the honest initial experience of the average browser user. 

I came back later and clicked on one of the folders at the top, saw some changes below, but not at all clear what was happening. The sidebar space is so tight, and I use long titles for almost everything. Plus the space was completely filled up since I have tens of thousands of bookmarks and folders.

Finally after adjusting the top and bottom window size within the sidebar, and expanding the sidebar to its maximum width, **I found what I was looking for: the folder tree. Viola!**

Some suggestions for ease of use, and for helping people find this addon. 

**First, change the name of the addon to something immediately comprehensible. Such as: 
-Bookmark folder finder plus.** 

Greatly simplify the first part of the instructions on the addon page: 
https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2

**Use headings in the instructions: 
-Your bookmarks are safe! No changes are made by default.
-How to find a folder and its folder tree. 
-How to set up the window sizing in the sidebar.**

I suggest that the sidebar be much more expandable in width. **I would like it to be able to expand to the full width of the screen.** 

And I don't like addons that make changes without asking first. I don't know what the addon is doing with favicons, but I wasn't asked, so in the addon options I disabled what the addon was trying to do. **I normally have all favicons deleted and blocked anyway via the about:config settings.** Favicons slow things down. 

**Finally, I don't see a Paypal link anywhere.** Not here on your Github entry page for this addon, nor on the Firefox addon page on mozilla.org

**Comment by aaFn** [comment]
Hello @Twistyness , thank you for your detailed feedback, this is very useful
Let me try to address them one by one, or ask more questions if you allow me, to get that clear in my mind

1. Leading spaces
Not sure I understand what you mean. Leading spaces in the titles are preserved on display, at least in Windows and Linux (I can't test on IOS).
Would you mind putting a screen capture here to show me what is exactly removed, so that I can see if this can be corrected ?

2. On/off button
Yes, it is in the toolbar. Look for a yellow star with a "+" on it (or it might be hidden if you removed it from the toolbar). Clicking on it will make the sidebar appear / disappear.
Else you can use keyboard shortcuts (Ctrl-B to see the normal bookmark sidebar, and Ctrl-Q or Ctrl+Shift+B for BSP2 depending on the OS you are in)

3. What is happening when you click on a search result ?
See -> https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.46-)
Basically, this is most of the time showing where in your bookmark pane is the object you clicked on, temporarily opening folders in doing so (and they are restored to their normal state when you stop the search, by hitting ESC or clicking on the X in the search box).

4. Sidebar space / horizontal width of it
You can resize it within limits which are unfortunately fixed by Firefox, and cannot be changed by the add-on.
If you want to have a wider view, here is a method -> https://github.com/aaFn/Bookmark-search-plus-2/issues/71

5.Name of the add-on
Not really my choice :-) This add-on is a follow-up to an old add-on not anymore working with FF, which was called "Bookmark Search Plus". So I named this one "Bookmark Search Plus 2".

6. Instructions on the add-on page
This are good suggestions. I will have a go at it. Thank you.

7. Favicons
Yes, this is why I have set the option to disable favicons. The add-on is simply re-fetching them because of a limitation of Firefox API, which doesn't make them available :-(  (contrary to Chrome API .. we have a bug open on FF for that, but they didn't fix it yet).
There is no way the add-on can know your **about:config setting**, so you have to re-specify it at account level, sorry (again FF API limitation).

8. PayPal link
Yes, didn't have the time to look at that, will do one day :-)

Again thank you for the feedback. I'll take care of 1) if you can give me a little bit more details, of 6) (and one day of 8) ...).

aaFn

**Comment by Twistyness** [comment]
1. I attached a couple screenshots showing a few bookmark folders with and without leading spaces. Before and after the addon is active in the bookmark sidebar. 
![bookmark folder names with leading spaces](https://user-images.githubusercontent.com/47829768/53256376-b7038900-3695-11e9-98a4-07e281b8e310.jpg)
![bookmark folder names without leading spaces](https://user-images.githubusercontent.com/47829768/53256377-b79c1f80-3695-11e9-85cb-a8cc31d52b82.jpg)

**Comment by Twistyness** [comment]
1. I want the addon to do this while it is active. It helps in seeing deep folder trees. And it helps to see all the search results without using a horizontal scroll bar. 

My original point was that at first I thought the addon had permanently removed all the leading spaces. Since I have around 58,000 bookmarks (!) and many of them have leading spaces, I was wondering how old my latest bookmark backup was, and how much work I had lost. 

But I see that I can get back to my bookmarks via Ctrl-B. But I hate using keyboard shortcuts. I would prefer that just clicking the addon icon (yellow star with plus sign) would toggle the view in the bookmark sidebar. I see I can use the sidebar title itself to toggle via a menu, but that is slow and less intuitive.

**Comment by Twistyness** [comment]
I hope this addon doesn't try to "clean" my bookmarks, or remove duplicates, or do anything at all by default. The forced removal of duplicate bookmarks is why I don't use Chrome. Some pages I bookmark in multiple folders because the page is filed under multiple topics. I can't understand why Chrome developers are so clueless. Worst of all Chrome does it right away upon importing a set of bookmarks, without asking. At least when I tried it the last year or two.

**Comment by Twistyness** [comment]
4. Maybe you could make this work in the Firefox bookmark library. It uses the full width of the screen. This might make it easier to use, especially with the deep folder trees I have. But I don't know how much leeway Firefox gives you to use that library. It would be nice if one could click on an addon search result in the left pane, and see the folder tree in the right pane where there is a huge amount of space. My monitors are 27 inch here and 21 inch in the other room.

**Comment by Twistyness** [comment]
5. You can give any name you want to the addon. Many people want to see folders in bookmark searches. And many more want to see the folder tree. So they go to Firefox addons and search for something like "bookmark folder search" or "bookmark folder tree". The keyword being "folder". Your addon will be far down the list of addon search results. Even though your addon is the only one I currently know of that pulls up the folder tree. I haven't kept up with the addons though. 

So I suggest putting all the keywords in the addon name:
"**Bookmark folder tree and search**"

**Comment by Twistyness** [comment]
7. Does what the addon does with favicons change anything with my bookmarks? That is my number one concern with bookmark addons. I believe Firefox puts favicons in favicons.sqlite? Does the addon do anything with that file? When I disable the addon, or toggle back to my normal bookmark layout, is anything changed with anything to do with bookmarks. In other words if I remove the addon am I back to what I had before except for specific additions and removals and renaming I did myself since installation of the addon?

**Comment by aaFn** [comment]
Sorry, will come back in details to you later, but quick answer, rest assured that BSP2 does not do any cleaning, de-dup .. etc ... on your bookmarks. It is primarily a display and search tool. Only modifications to bookmarks are the ones you make from the interface.

Same for favicons.sqlite, it is not accessilbe by the add-on, ther eis no way to access files on the system, this is forbidden by FF. The favicons are retrieved from the site and stored in FF controlled local storage. Until FF makes them available, which is not yet the case :-(    https://bugzilla.mozilla.org/show_bug.cgi?id=1315616

**Comment by aaFn** [comment]
More detailed answers to your other points:

- Leading space : the collapse was not wanted, I simply didn't know about it. This effect is HTML default.
I corrected that in 2.0.54.
It is now preventing HTML from collapsing multiple spaces into one, to respect what people intended to do with multiple spaces.

- The toolbar icon can only control the add-on sidebar on or off. It cannot replace the add-on by another sidebar .. Security feature of Chrome and FF, so sorry, I have no easy way to toggle between BSP2 sidebar and the native bookmark sidebar.

- Add-ons cannot run within the Bookmark Library .. sorry again.
At least not today :-)

- Add-on name = by respect to the initial author alice0775 of the original extension, I do not want to change it.
Indeed, I do not want people to believe I invented this. I am just taking forward the work of somebody else which I found very useful, and made it live in the FF post Quantum world where it was not running anymore ...

Hope this gives you all the answers you need,
thank you, aaFn.

**Comment by aaFn** [comment]
I edited the add-on description page, as you rightfully suggested.

Thank you, aaFn.

**Comment by aaFn** [comment]
On the demand to get a wider sidebar size, since this is not possible, I added a conext menu on the magnifier glass and on any empty part of the sidebar body, to propose a context menu with an action to open BSP2 in a tab, for a full view :-)

Cf. https://github.com/aaFn/Bookmark-search-plus-2/issues/71

This will be in 2.0.54.

**Comment by Twistyness** [comment]
I keep grasping at the line between the top and bottom panes, but finding no way to pull it up or down. I suggest adding that function if Firefox allows it. Pulling on the corner is less intuitive.

**Comment by Twistyness** [comment]
I have changed my mind about the leading spaces. I like that you have now kept them. I find that when I look at a folder tree on the bottom pane, I recognize locations in my folder tree much easier. 

I had a hunch it might have been an HTML spaces setting that was deleting the spaces.

**Comment by Twistyness** [comment]
The instructions on the mozilla page do not tell how to toggle between default bookmarks and addon bookmarks. I suggest a heading called **"Toggle between default bookmarks and addon bookmarks"** or something similar. It should mention the main menu. Maybe **Main menu** should be a heading too. 

And please mention that clicking the addon icon activates the addon bookmarks. Not everyone will want to remember a keyboard shortcut. Me, for example.

**Comment by Twistyness** [comment]
I suggest creating a heading "**This is an adaptation of addons by Alice0775**". You have already given her credit in the instructions. This is good enough. Wikimedia Commons gives attribution to initial creators of images by some text on the image description page, not in the image title, nor on the image itself. That is discouraged, and attribution is removed from most images. Image titles are clarified over time so that they get used more, and so that they show up better and more accurately in search results. 

The same is true for Firefox addons. This is now a wonderful addon that would be used by hundreds of thousands if they only knew about it.

**Comment by Twistyness** [comment]
I suggest making **a separate addon that can expand default addons to a full screen new tab** as you did with this bookmark folder searcher.

**Comment by Twistyness** [comment]
Does mozilla.org allow you to **add a Paypal link to that addon front page:** 
https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2

**Comment by Twistyness** [comment]
A really great thing about your addon is the **horizontal scroll bar it adds at the bottom.** I really miss it when I go back to default bookmarks. I have **many long bookmark titles** and they are impossible to read unless I waste time **hovering my cursor over each one individually.**

**Comment by aaFn** [comment]
Hello @Twistyness, yes me too .. this is really missing from the native sidebar, also for when bookmark trees are very deep and so go far on right ...

Paypal = I guess so, I didn't work that out yet.

I modified the add-on description as you suggest, mentioning first the toolbar icon.

Resize handle = does not look like anything else than a corner handle is available in standard -> https://developer.mozilla.org/en-US/docs/Web/CSS/resize
I know JQuery can allow some tricks on that, but I am not using it, this is making code too complex and big.

**Comment by Twistyness** [comment]
How about keeping the old title, and making it longer:
**Bookmark search plus 2, with folder search.** :)

**Comment by Twistyness** [comment]
I have **2 about:config settings** that I use **to prevent favicons:**
browser.chrome.image_icons.max_size 
browser.chrome.site_icons

Does the addon honor favicon settings in about:config?

Anything that slows down the first few seconds or minutes of use of the addon will make many people immediately stop using it, thinking it is broke, or using too many background resources. They will move on the next addon from the addon search results, and try it instead. Especially for a new addon with few users. 

I make a great effort to stop background activities, because Firefox in the past was notorious for slow web page access.

**Comment by Twistyness** [comment]
The addon description page does not mention its main feature (folder searching with folder tree results) until the 5th paragraph. I rarely read that far unless I already like what I read in the first couple paragraphs. Or if the addon title tells me I may like what it does. 

The first paragraph of the detailed description is actually the true summary: 

Detailed description
**BSP2 add-on allows you to quickly show where is your bookmark located in the tree folder,** automatically opening folders along the way if they are closed = under which parent folder, its grand-parent .. etc ... => the full chain from top.

**Comment by aaFn** [comment]
Hello @Twistyness , the about:config settings you mention are not accessible by add-ons.
Here is the exact set of what is accessible (not a lot ..) -> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings

That is why I have to manage that option by myself in the add-on Options page.

On description, ok, I have put closer to the start the meaningful description to make it more visible.

**Comment by aaFn** [comment]
Closing as not active anymore since nearly 3 weeks.

Thank you much for the help on the presentation / description page, for highlighting the problem with the multiple spaces, and for leading to open BSP2 in a page as a feature and not anymore a debug action.

Best regards, aaFn.
