### ISSUE TITLE
Add a way to close the context menu if you dont select an item

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#9]
If you right click and want to exit the context menu... now you can't except if you choose to click on one of it item.

Maybe it's a Firefox API Menu component issue ?

I would suggest a least that Escape keyboard push should quit the context menu.

**Comment by NicolasWeb** [comment]
A click anywhere else in the UI should too, like for any context menu. But not sure how feasible it is... ;-)

**Comment by aaFn** [comment]
So a click anywhere outside the sidebar never gets to the add-on ... it doesn't know, so that can't do anything.
A click anywwere inside the add-on sidebar does close the context menu, at least in Windows and Linux.
Let me know if not.

**Comment by aaFn** [comment]
@NicolasWeb , implemented a watch for Esc key. When occurring while the sidebar has focus, any menu is closed.
Let me know if any problem, or I should close. Thank you.

**Comment by aaFn** [comment]
Closed
