### ISSUE TITLE
Feature request : having a better view of general structure

### ISSUE THREAD

**Issue by eseb63** [aaFn/Bookmark-search-plus-2#95]
i have to reorganize my bookmarks : i have a lot, and not always took time to create the folders immediately so a lot of bookmarks are not classified ; after loading the treeview,  it's quite difficult to have a general view of the structure :
- folders are not all grouped under the parent but mixed with items : i have sometimes to search them 
- folders and items are not sorted (or i dont understand how)

my suggestions :

1) folders grouped first just under their parent, then items
2) alphabetical sort at each level (folders and items)
3) drag and drop is unconfortable when many folders are opened (the treeview is too large) : we need a "clean" treeview for that with collapsed folders (and expanding the nested targets during drag) 

	a) provide an option to open the treeview with collapsed folders
	b) provide a button to collapse all to retrieve this clean state (or locally for the sub-folders of a specifid level with a context menu option)
	
4)using a listview to display the items (like in the bookmark manager) would also be a way to keep the treeview more lisible?

thanks for your attention

**Comment by aaFn** [comment]
Hello @eseb63.

On 1), BSP2 is following the order of bookmarks and items as they are stored in the FF tree.

On 2) There is a "Sort by name" option at the level of each folder, like by the way in the native FF bookmark sidebar, and you can use both indifferntly to sort things folder by folder. However, no global sort function to apply recursively.

On 3), one way to make things easier is to right click on the Magnifying glass in the search box, and open BSP2 in a web page. Then you can drag and drop between the sidebar and the web page, showing two views of the same bookmark tree. This can help achieve what you want I believe.

On 4), not sure I understand what you mean ? Maybe the Bookmark manager is the best way to do what you want, BSP2 does not intend to replace it, simply to add better search functions on bookmarks to quickly locate where are given objects corresponding to search terms.
Or let me know if I am missing something.

All yours, aaFn.

**Comment by eseb63** [comment]
Hi @aaFn 
1) Do you have a special reason not to apply "sort by name" by default and keep a sort order that may present the tree  as a bit "anarchic"?

2) i didn't see this context menu option, because i searched a global one ; so i applied the sort by name folder by folder (it would more convenient to leave BSP2 make it ?)

3) it should help but it's only a partial workaround : the unorganized state of the treeview after a while will remain ? i can of course collapse all folders i want but recursive tasks are a bit tedious for humans, i would prefer leave this to BSP2 :) (sorting by name is a one shot task, "clean" the treeview is a more regular one)

4) i simply meaned that a single treeview to handle a deeply nested structure with potentially several thousands of leaves inevitably reaches his limit in term of lisibility  : so handling the leaves in an associated listview would permit i think  a better lisibility (not necessarily  to replace the firefox bookmark manager, but to make BSP2 more comfortable for large bookmark collections)?

**Comment by aaFn** [comment]
Hello @aaFn 
1. Yes, this is to act like the native Bookmark sidebar. People do not want to sort by name by default, they arrange the bookmarks in the order they want by drag & drop, insert .. etc ;. at the place they want, and they expect things to stay like they ordered them.

**Comment by eseb63** [comment]
Hello @aaFn 
1. You can't generalize so : some users may expect this comportment, others may prefer alphabetical sort, without having to apply it manually in each folder ; you could satisfy all easily with a user choice in the addon options, or another way.

I saw that JohnLukeBentley had the same need that mine : collapse the nodes at a more global level than a folder  (#31 one year ago) ; i agree that  global expanding is less  usefull (but it's done if collapsing is implemented) ; you said you didn't understand the usecase : simply having a clean view of the tree, at the opening or after some use. These features are classic ones for a treeview, require a quite limited coding effort, would satisfy number of users, so why to refuse to implement them ? please keep in mind that your users may have different needs and habits than yours ?

**Comment by aaFn** [comment]
Hello @eseb63 , agree on different habits, but please understand that each feature is time and effort, so I need to prioritize. I said yes to JohnLukeBentley in #31 on some of them, that will come.

**Comment by eseb63** [comment]
Hello @aaFn ,
I know that : as i said before, i was developer myself :)
but i think this coding effort would be quite limited (a recursive parameterized routine and you expand/collapse at any level, right?)

i have read again #31 : i don't see clearly you said yes to implement the JohnLukeBentley's requests ; you just say 

> __**I could** agree to make the effort of adding the keyboard shortcuts. For menu entries, I would need to get more convinced though
> 
i could :)
i don't see either a todo tag, neither a "for later consideration" one ...

also keep in mind that basic users use the mouse and not the keyboard to navigate in the tree : if you just implement the keyboard shortcuts, many users simply won't see they can do that ?

i think also it would be helpful to add an option to open (or not) the tree with collapsed nodes, like in the Windows Explorer (just a call to the precedent routine...)

**Comment by aaFn** [comment]
#31 is now solved in 2.0.71, closing this one also, thanks, aaFn.
