### ISSUE TITLE
BSP2 can not delete a bookmark

### ISSUE THREAD

**Issue by tofix67** [aaFn/Bookmark-search-plus-2#97]
Since a while I can see a bookmark, only in BSP2 an not in standard bookmarks.
It can not be moved or deleted.

BSP2:
![grafik](https://user-images.githubusercontent.com/50299276/57196988-377e1a00-6f62-11e9-9cbf-0f665238e521.png)

Original FF:
![grafik](https://user-images.githubusercontent.com/50299276/57197008-70b68a00-6f62-11e9-85f1-057f565cae85.png)

You can see "Thunderbird einrichten.......One.com" in BSP2 :-(

Is there a wax to "refresh" BSP2 base?

**Comment by aaFn** [comment]
Hello @tofix67, could you try first in the BSP2 add-on options page to press the button `Reloaf from FF API now` ?
There might be a de-synchronization between the BSP2 cache and the main FF DB, it looks like this happens sometimes lately when some messages are sent to BSP2 by FF, but not properly executed inside FF itself and BSP2 gets faster than FF native .. :-(

**Comment by tofix67** [comment]
Hi aaFn ;-)

> 
> 
> Hello @tofix67, could you try first in the BSP2 add-on options page to press the button `Reload from FF API now` ?
> There might be a de-synchronization between the BSP2 cache and the main FF DB, it looks like this happens sometimes lately when some messages are sent to BSP2 by FF, but not properly executed inside FF itself and BSP2 gets faster on their execution than FF native .. :-(

Thanks  for your very very fast answer - it works :-)
I thought so... but i was not sure, before!

I'm not a English native speaker...
I could you help to translate this coll part to German-

Tom

**Comment by aaFn** [comment]
Hi @tofix67, good. Closing the issue than.

Thanks for he translatio offer, I need first to implement the translation mechanism though.
I am recording a note of your possible help in #62 :-)
