### ISSUE TITLE
Lost Bookmarks

### ISSUE THREAD

**Issue by WRichardR** [aaFn/Bookmark-search-plus-2#98]
Hello,
I had to Refresh Firefox. I did backup my Bookmarks. 
I did lose my Bookmarks in Firefox. I was able to Restore them through them through Restore in the Library.
The Bookmarks are there now.
I then tried Bookmark-search-plus-2.
The Bookmark tree is not where it normally should be ? There is,
Bookmarks Toolbar
Bookmarks Menu
Other Bookmarks
There is nothing in those folders.
Can someone please help me with what might have happened and how to fix this ?
Before Refresh, the Add-On worked great.
Thanks,
Wayne

**Comment by aaFn** [comment]
Hello @WRichardR , strange ..  did you import / restore your bookmarks after reinstalling BSP2 in the refreshed Firefox, or before ?

At any rate, could you to go in the BSP2 add-on options page ando press the button `Reload from FF API now` ?

**Comment by WRichardR** [comment]
OK, That has taken care of most of my problem. Thing I am have trouble with at the moment. I seem to have Four instances of Firefox open in Task Manages when I open One Firefox browser. I think that is causing me bunches of problems. Do you know where I can go to ask for help with that. I guess that is not quite what you would deal with here ?
Thanks for your help. It has been Great,
Wayne

**Comment by WRichardR** [comment]
The reason I ask is I took your advice and got the bookmarks back. The first time, I would close my browser, open a new one, and the bookmarks disappeared. I closed that browser and opened a new one and they reappeared.
The only sense I make is the multiple cases in Task Manager, and I do not know why they are there ? 
Wayne

**Comment by aaFn** [comment]
Well, Firefox has a protection normally which doesn't allow it to run multiple times.
When you try, it says to you there is already an instance running and it doesn't fire ..
Or if you try to start the exact same instance (same version, same execution path ..), then it simply opens a new window.

I would assume that you are in the second case .. so when closing Firefox, to really close it, you need to make sure you close all windows, or else it is still running ...

If not that, sorry, not really sure of what is going on. You could go and ask on the Mozilla forum then (sorry, I do not have the link handy, I am traveling and am not at home with my whole collection of own bookmarks :-) )

**Comment by aaFn** [comment]
Hello @WRichardR, since your ùain question is resolved, can we close the issue ?
Thank you, aaFn.

**Comment by aaFn** [comment]
Closing as resolved question.
Let me know if we need to reopen, thank you, aaFn.
